### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Cannot process toolwindow Resource Connections (Deprecated)

### ISSUE THREAD

**Issue by flshbt** [microsoft/azure-tools-for-java#8030] opened 2023-12-01 10:14 UTC
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,3840x1552,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Cannot process toolwindow Resource Connections (Deprecated)
<REDACTED: Generic Secret>
at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindowFactory.shouldBeAvailable(ResourceConnectionExplorer.java:139)
```

**Comment by Flanker32** [comment] 2023-12-06 12:07
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7889

**Comment by Flanker32** [comment] 2023-12-06 12:07
@flshbt Thanks for your report and sorry for the trouble, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7889

**Closed as completed by Flanker32** 2023-12-06 12:07 UTC
