### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by mattmadhavan-mgm** [microsoft/azure-tools-for-java#5506] opened 2021-07-09 22:19 UTC
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1193x920,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=booking-acrs-migration-services, containerState=DISPOSE_COMPLETED, componentStore=/Users/matt/working/mgm/acrs/qry_param/booking-acrs-migration-services) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=booking-acrs-migration-services, containerState=DISPOSE_COMPLETED, componentStore=/Users/matt/working/mgm/acrs/qry_param/booking-acrs-migration-services) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(

**Comment by wangmingliang-ms** [comment] 2021-07-12 06:36
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-12 06:36 UTC
