### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 4c232d68-6812-4f11-a1ae-fa26f8dcc2dd] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed. com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by kokibas** [microsoft/azure-tools-for-java#7720] opened 2023-07-26 04:16 UTC
IntelliJ build version: 2022.2.4 IU-222.4459.24
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.74.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 4c232d68-6812-4f11-a1ae-fa26f8dcc2dd] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplie

**Comment by Flanker32** [comment] 2023-07-31 05:13
@kokibas Thanks for your report and sorry for the late response. It seems to be an authentication issue, could this issue be stable reproduced? If so, could you please share the authentication method and error stack for us for error investigation? Many thanks!

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:13
Duplicate of #7708

**Closed as completed by wangmingliang-ms** 2023-09-19 02:13 UTC
Labels: Tool: IntelliJ, need more info, Module: Auth
