### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by icodetea** [microsoft/azure-tools-for-java#7228] opened 2023-01-11 11:39 UTC
IntelliJ build version: 2022.3.1 IU-223.8214.52
OS: Linux
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.72.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,2,28,2502x1412,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:38
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-03-20 01:38 UTC
