### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by Eragon6080** [microsoft/azure-tools-for-java#7751] opened 2023-08-02 07:52 UTC
IntelliJ build version: 2023.2 IU-232.8660.185
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.79.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1441x853,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Scheduler worker in group main failed with an uncaught exception
   reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$streamingLogs$0(StreamingLogSupport.java:58)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: https:/<REDACTED: user-file-path>?follow=true&tailLines=300&tenantId=e06763e9-f97d-437d-a41f-33c197d92714&tailLines=300&limitBytes=1048576&sinceSeconds=300&follow=true
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$strea

**Comment by wangmingliang-ms** [comment] 2023-08-08 00:09
Duplicate of #7742

**Closed as completed by wangmingliang-ms** 2023-08-08 00:09 UTC
