### ISSUE TITLE
Intellij Plugin Fail to Initialize

### ISSUE THREAD

**Issue by msalman86** [Microsoft/azure-tools-for-java#22] opened 2016-08-26 04:34 UTC
Hey,

**OS**: OS X 10.11.6
**Intellij**: Ultimate 2016.2.2
**Plugin**: 1.4.1

```
Plugin 'com.microsoft.tooling.msservices.intellij.azure' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NullPointerException
    at com.microsoft.intellij.AzureActionsComponent.initComponent(AzureActionsComponent.java:85)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:430)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:443)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:385)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by martinsawicki** [comment] 2016-09-06 19:37
let's take a look. we didn't see this before.

**Comment by martinsawicki** [comment] 2016-09-08 16:13
we were not able to reproduce this issue on our end, but seeing where the NPE is in the reported exception, this may be an INtelliJ bug in some specific version of intelliJ or under some specific circumstances. Hard to say, but our "fix" will be a wokraround that will check if the suspected IntelliJ API unexpectedly returns null and the side effect will be that Publish To Web App will not be available on one of the menus. Releasing this update in probably in a day or two.

**Comment by martinsawicki** [comment] 2016-10-27 21:28
update with the potential fix released so closing

**Closed by martinsawicki** 2016-10-27 21:28 UTC
