### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped java.lang.InterruptedException

### ISSUE THREAD

**Issue by samgarcia-cocacola** [microsoft/azure-tools-for-java#7953] opened 2023-10-24 15:45 UTC
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.81.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1901x1044,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=java.lang.InterruptedException
	at <REDACTED: user-file-path>(Native Method)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:258)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:157)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:93)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
```

**Comment by samgarcia-cocacola** [comment] 2023-10-24 15:46
This error occurred when clicking the Stop button

**Comment by wangmingliang-ms** [comment] 2023-11-03 07:18
Duplicate of #7907

**Closed as completed by wangmingliang-ms** 2023-11-03 07:18 UTC
