### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4533b828)

### ISSUE THREAD

**Issue by AlanChaney** [microsoft/azure-tools-for-java#8131] opened 2024-02-01 16:11 UTC
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.84.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2296x1363,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$1@f556eec,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4533b828)
	at com.microsoft.azure.toolkit.intellij.storage.code.spring.StoragePathPrefixCompletionProvider.addCompletions(StoragePathPrefixCompletionProvider.java:30)
```

**Comment by wangmingliang-ms** [comment] 2024-02-02 08:06
Duplicate of #8109

**Closed as completed by wangmingliang-ms** 2024-02-02 08:06 UTC
