### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by sudheermaganti** [microsoft/azure-tools-for-java#7246] opened 2023-01-23 20:08 UTC
IntelliJ build version: 2022.2 IU-222.3345.118
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.72.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1728x1080,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2023-01-29 09:41
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6844

**Closed as completed by Flanker32** 2023-01-29 09:41 UTC
