### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by sharon-dinara** [microsoft/azure-tools-for-java#6664] opened 2022-06-01 16:07 UTC
#### Setup

IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.64.0-2021.3

####  Describe the bug
cannot sign in with any method. cli option never enabled. tried the rest which worked, but the resouce connector never noticed

####  To Reproduce
try to sign in. 

#### Exception or Stack Trace
none
#### Screenshots

Add screenshots to help explain your problem if available.

**Comment by wangmingliang-ms** [comment] 2022-06-03 03:27
Hi, @sharon-dinara , 
is your Mac OS an M1 or Intel? Can you try [this way](https://github.com/microsoft/azure-tools-for-java/issues/6576#issuecomment-1106180545) for temporary?

There is a known issue [#6576]  on Mac M1 which cause user not able to login, the cause should be that *the official Java Support for Mac M1 architecture was recently supported in Java 17 GA, and old java version (lower than Java 17) are not stable on Mac M1*, but IntelliJ are still using Java 11 or older.
We noticed that [JetBrains is to upgrade the runtime to Java 17 since 2022.2](https://blog.jetbrains.com/idea/2022/05/intellij-idea-2022-2-eap-1/).

**Comment by wangmingliang-ms** [comment] 2022-06-03 03:27
Duplicate of #6576

**Closed as completed by wangmingliang-ms** 2022-06-03 03:27 UTC

**Comment by Flanker32** [comment] 2022-06-09 04:55
@sharon-dinara Thanks for your report, we've released the fix to the dev channel, could you please try the bits and see whether the issue could be reproduced? You may get the bit [here](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij/versions/dev)
