### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException

### ISSUE THREAD

**Issue by ashokrajar** [microsoft/azure-tools-for-java#6302] opened 2022-01-06 18:12 UTC
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.60.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException
	at com.intellij.packaging.elements.PackagingElement.update(PackagingElement.java:136)
	at com.microsoft.azure.hdinsight.projects.HDInsightModuleBuilder.lambda$moduleCreated$0(HDInsightModuleBuilder.java:136)
```

**Comment by fengshuaihu** [comment] 2022-12-28 06:20
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6478

**Closed as completed by fengshuaihu** 2022-12-28 06:20 UTC
Labels: Module: HDInsight
