### ISSUE TITLE
[IntelliJ] Uncaught Exception Scheduler worker in group main failed with an uncaught exception java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager$Holder

### ISSUE THREAD

**Issue by NCherfaoui** [microsoft/azure-tools-for-java#9222] opened 2024-08-27 19:53 UTC
IntelliJ build version: 2024.2.0.2 IU-242.20224.419
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.91.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,1386x769,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager$Holder
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.getInstance(AzureTaskManager.java:49)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewStartupActivity.lambda$execute$2(WhatsNewStartupActivity.java:35)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.InterruptedException [in thread "boundedElastic-1"]
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager$Provider.getTaskManager(IntellijAzureTaskManager.java:144)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager$Holder.loadTaskManager(AzureT

**Comment by wangmingliang-ms** [comment] 2024-11-06 01:37
Duplicate of #8473

**Closed as completed by wangmingliang-ms** 2024-11-06 01:37 UTC
