### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by SagivDev** [microsoft/azure-tools-for-java#6917] opened 2022-09-07 10:43 UTC
IntelliJ build version: 2022.1.1 IU-221.5591.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.68.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x834,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.lambda$addAppSettings$5(AppSettingsTable.java:98)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.addAppSettings(AppSettingsTable.java:98)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.table.AppSettingsTable.setAppSettings(AppSettingsTable.java:125)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.component.table.FunctionAppSettingsTable.loadLocalSetting(FunctionAppSettingsTable.java:33)
	at com.microsoft.azure.toolkit.intellij.leg

**Comment by SagivDev** [comment] 2022-09-07 10:47
O

**Comment by SagivDev** [comment] 2022-09-07 10:49
Occurs when pressing on Modify Run Configuration.... in Azure Function drop down menu (the green play button next to Azure Function declaration in the source code)

**Comment by Flanker32** [comment] 2022-09-23 08:40
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6935

**Closed as completed by Flanker32** 2022-09-23 08:40 UTC
Labels: Type: Bug, Module: Azure Functions, Reason: fixed
