### ISSUE TITLE
[IntelliJ] Uncaught Exception  java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.telemetry.AzureTelemeter <clinit> requests com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#8488] opened 2024-07-24 07:43 UTC
IntelliJ build version: 2024.2 Beta IU-242.20224.91
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.90.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,0,824x530,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$setTransparentTitleBar$customBorder$1@5b15c75a,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.telemetry.AzureTelemeter <clinit> requests com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore.getInstance(IntellijStore.java:36)
	at com.microsoft.azure.toolkit.intellij.common.telemetry.IntelliJAzureTelemetryCommonPropertiesProvider.getInstallationId(IntelliJAzureT

**Comment by wangmingliang-ms** [comment] 2024-07-29 06:37
Duplicate of #8473

**Closed as completed by wangmingliang-ms** 2024-07-29 06:37 UTC
