### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by nextjedi** [microsoft/azure-tools-for-java#7814] opened 2023-08-31 05:33 UTC
IntelliJ build version: 2023.2.1 IC-232.9559.62
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Scheduler worker in group main failed with an uncaught exception
  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:47)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:259)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.doGetById(AbstractAzService.java:110)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.getById(AbstractAzService.java:102)
at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.Sprin

**Comment by wangmingliang-ms** [comment] 2023-11-03 07:24
Duplicate of #7783

**Closed as completed by wangmingliang-ms** 2023-11-03 07:24 UTC
Labels: Module: Auth
