### ISSUE TITLE
[MAC]Add docker support issue

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2804] opened 2019-03-01 08:29 UTC
### Environment:
1. OS: Mac
2. IDE version
```
IntelliJ IDEA 2019.1 EAP (Ultimate Edition) Build #IU-191.5849.21, built on February 27, 2019
IntelliJ IDEA 2019.1 EAP (Community Edition) Build #IC-191.5849.21, built on February 27, 2019
```
3. Bits: 3012

### Steps:
1. Open a test project
2. Right the project and select Azure -> add docker support

### Actual Result:

1. Dockerfile doesn't display in the project root path
2. The docker file doesn't open in the editor

![image](https://user-images.githubusercontent.com/28860891/53625713-ceff7d80-3c3e-11e9-93dd-b24bc82d9392.png)

After synchronizing project, Dockerfile displayed in the project root path

### Expect result:

1. Dockerfile is generated in the project root path
2. The docker file is opened in editor

![image](https://user-images.githubusercontent.com/28860891/53625782-ffdfb280-3c3e-11e9-9db9-682ef453dee6.png)

**Comment by ZhengJun003** [comment] 2020-06-15 10:06
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738765

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: IntelliJ, Internal Test, P3, bug, docker-host, transfter
