### ISSUE TITLE
[IntelliJ] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.

### ISSUE THREAD

**Issue by saimaheshwaran** [microsoft/azure-tools-for-java#9283] opened 2024-08-29 23:14 UTC
IntelliJ build version: 2024.2.0.2 IU-242.20224.419
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.91.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x944,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
Caused by: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
```

**Comment by wangmingliang-ms** [comment] 2024-09-03 05:44
Duplicate of #8134

**Closed as completed by wangmingliang-ms** 2024-09-03 05:44 UTC
