### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: f3e1c9eb-3acb-4c7b-909d-3d6cfc99ffeb] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed. com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.

### ISSUE THREAD

**Issue by tsoloane** [microsoft/azure-tools-for-java#7550] opened 2023-05-16 07:54 UTC
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1710x1070,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: f3e1c9eb-3acb-4c7b-909d-3d6cfc99ffeb] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed., throwable=com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
Trace ID: fab7cd00-d80e-42f1-9cf7-ec078b0a2800
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.j

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:06
Duplicate of #7446

**Closed as completed by wangmingliang-ms** 2023-09-08 06:06 UTC
