### ISSUE TITLE
Can't create key vault when Device login 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1138] opened 2017-10-19 05:01 UTC
I can only  repro one time

1. Interactive login 
2. Right click Docker Host node and select Publish
3. New a docker host 
4. Fill  some information and check Save credentials ...

![image](https://user-images.githubusercontent.com/22470312/31754872-2397017e-b4cd-11e7-9c8b-9cb3b4daa736.png)
5. Then publish, an error pops up when creating key vault
![image](https://user-images.githubusercontent.com/22470312/31754903-4e35d69e-b4cd-11e7-98ac-e186a8364d87.png)
LOG:
```
WARN: Unexpected error creating Azure Key Vault moanjardocekr1kv - Status code 401, {"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"date":"2017-10-19T03:15:29","requestId":"f8a507e5-940f-4aa5-a212-9c814d875f12","values":null}}

WARN: Unexpected error creating Azure Key Vault moanjardocekr1kv - Status code 401, {"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"date":"2017-10-19T03:15:29","requestId":"f8a507e5-940f-4aa5-a212-9c814d875f12","values":null}}
: Status code 401, {"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"date":"2017-10-19T03:15:29","requestId":"f8a507e5-940f-4aa5-a212-9c814d875f12","values":null}}
com.microsoft.azure.management.graphrbac.GraphErrorException: Status code 401, {"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"date":"2017-10-19T03:15:29","requestId":"f8a507e5-940f-4aa5-a212-9c814d875f12","values":null}}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.graphrbac.implementation.UsersInner.getDelegate(UsersInner.java:465)
	at com.microsoft.azure.management.graphrbac.implementation.UsersInner.access$200(UsersInner.java:44)
	at com.microsoft.azure.management.graphrbac.implementation.UsersInner$16.call(UsersInner.java:452)
	at com.microsoft.azure.management.graphrbac.implementation.UsersInner$16.call(UsersInner.java:448)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Eskibear** [comment] 2017-10-19 06:55
cannot reproduce. 
please update if there're any stable steps to reproduce it.

**Comment by bsaby** [comment] 2018-12-13 06:53
Build: 3.16.0 pre-release package
Now we can stably reproduce this error.

Requirments:
1. Login method: Interactive
![image](https://user-images.githubusercontent.com/22470312/49920557-91b00d00-fee5-11e8-9073-7e887df7e5ed.png)
2. Same repro steps as first comment

Result: 
![image](https://user-images.githubusercontent.com/22470312/49920722-3599b880-fee6-11e8-948a-3f2368b9188e.png)

```
Failed to Create Azure Key Vault

com.microsoft.azure.docker.model.AzureDockerException: Unexpected argument values; azureClient, vault name, hostName, resourceGroupName, region and userName/servicePrincipalId cannot be null
	at com.microsoft.azure.docker.ops.AzureDockerCertVaultOps.createOrUpdateVault(AzureDockerCertVaultOps.java:111)
	at com.microsoft.intellij.docker.utils.AzureDockerUIResources$3.run(AzureDockerUIResources.java:333)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Eskibear** [comment] 2018-12-13 16:02
@bsaby What if you sign in with the legacy method? (2nd one)

**Comment by bsaby** [comment] 2018-12-14 01:58
Try to publish as Docker Container with Legacy login method using the same build.

Result:
Try to publish three times and they all can create key vaults successfully.

**Comment by ZhengJun003** [comment] 2020-06-15 02:20
According to this issue: #4353, can't reproduce this issue

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738767

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: Eclipse, IntelliJ, Internal Test, P3, bug, docker-host, stacktrace, transfter
