### ISSUE TITLE
[intelliJ][Reader account]Warning message could not show completely.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3051] opened 2019-04-17 08:04 UTC
Build:
azure-toolkit-for-intellij-2019.1.develop.1097.04-17-2019

Repro Steps:
1. Sign in Azure with reader account.
2. Create a HDInsight configuration.
3. Choose an unlinked spark cluster.
Result:
Warning message could not display completely.
![image](https://user-images.githubusercontent.com/35950097/56270766-7e2de080-6129-11e9-9322-79ee9140649e.png)
4. Click OK button to save the configuration. 
5. Click icon to remotely run the configuration.
Result:
Warning message include two period.
![image](https://user-images.githubusercontent.com/35950097/56271069-2cd22100-612a-11e9-92c2-cad6d3b1180d.png)

**Comment by t-rufang** [comment] 2019-04-17 08:23
First issue in step 3 is fixed in Develop 1099. Will fix the second one in step 5 later.

**Comment by v-jiche** [comment] 2019-04-17 12:21
Build: 1010
For windows: 
![image](https://user-images.githubusercontent.com/35950097/56287184-45543280-614e-11e9-927f-232c0227ee43.png)
For Linux:
![image](https://user-images.githubusercontent.com/35950097/56287220-57ce6c00-614e-11e9-9cb2-dd81c123bd0d.png)

**Comment by t-rufang** [comment] 2019-04-19 06:39
HI @v-jiche , for `...` in `to the selected cluster...`, it's by design. If you mouse over the waning message, you will see the complete message.
For `...` in `Link the clust...`, it is a UI bug and is duplicate with #3025 .

**Comment by jingyanjingyan** [comment] 2019-05-30 03:42
Close as duplicate

**Closed by jingyanjingyan** 2019-05-30 03:42 UTC
Labels: HDInsight, IntelliJ, UX, duplicate
