### ISSUE TITLE
[Eclipse] Storage Account -> Create button does not display properly

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#418] opened 2017-05-12 08:07 UTC
Released build.
Repro steps:

1. Right click Storage Accounts and choose Create Storage Account...
2. Type Name
3. Resourse group choose Use existing（Picture 1）
**EXPEXT**: If there is a value in use existing list ,Create button should be available.
**RESULT**: Create button unavailable
4. Change name
5. Resourse group choose Create new（Picture 2）
**EXPEXT**:If no value in Create new list , Create button should be unavailable.
**RESULT**: Create button available

**Picture 1**
![image](https://cloud.githubusercontent.com/assets/22470312/25988824/19f4b130-372c-11e7-86c1-d98210763ef5.png)
**Picture 2**
![image](https://cloud.githubusercontent.com/assets/22470312/25988943/a941191e-372c-11e7-811e-a27e00606f0f.png)

**Comment by andxu** [comment] 2020-06-11 13:52
Can only reproduce picture 1
![image](https://user-images.githubusercontent.com/17075863/84392971-99ad5200-ac2d-11ea-8fae-958dae9f6f06.png)

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738806

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, Internal Test, P3, StorageExplorer, bug, transfter
