### ISSUE TITLE
[IntelliJ] Context menu isn't popped up when you right click on *Virtual Machine* (not the text area)

### ISSUE THREAD

**Issue by JunyiYi** [Microsoft/azure-tools-for-java#313] opened 2017-04-12 17:31 UTC
**OS**
MacOS Sierra

**IDE**
IntelliJ 2016.3

**Plugin**
azure-toolkit-for-intellij.2016.79.04-12-2017.zip

**Feature**
Context menu not shown in Azure Explorer

**Repro Steps**
1. Select the node in Azure Explorer (for example "Virtual Machine")
2. Right click that node in the far from the text (maybe somewhere on the right side)
3. The context menu doesn't show up (only when you click on the text area it shows up)

Take a look at the IntelliJ built-in tree nodes (like the one in Project Explorer), right-click anywhere of a node will trigger the context menu. It would be hard for a user to click the node if the name of the node is very short (like a letter "i").

**Comment by martinsawicki** [comment] 2017-04-12 17:59
@lenala duplicate of that other issue that we cannot fix for now?

**Comment by lenala** [comment] 2017-04-12 18:04
duplicate to #300.

**Comment by martinsawicki** [comment] 2017-04-12 18:09
closing as dupe then

**Closed by martinsawicki** 2017-04-12 18:09 UTC
Labels: bug-bash, duplicate, IntelliJ
