### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by sebyku** [microsoft/azure-tools-for-java#7531] opened 2023-05-10 08:07 UTC
IntelliJ build version: 2023.1.1 IC-231.8770.65
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2023-06-28 02:38
Duplicate of #7641

**Closed as completed by Flanker32** 2023-06-28 02:38 UTC
