### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by gerardv** [microsoft/azure-tools-for-java#7232] opened 2023-01-15 20:17 UTC
IntelliJ build version: 2022.3.1 IU-223.8214.52
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.72.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.action.DeployWebAppAction.execute(DeployWebAppAction.java:46)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceIntelliJActionsContributor.lambda$registerHandlers$16(AppServiceIntelliJActionsContributor.java:118)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:102)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObserva

**Comment by wangmingliang-ms** [comment] 2023-04-03 06:22
Duplicate of #7020

**Closed as completed by wangmingliang-ms** 2023-04-03 06:22 UTC
