### ISSUE TITLE
Azure China->Can't deploy .jar file to a new created Windows web app immediately

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2042] opened 2018-09-18 08:38 UTC
Build used: dev741
Deploy to a new web app failed with error 'Upload failed after 3 times of retry'
![image](https://user-images.githubusercontent.com/22470312/45675026-e5b68a00-bb60-11e8-967f-1fff0c5dfb84.png)

But can deploy successfully after a while
![image](https://user-images.githubusercontent.com/22470312/45674495-d551df80-bb5f-11e8-86aa-4a9bd4ba9ad5.png)

**Comment by SummerSun** [comment] 2018-09-18 09:09
Update the title to avoid the confusion that the issue is not just reproed in Azure China region, but also in other regions.

**Comment by SummerSun** [comment] 2018-09-18 09:09
@bsaby Fixed. Please help verify with the latest bits.

**Comment by SummerSun** [comment] 2018-09-18 11:43
Investigating.

From the exception message `java.net.UnknownHostException: qisun-webapp-180918193836.scm.azurewebsites.net`. 
But the host is not the value we get from `webApp.defaultHostName()`.

**Comment by bsaby** [comment] 2018-09-19 06:13
Verify this issue using build: dev750
 After .jar deployment, click the URL, the request always timed out after a long time load.
![image](https://user-images.githubusercontent.com/22470312/45734102-ce85a400-bc15-11e8-9a3f-7eaaeb0507be.png)
![image](https://user-images.githubusercontent.com/22470312/45734106-d0e7fe00-bc15-11e8-89b8-2d511c672675.png)

And request timed out issue also repro in global environement.

**Comment by Eskibear** [comment] 2018-09-21 14:09
This should work well in current version, as we fallback to use "ftp deploy". When issue for "zipDeploy" is resolved, we can have a try with it.

**Comment by ZhengJun003** [comment] 2020-06-12 09:52
Because azure china accounts not ready, so can't reproduce this issue.

**Comment by andxu** [comment] 2020-06-16 06:00
Blocked by azure china account.

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738783

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: External Dependency, IntelliJ, Internal Test, P3, transfter
