### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    [2e1e7ca6, L:/10.60.42.133:49329 - R:scadstorage.blob.core.windows.net/52.239.251.164:443] Error was received while reading the incoming data. The connection will be closed.

### ISSUE THREAD

**Issue by Edelmetall** [microsoft/azure-tools-for-java#7902] opened 2023-10-02 18:23 UTC
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS 14.0 (macOS Sonoma) 
Chip: Apple M1 Pro
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: Cannot deploy to Azure Function, with another Laptop (Windows Intel Chip) the deployment works.
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1751x1162,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   [2e1e7ca6, L:/10.60.42.133:49329 - R:<REDACTED: user-file-path>:443] Error was received while reading the incoming data. The connection will be closed.
   java.lang.LinkageError: Package versions: jackson-core=2.13.4, jackson-databind=2.13.4-2, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.42.0, Troubleshooting version conflicts: https:/<REDACTED: user-file-path>
<REDACTED: Generic Secret>
```

**Comment by Flanker32** [comment] 2023-10-07 05:44
Duplicate of #7897

**Comment by Flanker32** [comment] 2023-10-07 05:44
@Edelmetall Thanks for your report and sorry for the trouble, please track the issue in #7897

**Closed as completed by Flanker32** 2023-10-07 05:44 UTC
