### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalArgumentException: Argument for @NotNull parameter 'module' of com/intellij/openapi/module/ModuleUtilCore.getModuleDirPath must not be null

### ISSUE THREAD

**Issue by Nayan72642** [microsoft/azure-tools-for-java#8046] opened 2023-12-04 08:25 UTC
IntelliJ build version: 2023.1.1 IC-231.8770.65
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.82.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1366x720,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalArgumentException: Argument for @NotNull parameter 'module' of <REDACTED: user-file-path> must not be null
	at com.intellij.openapi.module.ModuleUtilCore.$$$reportNull$$$0(ModuleUtilCore.java)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunConfiguration.getDefaultLocalSettingsJsonPath(FunctionRunConfiguration.java:134)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.ui.FunctionRunPanel.resetFromConfig(FunctionRunPanel.java:127)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.ui.FunctionRunPanel.resetFromConfig(FunctionRunPanel.java:45)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureSettingPanel.reset(AzureSettingPanel.java:86)
	at com.m

**Comment by Flanker32** [comment] 2023-12-06 11:55
@Nayan72642 Thanks a lot for your report and sorry for the trouble. This issue should be resolved in toolkit v3.83.0, could you please upgrade to the latest version and see whether this issue could be reproduced? Feel free to re-open this issue once the problem is not fixed.

**Closed as completed** 2023-12-06 11:56 UTC
Labels: Tool: IntelliJ, Reason: fixed
