### ISSUE TITLE
Version 3.0.0 show error to sign in

### ISSUE THREAD

**Issue by flalvess** [Microsoft/azure-tools-for-java#355] opened 2017-04-22 18:04 UTC
When I try to sign in to my account, it's showed the message below.

==> run authenticateAsync ---------------
	redirectUriStr: https://msopentech.com/
	requestUriStr: https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.azure.com%2F&client-request-id=e4c07612-e45c-430a-b6d0-3d6cb7766dad&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&prompt=login&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c
	--> Browser.clearSessions()
==> run gui ---------------
	--> locationEvent.location: https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.azure.com%2F&client-request-id=e4c07612-e45c-430a-b6d0-3d6cb7766dad&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&prompt=login&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c
	--> locationEvent.location: https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxM0wxM00zTdQ1SzVO0jUxs0jSTUwzN9ZNNDA2TjM1sLRINk0uEuISECo78CTmCZfztgu2OdvLcteuYhTPKCkpKLbS188tzi9IzStJTc7QS87P1d_ByHiBkfEFI2MDE-MtJn5_x9KSDCMQkV-UWZX6iok1Jz89M28Vsyxcf2JeYnpqLtAIvcSq0qJUsCmbmNmAVG5-3g1mxgssjK9YmAz4frAwLmIFukXke1L2-inOPm1nQ_TnnWJhOMWqbxgc4l3pna6v72icmJsfVhVqkFHl6-5clJrplxZoEhFarp2eYxRaZljmX2xrYmU4gY1xFycuDwAA0&wfresh=0&id=&uaid=e4c07612e45c430ab6d03d6cb7766dad&pcexp=false&username=flavio%40labiras.cc&popupui=1
	--> locationEvent.location: https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxM0wxM00zTdQ1SzVO0jUxs0jSTUwzN9ZNNDA2TjM1sLRINk0uEuISECo78CTmCZfztgu2OdvLcteuYhTPKCkpKLbS188tzi9IzStJTc7QS87P1d_ByHiBkfEFI2MDE-MtJn5_x9KSDCMQkV-UWZX6iok1Jz89M28Vsyxcf2JeYnpqLtAIvcSq0qJUsCmbmNmAVG5-3g1mxgssjK9YmAz4frAwLmIFukXke1L2-inOPm1nQ_TnnWJhOMWqbxgc4l3pna6v72icmJsfVhVqkFHl6-5clJrplxZoEhFarp2eYxRaZljmX2xrYmU4gY1xFycuDwAA0&wfresh=0&id=&pcexp=false&username=flavio%40labiras.cc&popupui=1&contextid=F459C2D31AB1825A&bk=1492881955&uaid=e4c07612e45c430ab6d03d6cb7766dad&pid=0
	--> locationEvent.location: https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxM0wxM00zTdQ1SzVO0jUxs0jSTUwzN9ZNNDA2TjM1sLRINk0uEuISECo78CTmCZfztgu2OdvLcteuYhTPKCkpKLbS188tzi9IzStJTc7QS87P1d_ByHiBkfEFI2MDE-MtJn5_x9KSDCMQkV-UWZX6iok1Jz89M28Vsyxcf2JeYnpqLtAIvcSq0qJUsCmbmNmAVG5-3g1mxgssjK9YmAz4frAwLmIFukXke1L2-inOPm1nQ_TnnWJhOMWqbxgc4l3pna6v72icmJsfVhVqkFHl6-5clJrplxZoEhFarp2eYxRaZljmX2xrYmU4gY1xFycuDwAA0&wfresh=0&id=&pcexp=false&username=flavio%40labiras.cc&popupui=1&contextid=F459C2D31AB1825A&bk=1492881971&uaid=e4c07612e45c430ab6d03d6cb7766dad&pid=0
	--> locationEvent.location: https://login.microsoftonline.com/login.srf
	--> locationEvent.location: https://msopentech.com/?code=AQABAAIAAABnfiG-mA6NTae7CdWW7QfdjxlS0XtscZ87TFbkQkCB6-qSSPC3m7bbI2lalbpPjbH28mAkYnLcQscM3BjTVBqvM7fGcWfLT1J686cWLEAoWWpkKGrTw0alNUnCMrQWuNdOMKj31Hg12AcuZpUKysuQirbEmHqhBP38Uoq1qzeCIqXJme2poJCFaW6abr6duXnwm9HmFufdUEkiKZ8aY15FCgLOrpsL-Mzyj7L9so4TIj9Y21V2sqSyvmYzNXtnCdwmXPgcSGxL2LtAHoS2R6d8_R-9vl-sJhbEK2vwX5IW1M4_aDdccmaPkh4boZBmQBRwkHmv7-o65iq94kYgKrkB2wmh51KUxLIDYH2Rbe_JqLjjDxd1g7xsxirErHo7I5ZMrM_KfT6sMjAYQ0uIRvsqbZJ7004RovBU3DvuMdR_4Qgh0aauM8wwm712Y7NR3j0HzNRUhAQwRG5xMC9P2ct-INXNt7EABcW4eKvij8RDBLmHbquZwyfC5Ju0Y_GV1bCqtQa94IYeQ2F-aaUqRhpG3EeGJGSfLVq11o0i3AUf38NkpnyPebr8Zp_40znrIkfFgBT9nKpTQ88sihi3QeIVT1oJiqdLEXZKq89SZkPiVJ1f997hoNLNlWON-1dJPeEmijy4IfELv_ZRkVH25Z9D2TJh5EdxiWA9lb1N9ildYyAA&session_state=63aaa4e6-8918-458b-a72e-4b1b27cec3cc
Error sending IPC message: Broken pipe
doSignIn@SingInDialog: null
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:481)
	at com.microsoft.azuretools.core.ui.SignInDialog.signInAsync(SignInDialog.java:305)
	at com.microsoft.azuretools.core.ui.SignInDialog.doSignIn(SignInDialog.java:274)
	at com.microsoft.azuretools.core.ui.SignInDialog.okPressed(SignInDialog.java:237)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at com.microsoft.azuretools.core.ui.SignInDialog.go(SignInDialog.java:99)
	at com.microsoft.azuretools.core.handlers.SignInCommandHandler.doSignIn(SignInCommandHandler.java:50)
	at com.microsoft.azuretools.azureexplorer.AzureModuleImpl$SignInOutAction$1.actionPerformed(AzureModuleImpl.java:63)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:51)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.azuretools.azureexplorer.views.ServiceExplorerView$2$1.run(ServiceExplorerView.java:328)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.ExceptionInInitializerError
	at com.microsoft.azure.management.resources.implementation.ResourceManager$AuthenticatedImpl.<init>(ResourceManager.java:136)
	at com.microsoft.azure.management.resources.implementation.ResourceManager.authenticate(ResourceManager.java:67)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.<init>(Azure.java:258)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.<init>(Azure.java:251)
	at com.microsoft.azure.management.Azure.authenticate(Azure.java:143)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.authenticate(Azure.java:193)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.authTid(AccessTokenAzureManager.java:133)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:118)
	at com.microsoft.azuretools.authmanage.AdAuthManager.signIn(AdAuthManager.java:84)
	at com.microsoft.azuretools.core.ui.SignInDialog$5.run(SignInDialog.java:289)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.AzureServiceClient.<clinit>(AzureServiceClient.java:74)
	... 11 more
Canceled by the user.

My system is:
Ubuntu 16.04.2 LTS
Eclipse Neon.3
Azure Plugin to Eclipse version 3.0.0

**Comment by vladimir-shcherbakov** [comment] 2017-04-24 17:48
The issue is unique to Ubuntu and caused by Azure SDK for Java.  Will be fixed as soon as the SDK is fixed.

**Comment by flalvess** [comment] 2017-05-02 12:05
How do I upgrade this version in Eclipse?
I can see the new update on http://marketplace.eclipse.org/content/azure-toolkit-eclipse, but in the Eclipse Marketplace it's not possible to update plugin. It's show ˜No updates are available˜.

**Comment by martinsawicki** [comment] 2017-05-02 18:12
Because of how significant the changes are between v2.x and 3.x, using the Eclipse update functionality to go from v2 to v3 would not work properly. Instead pls uninstall all the v2.x components manually and install v3.x after that.
Please see https://github.com/Microsoft/azure-tools-for-java/issues/170 for important details.

**Comment by flalvess** [comment] 2017-05-02 23:15
My system is already version 3.0.0, but the error I had reported in this thread had a new version. This version is 3.0.1 on 2017-04-27. Version 3.0.0 was released on 2017-04-19.

My Installed plugins in Eclipse is in version 3.0.0.201704192131. What I want is to upgrade this plugins to newest version, released on 2017-04-27, that is the update date in eclipse marketplace site (https://marketplace.eclipse.org/content/azure-toolkit-eclipse#comment-form).

**Comment by martinsawicki** [comment] 2017-05-02 23:41
Ah, I think I understand what you're trying to do better now.
We have not yet released v3.0.1. v3.0.0 is the latest on Marketplace.

However, it'd be great if you could check if our release candidate for v3.0.1 solves the issue you originally reported. Since it is not officially released, you can get the RC from the "unofficial" staging update site at: https://azuredownloads.blob.core.windows.net/eclipse/v3.0.1/. See if that works?

**Comment by flalvess** [comment] 2017-05-02 23:59
Thank you very much!
This version works perfectly.
Thanks for you support.

**Comment by martinsawicki** [comment] 2017-05-03 00:20
glad to hear. Hoping to release officially tomorrow, once all the tests are complete.

**Comment by martinsawicki** [comment] 2017-05-03 21:38
the v3.0.1 update has now been made available at the usual public update site, so closing this issue.

**Closed by martinsawicki** 2017-05-03 21:38 UTC
Labels: IntelliJ
