### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by vcitiriga** [microsoft/azure-tools-for-java#7426] opened 2023-03-30 07:55 UTC
IntelliJ build version: 2022.2.3 IU-222.4345.14
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.74.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x672,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.action.DeployWebAppAction.lambda$runConfiguration$2(DeployWebAppAction.java:70)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:102)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:382)
```

**Comment by wangmingliang-ms** [comment] 2023-04-03 06:22
Duplicate of #7020

**Closed as completed by wangmingliang-ms** 2023-04-03 06:22 UTC
