### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: c6a846d6-1593-424e-abcb-abbb12a5385a] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed. com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by phongcuncon** [microsoft/azure-tools-for-java#7831] opened 2023-09-05 11:16 UTC
IntelliJ build version: 2023.1.5 IU-231.9392.1
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.80.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x900,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: c6a846d6-1593-424e-abcb-abbb12a5385a] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.mi

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:13
Duplicate of #7708

**Closed as completed by wangmingliang-ms** 2023-09-19 02:13 UTC
