### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=ce-kafka, containerState=DISPOSE_COMPLETED, componentStore=/home/cyrus/work/ce-kafka-images) (disposed)

### ISSUE THREAD

**Issue by cyrusv** [microsoft/azure-tools-for-java#5307] opened 2021-05-25 16:42 UTC
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Linux
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1391x1376,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=ce-kafka, containerState=DISPOSE_COMPLETED, componentStore=/home/cyrus/work/ce-kafka-images) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.trackProjectDependencies(WorkspaceTaggingActivity.java:40)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$0(WorkspaceTaggingActivity.java:35)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$1

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:17
Duplicate of #5439, after refactoring

**Closed by wangmingliang-ms** 2021-07-01 03:17 UTC
