### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group Idea Thread Group failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 2 queries 

### ISSUE THREAD

**Issue by guitarsheng** [microsoft/azure-tools-for-java#5469] opened 2021-07-04 13:44 UTC
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x512,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group Idea Thread Group failed with an uncaught exception, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 2 queries 
Caused by: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 2 queries 
		at com.microsoft.azure.toolkit.lib.auth.AzureAccount.getSubscription_aroundBody2(AzureAccount.java:280)
		at com.microsoft.azure.toolkit.lib.auth.AzureAccount$AjcClosure3.run(AzureAccount.java:1)

**Comment by wangmingliang-ms** [comment] 2021-07-06 05:29
Duplicate of #5451

**Closed by wangmingliang-ms** 2021-07-06 05:29 UTC
