### ISSUE TITLE
[Enhancement]Support configure app settings when creating app service

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2819] opened 2019-03-04 09:51 UTC
### Environment:
OS: Windows/Mac/Linux
IDE: IU18.3.5 and IC 18.3.2
JDK: 8

### Repro steps:

1. Right-click project ->Azure -> deploy to Azure
2. Select create new

### Actual result:
Don't support configure app settings 
![image](https://user-images.githubusercontent.com/28860891/53724572-1b4bf700-3ea5-11e9-80dc-211e512cb27e.png)

### Expect result: 
I think our plugin should support configure app settings when creating app service in  IntelliJ, like eclipse:
![image](https://user-images.githubusercontent.com/28860891/53725013-18053b00-3ea6-11e9-99f4-3e4c3668858b.png)

**Comment by ZhengJun003** [comment] 2020-06-15 10:02
Can reproduce this issue in azure toolkits 3.38.0

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738789

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: IntelliJ, Internal Test, app-service, feature-request, transfter
