### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by tamas2792** [microsoft/azure-tools-for-java#5546] opened 2021-07-16 12:37 UTC
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x512,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=Getting_Started, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\itamas\OneDrive - ENDAVA\Desktop\HibernateProjects\Security-Amigos\Getting_Started) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Getting_Started, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\itamas\OneDrive - ENDAVA\Desktop\HibernateProjects\Security-Amigos\Getting_Started) (disposed)
	at com.microsoft.azure.toolkit.intellij.azur

**Comment by wangmingliang-ms** [comment] 2021-07-19 15:10
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-19 15:10 UTC
