### ISSUE TITLE
[IntelliJ] Cancel Sign in will throw exception

### ISSUE THREAD

**Issue by jianghaolu** [Microsoft/azure-tools-for-java#212] opened 2017-03-17 18:10 UTC
<img width="1280" alt="screen shot 2017-03-17 at 11 10 17 am" src="https://cloud.githubusercontent.com/assets/2320445/24056819/5e7348f4-0b02-11e7-8271-597734ef1895.png">

**Comment by vladimir-shcherbakov** [comment] 2017-03-24 17:16
For some reason, after the browser is opened the plugin can only track one event - redirection to the redirect URL. All other events (like window closing) are considered as authentication error.
 
The one good solution for this and other browser-interaction-authorization issues - is to switch to device login authorization model to not tinker with all the variety of browser control implementations.

**Comment by martinsawicki** [comment] 2017-04-06 22:50
We need an OK-only error message that says "Authentication failed or was interrupted." No exception in IJ,

**Comment by bsaby** [comment] 2017-04-10 07:22
Test failed, using artifacts/WindowsAzurePlugin4EJ.244.04-09-2017.zip.

When cancel Sign in, there will be not an error message that says "Authentication failed or was interrupted",  just a expection.

**Comment by vladimir-shcherbakov** [comment] 2017-04-10 07:53
![image](https://cloud.githubusercontent.com/assets/6579928/24850670/d1f7475e-1d85-11e7-8af4-32474d0c4191.png)

The main idea of the fix - do not show the error as a plugin error with blinking exclamation mark on the right bottom.

Sign in can be canceled whether by clicking the "Back" button (1) or by clicking the cross (2).

1) clicking the Back button can be caught - that's why the Sign in dialog gets closed - no error shown.
2) clicking the cross button - there may be several reasons to click the button: from canceling like in 1 to failing auth. In this case the Error dialog gets shown.

How exactly did you cancel the Sign in?

**Comment by bsaby** [comment] 2017-04-10 08:20
Test passed, using azure-toolkit-for-intellij.2017.**240**.04-09-2017.zip.
The reproduction is because the build used is not the latest build.

1. clicking the Back button, it will back to the Azure Sign In dialog. 
2. clicking the cross button - the error dialog box appears as shown below.
But the font should be the  standard UI font .

![image](https://cloud.githubusercontent.com/assets/22470312/24852029/8024f902-1e08-11e7-95a3-6a38d54a0945.png)

**Comment by vladimir-shcherbakov** [comment] 2017-04-11 00:26
font fixed.

**Comment by bsaby** [comment] 2017-04-11 04:16
Test passed, using azure-toolkit-for-intellij.2017.**252**.04-10-2017.zip.
![image](https://cloud.githubusercontent.com/assets/22470312/24892608/7ad9d276-1eb0-11e7-8394-b84a8e40b187.png)

**Closed by bsaby** 2017-04-11 04:16 UTC
Labels: bug-bash, fixed, IntelliJ, wontfix
