### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped java.lang.InterruptedException

### ISSUE THREAD

**Issue by floringrigoriu** [microsoft/azure-tools-for-java#7954] opened 2023-10-24 19:23 UTC
IntelliJ build version: 2023.1.5 IC-231.9392.1
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.81.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1537x913,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@411975aa,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=java.lang.InterruptedException
	at <REDACTED: user-file-path>(ProcessImpl.java:568)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:258)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:157)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:93)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
```

**Comment by wangmingliang-ms** [comment] 2023-11-03 07:17
Duplicate of #7907

**Closed as completed by wangmingliang-ms** 2023-11-03 07:17 UTC
