### ISSUE TITLE
Got Java exception while trying to delete a WebApp

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#66] opened 2017-02-17 18:36 UTC
```
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.AbstractCollection.remove(AbstractCollection.java:293)
	at com.microsoft.azuretools.utils.AzureModelController.removeWebAppFromExistingResourceGroup(AzureModelController.java:260)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappNode$DeleteWebAppAction.azureNodeAction(WebappNode.java:128)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureNodeActionListener.actionPerformed(AzureNodeActionListener.java:54)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListenerAsync$1.run(NodeActionListenerAsync.java:56)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
I just created that web app and deployed from IntelliJ. The subscription used was a MSDN one

**Comment by martinsawicki** [comment] 2017-03-02 00:29
looks like duplicate of an earlier issue

**Comment by vladimir-shcherbakov** [comment] 2017-03-07 08:06
duplicate: Deleting webapp from Azure explorer throws error #70

**Closed by vladimir-shcherbakov** 2017-03-07 08:06 UTC
Labels: bug-bash, duplicate, IntelliJ
