### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Index is not created for `Stubs`

### ISSUE THREAD

**Issue by lenmpeng** [microsoft/azure-tools-for-java#6165] opened 2021-12-06 03:42 UTC
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Index is not created for `Stubs`
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1249)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findJavaMainClass(SparkContextUtils.kt:94)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:83)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.lambda$setupConfigurationFromContext$1(SparkBatchJobLocalRunConfigurationProducer.java:56)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.setupConfigurationFromContext(SparkBatchJobLocalRunConfigurationProducer.java:55)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.setupConfigurationFromContext(SparkBatchJobLocalRunConfigurationProducer.java:30)

**Comment by fengshuaihu** [comment] 2022-12-29 05:23
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7158

**Closed as completed by fengshuaihu** 2022-12-29 05:23 UTC
Labels: Module: HDInsight
