### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by djebos** [microsoft/azure-tools-for-java#6164] opened 2021-12-05 15:05 UTC
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Linux
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,37,824x492,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findMainMethod(SparkContextUtils.kt:89)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.update(SparkRunConfigurationAction.kt:67)
```

**Comment by fengshuaihu** [comment] 2022-12-29 03:38
Duplicate of  [#5768](https://github.com/microsoft/azure-tools-for-java/issues/5768)

**Closed as completed by fengshuaihu** 2022-12-29 03:38 UTC
Labels: Module: HDInsight
