### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null

### ISSUE THREAD

**Issue by petrov94** [microsoft/azure-tools-for-java#7073] opened 2022-11-05 21:58 UTC
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.63.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1033,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@32b1117a,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl:STRING_LITERAL
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.a

**Comment by fengshuaihu** [comment] 2022-11-16 03:31
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/5762

**Closed as completed** 2022-11-16 07:26 UTC
Labels: Type: Bug, Module: HDInsight
