### ISSUE TITLE
Key Vault creation fails during Docker host creation

### ISSUE THREAD

**Issue by aovechki** [microsoft/azure-tools-for-java#335] opened 2017-04-12 19:04 UTC
win10, x64, Eclipse.Mars

When trying to create a new docker host with all default settings (create a new Key Vault is specified) from the Azure Explorer menu, a VM is created and everything seems ok, but there's an error in the error log related to creation of the Key Vault (below). Afterwards, this docker host cannot be used for publishing.

null
com.microsoft.azuretools.azureexplorer
Error
Wed Apr 12 11:57:22 PDT 2017
WARN: Unexpected error creating Azure Key Vault web2628579226286kv - null

java.lang.NullPointerException
	at com.microsoft.azure.management.graphrbac.implementation.UserImpl.<init>(UserImpl.java:35)
	at com.microsoft.azure.management.graphrbac.implementation.UsersImpl$2.call(UsersImpl.java:81)
	at com.microsoft.azure.management.graphrbac.implementation.UsersImpl$2.call(UsersImpl.java:78)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:517)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:471)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 33 more

**Comment by aovechki** [comment] 2017-04-12 19:14
this is using an MSDN subs, in case it matters

**Comment by selvasingh** [comment] 2017-04-14 16:26
Limit investigation to no more than a few minutes for v3.0

**Comment by milismsft** [comment] 2017-04-14 19:13
This is 'by design" for now; the user's log in address does not match the expected Azure Graph's user principal name (there's no API in SDK to retrieve that). The user work around is to create and use a service principal log in.

**Comment by milismsft** [comment] 2017-04-14 19:15
Temporary work is to catch the Azure Graph's CloudException and pop a message that will tell the user to create/use a service principal log in instead.

**Comment by Flanker32** [comment] 2020-07-02 08:23
We have deprecated the support for docker host, close this issue.

**Closed by Flanker32** 2020-07-02 08:23 UTC
Labels: Eclipse, P3, deprecated, docker-host, enhancement
