### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by KamalNayak07** [microsoft/azure-tools-for-java#4313] opened 2020-04-16 17:28 UTC
IntelliJ build version: 2019.1.1 IU-191.6707.61
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.28.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,29,1537x802,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.microsoft.azure.hdinsight.sdk.storage.adlsgen2.ADLSGen2FSOperation.appendData(ADLSGen2FSOperation.java:113)
	at com.microsoft.azure.hdinsight.sdk.storage.adlsgen2.ADLSGen2FSOperation.uploadData(ADLSGen2FSOperation.java:94)
	at com.microsoft.azure.hdinsight.spark.common.ADLSGen2Deploy.lambda$deploy$3(ADLSGen2Deploy.java:87)
	at com.microsoft.azure.hdinsight.spark.common.ADLSGen2Deploy$$Lambda$7128/1304489981.call(Unknown Source)
```

**Comment by andxu** [comment] 2020-04-24 02:10
@KamalNayak07 "Caused by: java.lang.OutOfMemoryError: Java heap space" seems your IDEA is run out of memory, see details [here](https://www.jetbrains.com/help/idea/increasing-memory-heap.html) to increase memory heap.

**Comment by vscjavaci** [comment] 2020-06-02 08:38
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thr... (#3551)

**Comment by vscjavaci** [comment] 2020-06-03 06:45
Close this issue due to duplicate error: java.lang.OutOfMemoryError: Java heap space

**Closed by vscjavaci** 2020-06-03 06:45 UTC
Labels: External:IntelliJ, duplicate, stacktrace
