### ISSUE TITLE
Can not connect to a Azure Data Lake HDInsight Cluster

### ISSUE THREAD

**Issue by nielsenbe** [Microsoft/azure-tools-for-java#283] opened 2017-04-04 03:18 UTC
I am able to log into my account without error in the Azure Explorer window.  It detects my HDI cluster, but not the storage account.  The cluster was built with the Azure Data Lake option for backing store.  It appears to be looking for a traditional Storage account, but there is no name / key equivalent for ADL.  ADL uses a certificate based Azure AD Service Principal.

Windows 10
Scala IDE 4.5
Azure Plugin for Eclipse with Java 2.9.5.20170125103

Cluster
Spark 2.0 HDI 3.5

**Comment by martinsawicki** [comment] 2017-04-06 22:20
@voidfunction any ideas?  (note we no longer has support for Classic Storage accounts, not sure if that is what the issue is here though)

**Comment by nielsenbe** [comment] 2017-04-07 01:33
I spun up a new cluster (same settings), but this time I connected the cluster to blob storage.  The plugin picked it right up.  So it appears to be a Data Lake problem.  (I have never used classic storage for HDInsight).

**Comment by voidfunction** [comment] 2017-04-07 04:13
@nielsenbe ADLS is not supported in our released bits. It will be enable in our coming release.

**Comment by voidfunction** [comment] 2017-05-10 06:43
@nielsenbe please get the latest bits for adls support. Thank you. Close the issue.

**Closed by voidfunction** 2017-05-10 06:43 UTC
Labels: Eclipse, HDInsight
