### ISSUE TITLE
[Eclipse] No messages of key vault creation failure

### ISSUE THREAD

**Issue by xscript** [Microsoft/azure-tools-for-java#319] opened 2017-04-12 18:03 UTC
- How to repro:
  - Create a docker host
  - After creation, show details.
  - Go to Azure Portal, there is no key vault instance created.
- OS: Windows 10
- IDE: Eclipse Neon.3
- Plugin Version: WindowsAzurePlugin4EJ.271.04-11-2017.zip

![image](https://cloud.githubusercontent.com/assets/2300784/24972180/0e18421a-1fed-11e7-96c1-8ded35b8e8d2.png)

**Comment by selvasingh** [comment] 2017-04-14 16:31
must fix

**Comment by milismsft** [comment] 2017-04-14 21:04
No repro; this could be related to the issue we have where for some interactive login users we failed to create the associated Azure Key Vault. (see https://github.com/Microsoft/azure-tools-for-java/issues/335)

**Comment by bsaby** [comment] 2017-04-19 09:30
Repro in both Eclipse and IntelliJ .
Builds used:
artifacts/azure-toolkit-for-intellij.2017.333.04-18-2017.zip
artifacts/WindowsAzurePlugin4EJ.338.04-18-2017.zip

After publish Docker host successfully, the details display normally, but if I restart IJ/Eclipse or view host’s details in another software which not the one I used to publish Docker Host before, Docker Hosts will not display the message.
Shown as below pictures:
![image](https://cloud.githubusercontent.com/assets/22470312/25173081/798fa000-2525-11e7-894d-106974b54b9d.png)

![image](https://cloud.githubusercontent.com/assets/22470312/25172781/97fe706c-2524-11e7-8c67-c1b4034d7b9e.png)

**Comment by milismsft** [comment] 2017-04-19 15:34
The "-unknown-" you see is "by design"; if the user does not save the log in credentials in an Azure Key Vault, there's not much we can do to retrieve that data outside the session where he created the Docker host. We will only get it if he goes through the Publishing and choses that host; at that time we will prompt him to introduce the log in credentials which will be saved in memory for the duration of the session (closing IntelliJ or Eclipse will clear that memory).

**Comment by bsaby** [comment] 2017-04-20 01:47
By design and closed.

**Closed by bsaby** 2017-04-20 01:47 UTC
Labels: bug-bash, Eclipse, fixed
