### ISSUE TITLE
the lastest version of IntelliJ is incompatible with the Azure plugin

### ISSUE THREAD

**Issue by reyang** [Microsoft/azure-tools-for-java#256] opened 2017-03-17 20:12 UTC
I'm using the 2017.1 version and got the following error while installing the plugin:

![image](https://cloud.githubusercontent.com/assets/17327289/24061086/41b1c892-0b13-11e7-96b4-154a50f68e49.png)

**Comment by martinsawicki** [comment] 2017-03-20 19:43
apparently this is a in-released preview version. Need to see why and does JetBrains know existing plugins are broken.

**Comment by lenala** [comment] 2017-03-21 18:14
This is caused by IntelliJ API changes in LibraryPresentationProvider:
 ` public Icon getIcon(@Nullable LibraryProperties properties) { `
was changed to
`  public Icon getIcon(@Nullable P properties) {  `
This method is overriden in SparkLibraryType. If made compatible with IntelliJ 2017.1, it becomes incompatible with 2016.x version.

**Comment by lenala** [comment] 2017-03-21 19:17
This is fixed by overriding deprecated getIcon() method. After IntelliJ 2017.1 is released, can be updated to override use `public Icon getIcon(@Nullable SparkLibraryProperties properties)`.

**Comment by lenala** [comment] 2017-03-21 19:20
Please verify if the build can be installed both to IntelliJ 2017.1 and 2016.x.

**Comment by reyang** [comment] 2017-03-21 19:37
Great, let me try it. Thanks for the fix! 👍

**Comment by bsaby** [comment] 2017-03-22 07:38
Test build uesd: artifacts/azure-toolkit-for-intellij.116.zip
Build can be installed to IntelliJ2016.x but can not be installed to IntelliJ 2017.1 .

**Comment by reyang** [comment] 2017-03-22 17:40
Tried with build 115 and got "Plugin 'Azure Toolkit for IntelliJ' is incompatible with this installation" error.

![capture](https://cloud.githubusercontent.com/assets/17327289/24212216/cd204896-0eeb-11e7-991c-a006321c0cfe.PNG)

**Comment by bsaby** [comment] 2017-04-01 07:06
Test passed. 
Azure Toolkit for IntelliJ v3.0 for 2016 is compatible with IJ2016.x
Azure Toolkit for IntelliJ v3.0 for 2017 is compatible with IJ2017.1.
Using **azure-toolkit-for-intellij.2016.2.03-31-2017.zip** and **azure-toolkit-for-intellij.2017.191.03-31-2017.zip.**

**Closed by bsaby** 2017-04-01 07:06 UTC
Labels: bug-bash, IntelliJ
