### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot create extension (class=com.microsoft.azure.toolkit.intellij.facet.projectexplorer.AzureFacetTreeStructureProvider) [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by RokolyA94** [microsoft/azure-tools-for-java#7679] opened 2023-07-11 12:34 UTC
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Linux
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1920x1136,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot create extension (class=com.microsoft.azure.toolkit.intellij.facet.projectexplorer.AzureFacetTreeStructureProvider) [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1096)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.microsoft.azure.toolkit.intellij.facet.projectexplorer.AzureFacetTreeStructureProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, descriptorPath=plugin.xml, path=~<REDACTED: user-file-path>, version=3.78.0-2023.1, package=null,

**Comment by Flanker32** [comment] 2023-07-31 05:28
@RokolyA94 Thanks a lot for your report and sorry for the late response, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7718

Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7718

**Closed as completed by Flanker32** 2023-07-31 05:28 UTC
