### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240108101519)

### ISSUE THREAD

**Issue by ronisonmatos** [microsoft/azure-tools-for-java#8091] opened 2024-01-08 13:28 UTC
IntelliJ build version: 2023.3.2 IU-233.13135.103
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240108101519)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:575)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:287)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.getResourceGroup(AbstractAzResource.java:310)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.exists(AbstractAzResource.java:101)
	at com.microsoft.a

**Comment by Flanker32** [comment] 2024-01-29 08:06
@ronisonmatos Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8107. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 08:06
Duplicate of #8107

**Closed as completed by Flanker32** 2024-01-29 08:06 UTC
