### ISSUE TITLE
Click the "help" button in add library window, nothing shows up

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2378] opened 2018-11-20 11:04 UTC
It is not a regression issue, it also repro in previous version.

Build: 864

Repro steps:

1. Right-click a web project choose Azure-Libraries Configuration
2. Click add
2. Click the "help" button in add library window

Result:

There is nothing shows up. I think it should open a page to display some info.
![image](https://user-images.githubusercontent.com/28860891/48769637-1c428980-ecf7-11e8-8a9d-432af8391efe.png)

**Comment by ZhengJun003** [comment] 2020-06-16 06:32
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738774

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738815

**Comment by vscjavaci** [comment] 2020-07-02 01:10
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:10 UTC
Labels: IntelliJ, Internal Test, P3, add-library, bug, transfter
