### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by rtellams** [microsoft/azure-tools-for-java#7869] opened 2023-09-20 17:54 UTC
IntelliJ build version: 2023.1.2 IU-231.9011.34
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.80.2-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:47)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:259)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.doGetById(AbstractAzService.java:110)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.getById(AbstractAzService.java:102)
	at com.microsoft.azure.toolkit.intellij.sprin

**Comment by Flanker32** [comment] 2023-10-07 06:19
@rtellams Thank you for reporting this issue and we apologize for the delay in responding to you. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?

**Comment by rtellams** [comment] 2023-10-07 17:19
Looks good now.

**Comment by Flanker32** [comment] 2023-10-08 06:01
@rtellams Got it, thanks a lot for your help! I’ll close the issue for now, but please feel free to open it if you meet this issue again. Thanks again for your support!

**Closed as completed by Flanker32** 2023-10-08 06:01 UTC
Labels: Tool: IntelliJ, Module: Azure Spring Apps
