### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)

### ISSUE THREAD

**Issue by rmosh** [microsoft/azure-tools-for-java#8072] opened 2023-12-19 20:21 UTC
IntelliJ build version: 2023.3 IC-233.11799.241
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1718x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler$1.processWillTerminate(RunProcessHandler.java:88)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyComplete(RunProcessHandler.java:110)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$1(SpringCloudDeploymentConfigurationState.java:91

**Comment by Flanker32** [comment] 2024-01-29 07:55
@rmosh Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8100. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:55
Duplicate of #8100

**Closed as completed by Flanker32** 2024-01-29 07:55 UTC
