### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: User data is not supported; editorClass='com.microsoft.azure.toolkit.intellij.redis.explorer.RedisCacheExplorer'; key='editor.notification.provider' [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by Ryaryu** [microsoft/azure-tools-for-java#6676] opened 2022-06-06 17:10 UTC
IntelliJ build version: 2022.1.2 IU-221.5787.30
OS: Linux
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.64.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,24,1920x1055,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: User data is not supported; editorClass='com.microsoft.azure.toolkit.intellij.redis.explorer.RedisCacheExplorer'; key='editor.notification.provider' [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
```

**Comment by wangmingliang-ms** [comment] 2022-06-07 07:06
this issue has been fixed in the latest release `v3.65.*`
Duplicate of #6550

**Closed as completed by wangmingliang-ms** 2022-06-07 07:06 UTC
