### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   [Correlation ID: 826e5b93-2dc0-47f9-831f-010b3b0ef70d] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.

### ISSUE THREAD

**Issue by kaiquesimao** [microsoft/azure-tools-for-java#7767] opened 2023-08-07 18:20 UTC
IntelliJ build version: 2023.2 IU-232.8660.185
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x824,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  [Correlation ID: 826e5b93-2dc0-47f9-831f-010b3b0ef70d] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.
  com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:15
Duplicate of #7708

**Closed as completed by wangmingliang-ms** 2023-09-19 02:15 UTC
