### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by jbonfante** [microsoft/azure-tools-for-java#7458] opened 2023-04-11 16:23 UTC
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x922,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@6cbdd28e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2023-04-15 14:48
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-04-15 14:48 UTC
