### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files

### ISSUE THREAD

**Issue by ielkhalloufi** [microsoft/azure-tools-for-java#7247] opened 2023-01-25 14:10 UTC
IntelliJ build version: 2022.2.3 IU-222.4345.14
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.72.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:42)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:35)
```

**Comment by Flanker32** [comment] 2023-01-29 09:40
@ielkhalloufi Thanks for your report and sorry for the trouble. Could you please help share a bit more info about this issue, could this issue be stable reproduced and is there any way to reproduce this issue?

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:45
Duplicate of #7374

**Closed as completed by wangmingliang-ms** 2023-03-20 01:45 UTC
Labels: Module: Bicep
