### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})

### ISSUE THREAD

**Issue by KubilayKarayilan** [microsoft/azure-tools-for-java#7629] opened 2023-06-15 09:25 UTC
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1460x970,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@67d51a6f,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})
Caused by: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.common.component.SenderReceiverPanel.execute(SenderReceiverPanel.java:119)
Ca

**Comment by Flanker32** [comment] 2023-06-28 02:59
Duplicate of #7643

**Closed as completed by Flanker32** 2023-06-28 02:59 UTC
