### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by AndreyOsadchuk** [microsoft/azure-tools-for-java#6978] opened 2022-09-28 08:50 UTC
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.68.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x986,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@504be84f,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2022-09-29 01:56
Hi, @AndreyOsadchuk, thanks for reporting. could you please help share us how to reproduce this error? This error has been reported several times, but currently we could not reproduce this issue.

**Comment by Flanker32** [comment] 2022-09-29 01:57
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6844

**Closed as completed by Flanker32** 2022-09-29 01:57 UTC
Labels: Type: Bug, Reason: not reproduceable, need more info
