### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=nbme-dam-10-10-github, containerState=COMPONENT_CREATED, componentStore=C:\Java\Projects\Nuxeo\nuxeo-nbme-dam-10-github\nbme-dam-10-10-github))

### ISSUE THREAD

**Issue by apodoksik** [microsoft/azure-tools-for-java#5891] opened 2021-09-30 20:24 UTC
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.57.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=nbme-dam-10-10-github, containerState=COMPONENT_CREATED, componentStore=C:\Java\Projects\Nuxeo\nuxeo-nbme-dam-10-github\nbme-dam-10-10-github))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfi

**Comment by wangmingliang-ms** [comment] 2021-10-03 14:30
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-03 14:30 UTC
