### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null

### ISSUE THREAD

**Issue by Vhodnoylogin** [microsoft/azure-tools-for-java#7410] opened 2023-03-23 12:14 UTC
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.74.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null
	at org.wso2.lsp4intellij.actions.LSPGotoDeclarationAction.actionPerformed(LSPGotoDeclarationAction.java:31)
```

**Comment by wangmingliang-ms** [comment] 2023-04-03 06:25
Duplicate of #7387

**Closed as completed by wangmingliang-ms** 2023-04-03 06:25 UTC
