### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Operator called default onErrorDropped

### ISSUE THREAD

**Issue by AugustoNapoleao1996** [microsoft/azure-tools-for-java#8006] opened 2023-11-14 14:01 UTC
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1921x1033,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Operator called default onErrorDropped
   reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
Caused by: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
```

**Comment by Flanker32** [comment] 2023-12-06 12:10
@AugustoNapoleao1996 Thanks for your report and sorry for the late response. Please track the issue in #7962

**Comment by Flanker32** [comment] 2023-12-06 12:11
Duplicate of #7962

**Closed as completed by Flanker32** 2023-12-06 12:11 UTC
