### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: 3 : child= 'FilePartNode: 'WSDL'; children: 2; fs=LocalFileSystem; myFileOrUrl=file://C:/workspace/ptb/digi-seal-service-project/digi-seal-service/src/main/resources/wsdl; class com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl'; child.nameEqualTo(nameId)=false; child.getClass()=class com.intellij.openapi.vfs.impl.FilePartNode; child.nameId=6059285; child.getName()='WSDL'; nameId=6076105; name='wsdl'; compare(child) = 0; UrlPart.nameEquals: true; name.equals(child.getName())=false; file=file://C:/workspace/ptb/digi-seal-service-project/digi-seal-service/src/main/resources/wsdl; this.isCaseSensitive()=false

### ISSUE THREAD

**Issue by Duke2k** [microsoft/azure-tools-for-java#8154] opened 2024-02-09 07:45 UTC
IntelliJ build version: 2023.3.3 IC-233.14015.106
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,2558x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: 3 : child= 'FilePartNode: 'WSDL'; children: 2; fs=LocalFile

**Comment by wangmingliang-ms** [comment] 2024-03-01 06:30
Duplicate of #7463

**Closed as completed by wangmingliang-ms** 2024-03-01 06:30 UTC
