### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   [Correlation ID: 82498fa5-c1b2-410a-ac48-d035f39d4168] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.

### ISSUE THREAD

**Issue by dataaccess-recovery** [microsoft/azure-tools-for-java#7826] opened 2023-09-02 06:27 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x673,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  [Correlation ID: 82498fa5-c1b2-410a-ac48-d035f39d4168] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.
  com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:15
Duplicate of #7708

**Closed as completed by wangmingliang-ms** 2023-09-19 02:15 UTC
