### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.runOnPooledThread(java.lang.Runnable)" because the return value of "com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.getInstance()" is null

### ISSUE THREAD

**Issue by oscaralvarado29** [microsoft/azure-tools-for-java#6954] opened 2022-09-23 12:01 UTC
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.68.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1350x679,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.runOnPooledThread(java.lang.Runnable)" because the return value of "com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.getInstance()" is null
	at com.microsoft.azure.toolkit.intellij.cosmos.dbtools.DbToolsWorkaround.preload(DbToolsWorkaround.java:41)
```

**Comment by wangmingliang-ms** [comment] 2022-09-26 02:34
Duplicate of #6939

**Closed as completed by wangmingliang-ms** 2022-09-26 02:34 UTC
