### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=visionplanner.bms, containerState=COMPONENT_CREATED, componentStore=/opt/repo/bb/visionplanner.bms))

### ISSUE THREAD

**Issue by cbos** [microsoft/azure-tools-for-java#5906] opened 2021-10-06 07:41 UTC
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Linux
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.57.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1916x1006,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=visionplanner.bms, containerState=COMPONENT_CREATED, componentStore=/opt/repo/bb/visionplanner.bms))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfiguration.java:103)
```

**Comment by wangmingliang-ms** [comment] 2021-10-07 01:19
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-07 01:19 UTC
