### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception: execute Azure Cli command 'az account get-access-token' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by pcsmiana** [microsoft/azure-tools-for-java#8056] opened 2023-12-07 19:50 UTC
IntelliJ build version: 2023.3 IU-233.11799.241
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAc

**Comment by Flanker32** [comment] 2023-12-08 02:00
@pcsmiana Thanks for your report and sorry for the trouble. Please track the issue in #8054

**Comment by Flanker32** [comment] 2023-12-08 02:00
Duplicate of #8054

**Closed as completed by Flanker32** 2023-12-08 02:00 UTC
