### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun java.lang.NoSuchMethodError: 'int com.intellij.psi.PsiJavaCodeReferenceElement.getTypeParameterCount()'

### ISSUE THREAD

**Issue by sajid-basheer** [microsoft/azure-tools-for-java#6669] opened 2022-06-02 15:38 UTC
IntelliJ build version: 2022.1.1 IC-221.5591.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.65.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x965,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@68ab3f8d,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=java.lang.NoSuchMethodError: 'int com.intellij.psi.PsiJavaCodeReferenceElement.getTypeParameterCount()'
	at com.intellij.psi.impl.source.PsiClassReferenceType.getParameterCount(PsiClassReferenceType.java:212)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.isSparkContext(SparkContextUtils.kt:55)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.update(SparkRunConfigurationAction.kt:70)
```

**Comment by fengshuaihu** [comment] 2023-01-12 05:08
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6616

**Closed as completed by fengshuaihu** 2023-01-12 05:08 UTC
Labels: Module: HDInsight
