### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot create extension (class=com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor) [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by sudhansu-badajena** [microsoft/azure-tools-for-java#8069] opened 2023-12-18 14:49 UTC
IntelliJ build version: 2023.3 IU-233.11799.241
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x824,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot create extension (class=com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor) [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1471)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.<init>(IntellijAzureActionManager.java:70)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$Provider.getActionManager(IntellijAzureActionManager.java:386)
	at com.microsoft.azure.toolkit.lib.common.action.AzureActionManager$Holder.loadActionManager(AzureActionManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.action

**Comment by Flanker32** [comment] 2024-01-29 07:04
Thank you for reporting this issue and we are sorry for the inconvenience. Please track this issue in https://github.com/microsoft/azure-tools-for-java/issues/8117.
It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:04
Duplicate of #8117

**Closed as completed by Flanker32** 2024-01-29 07:04 UTC
