### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null

### ISSUE THREAD

**Issue by jasimahmedkhan** [microsoft/azure-tools-for-java#6618] opened 2022-05-09 11:31 UTC
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Linux
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1600x863,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@632bf484,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl:STRING_LITERAL
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:06
Duplicate of #6338

**Closed as completed by wangmingliang-ms** 2022-05-13 02:06 UTC
Labels: Module: HDInsight
