### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Magic-Cards, containerState=DISPOSE_COMPLETED, componentStore=D:\Provas Tecnicas\Zappts\Magic-Cards) (disposed)

### ISSUE THREAD

**Issue by misael-mateus** [microsoft/azure-tools-for-java#6901] opened 2022-08-30 09:51 UTC
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@3cfd1247,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Magic-Cards, containerState=DISPOSE_COMPLETED, componentStore=D:\Provas Tecnicas\Zappts\Magic-Cards) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:189)
	at com.microsoft.azure.toolkit.intellij.common.survey.SurveyPopUpDialog.<init>(SurveyPopUpDialog.java:65)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.showSurveyPopup(CustomerSurveyManager.java:77)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.lambda$takeSurvey$0(CustomerSurveyManager.java:72)
`

**Comment by wangmingliang-ms** [comment] 2022-09-20 15:04
duplicate of #6790

**Closed as completed by wangmingliang-ms** 2022-09-20 15:04 UTC
Labels: Type: Bug, Reason: fixed, State: Resolved
