### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: 683 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.azure.toolkit.intellij.common.auth.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by proyaz** [microsoft/azure-tools-for-java#7541] opened 2023-05-12 14:29 UTC
IntelliJ build version: 2023.1.1 IC-231.8770.65
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: 683 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.azure.toolkit.intellij.common.auth.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.loadIcon(IntelliJAzureIcons.java:120)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.lambda$doGetIcon$2(IntelliJAzureIcons.java:98)
		at com.microsoft.azure.toolkit.intellij.

**Comment by wangmingliang-ms** [comment] 2023-06-02 03:58
Duplicate of #7185

**Closed as completed by wangmingliang-ms** 2023-06-02 03:58 UTC
