### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: 431 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.azure.toolkit.intellij.common.auth.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by srinivas5a0** [microsoft/azure-tools-for-java#7384] opened 2023-03-14 07:55 UTC
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.74.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: 431 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.azure.toolkit.intellij.common.auth.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.loadIcon(IntelliJAzureIcons.java:119)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.lambda$doGetIcon$2(IntelliJAzureIcons.java:97)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAz

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:44
Duplicate of #7185

**Closed as completed by wangmingliang-ms** 2023-03-20 01:44 UTC
