### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Unhandled exception in [CoroutineName(com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener), StandaloneCoroutine{Cancelling}@bc1ca9b, Dispatchers.Default]

### ISSUE THREAD

**Issue by Patman2021** [microsoft/azure-tools-for-java#7833] opened 2023-09-05 13:25 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1729x1033,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Unhandled exception in [CoroutineName(com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener), StandaloneCoroutine{Cancelling}@bc1ca9b, Dispatchers.Default]
  java.lang.NullPointerException: Cannot invoke "com.microsoft.azure.toolkit.lib.common.action.AzureActionManager.getAction(com.microsoft.azure.toolkit.lib.common.action.Action$Id)" because "am" is null
at com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener.execute(CognitiveServicesStartupListener.java:37)
```

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:09
Duplicate of #7832

**Closed as completed by wangmingliang-ms** 2023-09-19 02:09 UTC
