### ISSUE TITLE
[intelliJ][Job Upload Storage]A legacy of data when change clusters.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2947] opened 2019-03-27 11:22 UTC
Build:
azure-toolkit-for-intellij-2018.3.develop.1063.03-27-2019

Repro Steps:
1. Create a HDInsight configuration.
2. Choose a365 as Spark clusters. Use Azure Blob as Storage Type. Input some data for Storage account and key.
![image](https://user-images.githubusercontent.com/35950097/55072190-65e81a00-50c5-11e9-8a93-d3e2e3e15df2.png)
3. Change Spark clusters to chayang.
4. Use Azure Blob as Storage Type.

Result:
The data of Storage Account and Storage Key is kept.
![image](https://user-images.githubusercontent.com/35950097/55072144-4c46d280-50c5-11e9-81b0-c7ecb16e23be.png)

Note:
Storage Type: Use ADLS Gen 1 to upload.
Result: The same problem
Storage Type: WebHDFS to upload.
Result: The same problem.

**Comment by lcadzy** [comment] 2019-03-28 00:50
It is by design. When validating storage info , first new model then get data from UI then set data to model.

**Comment by jingyanjingyan** [comment] 2019-03-28 03:56
Close it as by design
@wezhang For common sense, it is not a good option to show the data that does not match to the user,  i am ok to re-open it based on your comment. Thanks.

**Closed by jingyanjingyan** 2019-03-28 03:56 UTC
Labels: HDInsight, IntelliJ, wontfix
