### ISSUE TITLE
An error occured when getting publish profile in jdk11 environment

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3070] opened 2019-04-22 06:27 UTC
### Environment:
```
1. OS: Windows10/Mac
2. Plugin version
   - Azure java toolkit for Eclipse: 3.14.0
   - Azure java toolkit for IntelliJ: 3.21.0
3. Eclipse: 2019-03
4. IntelliJ: IU19.1.1/IC19.1
5. JDK: oracle jdk11.0.2
```
### Repro steps:
1. Right-click a web app and choose `Show Properties`
2. Click on` Get Publish Profile` button
3. Choose where you want to save the profile

### Result:
The Plugin will prompt the user that failed to get Publish Profile, but the publish profile has been saved locally.

Error in Eclipse:
![image](https://user-images.githubusercontent.com/22470312/56486364-ec97e780-6509-11e9-8752-b5e721f63894.png)
Error in IntelliJ:
![image](https://user-images.githubusercontent.com/22470312/56486372-f7527c80-6509-11e9-964a-1a29ddbc8444.png)

**Comment by ZhengJun003** [comment] 2020-06-15 09:21
Can reproduce this issue in azure toolkits for IntelliJ 3.38.0 and azure toolkits for eclipse 3.23.0

IntelliJ:
![image](https://user-images.githubusercontent.com/41051257/84640632-869bca00-af2c-11ea-9800-2d71f58a4bb8.png)

Eclipse:
![image](https://user-images.githubusercontent.com/41051257/84640706-a29f6b80-af2c-11ea-8dc9-2cbeb29a4cc7.png)

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738777

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738818

**Comment by vscjavaci** [comment] 2020-07-02 01:10
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:10 UTC
Labels: Eclipse, IntelliJ, Internal Test, P2, app-service, bug, function, transfter
