### ISSUE TITLE
Right click doesn't work in azure explorer

### ISSUE THREAD

**Issue by juniwang** [Microsoft/azure-tools-for-java#300] opened 2017-04-12 16:16 UTC
- issue type: minor feature issue.
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - select view -> Tools Window -> Azure azure explorer to open azure explorer window
  - select Virtual Machine and right click on the blank area of this item
- expected: the context menu is shown
- actual: it doesn't show. This behavior is not consistent with other tool windows of Intellij.
![2017-04-12_0906](https://cloud.githubusercontent.com/assets/8814383/24967994/a5a6d2e6-1f60-11e7-99d5-88ec39853eb8.png)
![2017-04-12_0904](https://cloud.githubusercontent.com/assets/8814383/24967999/a83da8ea-1f60-11e7-90f8-27e6fc081733.png)

**Comment by martinsawicki** [comment] 2017-04-12 16:17
@lenala could this be more IJ2017-specific breakage?

**Comment by lenala** [comment] 2017-04-12 16:29
No, it is just when you click outside of the label, menu does not pop up, but when you click on the label, it does.

**Comment by martinsawicki** [comment] 2017-04-12 16:32
sounds by design then

**Comment by martinsawicki** [comment] 2017-04-12 16:33
right?

**Comment by lenala** [comment] 2017-04-12 16:41
I agree. Well, it might be nice to do it to make it consistent with other menus, but this is a minor thing.

**Comment by martinsawicki** [comment] 2017-04-12 16:43
closing as by design then

**Closed by martinsawicki** 2017-04-12 16:43 UTC
Labels: bug-bash, IntelliJ
