### ISSUE TITLE
UnknownHostException gets thrown when trying to publish to a Docker Container

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/azure-tools-for-java#135] opened 2017-02-17 20:33 UTC
The publishing just hangs (No RG gets created in my subscription)
![image](https://cloud.githubusercontent.com/assets/22645093/23082185/19f926cc-f50d-11e6-92e2-1a74a833689d.png)

I found this exception in the logs:

`2017-02-17 12:20:56,857 [6646455]   INFO - microsoft.intellij.AzurePlugin - To warm the site up - implicitly trying to connect it 
2017-02-17 12:20:56,917 [6646515]   INFO - microsoft.intellij.AzurePlugin - bug-bash-webb-app491315.centralus.cloudapp.azure.com 
java.net.UnknownHostException: bug-bash-webb-app491315.centralus.cloudapp.azure.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.microsoft.intellij.util.WAHelper.sendGet(WAHelper.java:183)
	at com.microsoft.tasks.DockerContainerDeployTask$2.run(DockerContainerDeployTask.java:86)
`

**Comment by milismsft** [comment] 2017-02-24 19:23
can't repro this in the latest version; the initial error could have been caused by unexpected characters present in the auto-generated names (this was fixed in the later builds).

**Comment by bsaby** [comment] 2017-02-27 08:55
Not repro in the artifacts/azure-toolkit-for-intellij.215.zip

**Closed** 2017-03-01 08:53 UTC
Labels: bug-bash, IntelliJ
