### ISSUE TITLE
searching blob only works if the search string starting from head

### ISSUE THREAD

**Issue by juniwang** [microsoft/azure-tools-for-java#310] opened 2017-04-12 17:07 UTC
- issue type: major issue
- IDE: Intellij 2017
- platform: Windows 10
- plugin version: azure-toolkit-for-intellij.2017.267.04-11-2017
- Repo steps: 
  - Open Azure explorer and select storage, View any blob container 
  - upload files both with and without folders. My hierarchy in my testing container:
      - /sub1/sub2/design.html
      - /CN-OSSLAB-9-26-2014-credentials.publishsettings
      - /ct.txt
  - input "LAB" and click search
- expected: blob "CN-OSSLAB-9-26-2014-credentials.publishsettings" is visible
- actual: blob "CN-OSSLAB-9-26-2014-credentials.publishsettings" is invisible

**Comment by martinsawicki** [comment] 2017-04-12 17:11
@lenala i suspect this worked like this for ever?

**Comment by martinsawicki** [comment] 2017-04-13 22:15
basically by design - worked this way for a long time. Could be revisited in the future, if there is evidence of customer interest in this feature.

**Comment by Flanker32** [comment] 2020-06-02 08:59
Storage explorer and related features has been removed in the latest release, close this issue

**Closed by Flanker32** 2020-06-02 08:59 UTC
Labels: IntelliJ, bug-bash
