### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 97c16a7d-1156-431b-b707-cd5a61844bee] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed. com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.

### ISSUE THREAD

**Issue by sureshburra** [microsoft/azure-tools-for-java#5292] opened 2021-05-24 16:12 UTC
IntelliJ build version: 2021.1.1 IC-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 97c16a7d-1156-431b-b707-cd5a61844bee] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed., throwable=com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
Trace ID: 6844cef7-684c-4244-9deb-d3c817b89000
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.j

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:25
Duplicate of #5311

**Closed by wangmingliang-ms** 2021-07-01 03:25 UTC
Labels: auth
