### ISSUE TITLE
hdinsight explorer error from customer

### ISSUE THREAD

**Issue by adashen** [microsoft/azure-tools-for-java#970] opened 2017-09-01 03:25 UTC
“java.util.concurrent.ExecutionException: java.net.UnknownHostException: msopentechrelease.blob.core.windows.net” error when like below. URL of “msopentechrelease.blob.core.windows.net"

![error](https://user-images.githubusercontent.com/1872137/29954133-2600b7a6-8f08-11e7-899c-4d33d71d8250.jpg)

**Comment by wezhang** [comment] 2017-09-08 06:21
@adashen may I get the full call stack log? 😃

**Comment by djlan** [comment] 2017-09-08 06:27
Had a call with customer. This is actually resolved. Customer has installed two versions of HDInsight tool. One is deprecated. After uninstall the deprecated tool, the issue is gone.

**Comment by t-rufang** [comment] 2019-06-13 05:23
Close this issue since it's resolved.

**Closed by t-rufang** 2019-06-13 05:23 UTC
Labels: HDInsight, IntelliJ
