### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null

### ISSUE THREAD

**Issue by Ryan-Reddy** [microsoft/azure-tools-for-java#6712] opened 2022-06-19 16:23 UTC
IntelliJ build version: 2022.1.2 IU-221.5787.30
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.65.2-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1681x1010,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl:STRING_LITERAL
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.

**Comment by Ryan-Reddy** [comment] 2022-06-19 16:24
no idea what happened, didn't bother my workflow but thought I would submit for you anyway

**Comment by fengshuaihu** [comment] 2022-12-28 09:22
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/5762

**Closed as completed by fengshuaihu** 2022-12-28 09:22 UTC
Labels: Module: HDInsight
