### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group Idea Thread Group failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 

### ISSUE THREAD

**Issue by jonmclean** [microsoft/azure-tools-for-java#5466] opened 2021-07-01 21:13 UTC
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: I had one IDE window open.  I used the toolbox to load a second project and clicked "Open in new Window" when IDEA asked if the project should be in a new window or in the same window.
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group Idea Thread Group failed with an uncaught exception, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 
Caused by: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 
		at com.mi

**Comment by wangmingliang-ms** [comment] 2021-07-06 05:30
Duplicate of #5451

**Closed by wangmingliang-ms** 2021-07-06 05:30 UTC
