### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: containing file is null; hierarchy=class com.intellij.psi.impl.source.html.HtmlTagImpl, context=null, contextFile=null

### ISSUE THREAD

**Issue by sqazombie** [microsoft/azure-tools-for-java#6459] opened 2022-03-01 23:15 UTC
IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,3441x1400,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: containing file is null; hierarchy=class com.intellij.psi.impl.source.html.HtmlTagImpl, context=null, contextFile=null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl:WHITE_SPACE / com.intellij.psi.impl.source.html.HtmlTagImpl:HTML_TAG

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:17
Duplicate of #5762

**Closed as completed by wangmingliang-ms** 2022-05-13 02:17 UTC
Labels: Module: HDInsight
