### ISSUE TITLE
Azure login fails in Eclipse

### ISSUE THREAD

**Issue by yafernandes** [Microsoft/azure-tools-for-java#740] opened 2017-07-07 12:59 UTC
Hi,

I can't log in from Eclipse.  I get the message "Expected and returned userInfo.displayableId doesn't match: ID@microsoft.com != EasyID@microsoft.com" no matter what email I try to log in with.

**Comment by adashen** [comment] 2017-07-10 01:15
Hi, Can you provide more information. Which os do you use? (mac, windows, linux). And what login method  is leveraged? (Interactive or automated). And is your account can login AAD through browser?

**Comment by yafernandes** [comment] 2017-07-12 20:53
Eclipse Neon on Windows.
Interactive login w/ TFA.
azurecert file works.

**Comment by yafernandes** [comment] 2017-07-12 21:05
Sorry, I meant automatic authentication with azureauth file works.

**Comment by adashen** [comment] 2017-07-13 05:55
Hi, from the code trace, it seems your input ID (ID@microsoft.com) is not same as the one from the oauth. So the login failed

**Comment by vladimir-shcherbakov** [comment] 2017-07-13 17:37
Please try to delete cookies in Internet Explorer:

![image](https://user-images.githubusercontent.com/6579928/28179420-b4f07678-67b6-11e7-87c8-9e6b55f785cc.png)

![image](https://user-images.githubusercontent.com/6579928/28179444-cfb1b274-67b6-11e7-9336-17a449b00c31.png)

![image](https://user-images.githubusercontent.com/6579928/28179479-f044a956-67b6-11e7-9699-82091accdbd6.png)

**Comment by maucaro** [comment] 2017-07-26 18:49
I am getting a similar eror: Expected and returned userInfo.displayableId doesn't match: maucaro@microsoft.com != Mauricio.Caro@microsoft.com. If I use an MSA (hotmail account) that is tied to another Azure subscription, I can log in.

**Comment by vladimir-shcherbakov** [comment] 2017-07-26 21:18
@maucaro 
Did you try to delete cookies?

**Comment by maucaro** [comment] 2017-07-27 09:17
@vladimir-shcherbakov, deleting cookies didn't help. Both are the same account; it just so happens that in my case with this corporate account, UPN != displaylabelid. Both serve as email aliases to the same account, by the way. This has not caused problems in any other instance except for this plug-in.

**Comment by vladimir-shcherbakov** [comment] 2017-07-27 20:00
@maucaro, Could you please clarify:
1) You use the latest Azure Toolkit for Eclipse 3.0.6 on Windows 10;
2) You deleted cookies as described [here](https://github.com/Microsoft/azure-tools-for-java/issues/740#issuecomment-315149068)

**Comment by maucaro** [comment] 2017-07-28 21:58
Yes (3.0.6) and yes; just tried again. Here is what I get: Expected and returned userInfo.displayableId doesn't match: maucaro@microsoft.com != Mauricio.Caro@microsoft.com. I think the problem is that for most users UPN = displaylabelId; in my case it doesn't. But, again, this has not been a problem in any other place except for the Azure Toolkit for Eclipse.

**Comment by sorin-bolos** [comment] 2017-08-03 12:28
I have the same problem on IntelliJ Idea. "Expected and returned userInfo.displayableId doesn't match: sorinb@imprezzio.global != sorinb@imprezzio.com". 
I'm using Azure Toolkit for Intellij 3.0.6-2017.2
I tried deleting the cookies but it didn't help

**Comment by uxio** [comment] 2017-08-22 12:33
I have the exact same problem!
I use:

Eclipse Oxygen
MacOS Sierra

**Comment by Eskibear** [comment] 2017-08-24 03:40
@uxio @sorin-bolos @maucaro 
Thanks for the info. 
Fixed in #942 , it now checks `uniqueId` instead of `displayableId`, and it will be included in the next release.

**Comment by adashen** [comment] 2017-09-08 08:55
@maucaro @uxio @yafernandes Can you try to login again on the latest release (3.0.8) which was released yesterday. The issues should have been fixed.

**Closed** 2017-11-02 07:25 UTC
