### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by Rashika-Vats** [microsoft/azure-tools-for-java#7124] opened 2022-11-25 13:23 UTC
IntelliJ build version: 2022.2.2 IC-222.4167.29
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.4
Plugin version: 3.70.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1367x728,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2022-11-29 09:29
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6844

**Closed as completed by Flanker32** 2022-11-29 09:29 UTC
