### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=eventhubs, containerState=DISPOSE_COMPLETED, componentStore=C:\MySources\python\eventhubs) (disposed)

### ISSUE THREAD

**Issue by hades321** [microsoft/azure-tools-for-java#6591] opened 2022-04-26 19:50 UTC
IntelliJ build version: 2022.1 IU-221.5080.210
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,1451x817,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=eventhubs, containerState=DISPOSE_COMPLETED, componentStore=C:\MySources\python\eventhubs) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:190)
	at com.microsoft.azure.toolkit.intellij.common.survey.SurveyPopUpDialog.<init>(SurveyPopUpDialog.java:65)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.showSurveyPopup(CustomerSurveyManager.java:77)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.lambda$takeSurvey$0(CustomerSurveyManager.java:72)
```

**Comment by wangmingliang-ms** [comment] 2022-04-28 03:23
Duplicate of #6568

**Closed as completed by wangmingliang-ms** 2022-04-28 03:23 UTC
Labels: Type: Bug
