### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 8894c498-2883-4dc1-af57-07ff2b09cc41] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed. java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by Jonasmo12** [microsoft/azure-tools-for-java#7559] opened 2023-05-19 07:07 UTC
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1470x920,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 8894c498-2883-4dc1-af57-07ff2b09cc41] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed., throwable=java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:62)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
```

**Comment by Flanker32** [comment] 2023-07-31 08:51
@Jonasmo12 Thanks for your report and sorry for the late response. Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7682.

Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7682.

**Closed as completed by Flanker32** 2023-07-31 08:51 UTC
