### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Function_ switcheroo_ factoryName_ Deploy Functions.xml com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployModel

### ISSUE THREAD

**Issue by htmfilho** [microsoft/azure-tools-for-java#6845] opened 2022-08-12 12:05 UTC
IntelliJ build version: 2022.2 IU-222.3345.118
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1698x865,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Function_ switcheroo_ factoryName_ Deploy Functions.xml, throwable=com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployModel
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:58)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployConfiguration.lambda$readExternal$0(FunctionDeployConfiguration.java:170)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployConfiguration.readExternal(FunctionDeployConfiguration.java:170)
Caused by

**Comment by wangmingliang-ms** [comment] 2022-09-04 10:36
duplicate of #6670

**Closed as completed by wangmingliang-ms** 2022-09-04 10:36 UTC
