### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by egorStaarostin** [microsoft/azure-tools-for-java#7194] opened 2022-12-24 19:40 UTC
IntelliJ build version: 2022.3.1 IC-223.8214.52
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.71.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.net.SocketException: Connection reset
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.lambda$fetchLog$0(SparkJobLogInputStream.java:43)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.fetchLog(SparkJobLogInputStream.java:42)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.available(SparkJobLogInputStream.java:66)
Caused by: java.net.SocketException: Connection reset
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:247)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:253)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getBatchSparkJobStatus(SparkBatchSubmission.java

**Comment by fengshuaihu** [comment] 2022-12-28 03:47
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7151

**Closed as completed by fengshuaihu** 2022-12-28 03:47 UTC
Labels: Module: HDInsight
