### ISSUE TITLE
[IntelliJ][Auth]Error occurred when sign in and sign out

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#2494] opened 2018-12-12 03:46 UTC
Build: Develop 900
IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
OS: MAC

Repro Step:

Create a project.
Open Azure Explorer.
Right click on Azure Explorer or click on sign in icon.
Sign in to Azure with interactive in Azure Explorer.(If you have already signed to Azure, please sign out first.)
Check Error occurred.
Screenshot:
Sign in:
<img width="1212" alt="screen shot 2018-12-12 at 11 39 00 am" src="https://user-images.githubusercontent.com/40199316/49845697-c5fecd00-fe02-11e8-80b8-766ef3f57c40.png">
<img width="1213" alt="screen shot 2018-12-12 at 11 39 10 am" src="https://user-images.githubusercontent.com/40199316/49845702-ca2aea80-fe02-11e8-9b27-9eea2ae0fe66.png">
<img width="1680" alt="screen shot 2018-12-12 at 11 39 39 am" src="https://user-images.githubusercontent.com/40199316/49845714-d57e1600-fe02-11e8-9ba7-cb560c36dbe5.png">
<img width="1679" alt="screen shot 2018-12-12 at 11 40 07 am" src="https://user-images.githubusercontent.com/40199316/49845715-d747d980-fe02-11e8-9759-216b2a4fc46d.png">

sign out: 
<img width="1679" alt="screen shot 2018-12-12 at 11 43 47 am" src="https://user-images.githubusercontent.com/40199316/49845822-49b8b980-fe03-11e8-9706-83bdbe4735b4.png">
<img width="1680" alt="screen shot 2018-12-12 at 11 44 01 am" src="https://user-images.githubusercontent.com/40199316/49845825-4ae9e680-fe03-11e8-90b5-9c1aede07312.png">

**Comment by Eskibear** [comment] 2018-12-12 04:58
It's a known issue as mentioned in #2368 . Won't fix in this sprint. 
The workaround will be any of the following:
1. Request adal lib to provide a choice, not to write this into error log. 
2. Investigate if we can dismiss such log in IDEA.

**Comment by Eskibear** [comment] 2018-12-12 05:01
For the NPE carried with sign-out, I'll investigate.

**Comment by Eskibear** [comment] 2018-12-12 05:41
I cannot reproduce the NPE. Can you stably reproduce it? Please share the detailed steps before the sign-out operation.

**Comment by v-lanjli** [comment] 2018-12-12 05:55
I can't reproduce the issue of sign-out now....

**Closed** 2018-12-12 08:16 UTC
Labels: IntelliJ, auth, bug, help wanted, notreproduce
