### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by c0dezer019** [microsoft/azure-tools-for-java#5446] opened 2021-06-29 02:38 UTC
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Linux
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,4,28,1920x1054,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=BattleshipReact, containerState=DISPOSE_COMPLETED, componentStore=/home/brian/Documents/c0de_box/projects/BattleshipReact) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=BattleshipReact, containerState=DISPOSE_COMPLETED, componentStore=/home/brian/Documents/c0de_box/projects/BattleshipReact) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:15
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-01 03:15 UTC
