### ISSUE TITLE
The refresh on Azure Explorer does not keep the original expanding level

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#332] opened 2017-04-12 18:56 UTC
Issue:
When you navigate to some resource node in the tree view of Azure explorer, and you want to see if there's any update, after you click the refresh button, you will see the original expanding view is not kept.

Expected:
Keep at the original expanding state.

Repro:
1. Sign in with your azure subscription.
2. Open Azure Explorer.
3. Navigate to some deep node in the tree view.
4. Refresh it, then you will see that you're brought back to top level.

**Before Refresh:**
<img width="675" alt="screen shot 2017-04-12 at 11 50 45 am" src="https://cloud.githubusercontent.com/assets/6917718/24974389/cbd8e27c-1f76-11e7-8133-9b84320ef717.png">

**After Refresh:**
<img width="671" alt="screen shot 2017-04-12 at 11 51 00 am" src="https://cloud.githubusercontent.com/assets/6917718/24974401/d8f10cfa-1f76-11e7-9fb8-73408478086f.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: Eclipse Neon.3

Plugin: WindowsAzurePlugin4EJ.273.04-12-2017.zip

Feature: Azure Explorer

**Comment by martinsawicki** [comment] 2017-04-12 22:28
duplicate of an issue I logged earlier. We cannot do this safely/easily. Maybe in the future.

**Comment by reyang** [comment] 2017-04-17 19:00
closed as a dup with #261

**Closed by reyang** 2017-04-17 19:00 UTC
Labels: bug-bash, Eclipse
