### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by torchy-newman** [microsoft/azure-tools-for-java#5537] opened 2021-07-15 19:56 UTC
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,1117x513,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=sv-usage-allowance-extract, containerState=DISPOSE_COMPLETED, componentStore=C:\single-view\git\azure\single-view-business-transformation\usage-allowance-extract) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=sv-usage-allowance-extract, containerState=DISPOSE_COMPLETED, componentStore=C:\single-view\git\azure\single-view-business-transformation\usage-allowance-extract) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.Pr

**Comment by wangmingliang-ms** [comment] 2021-07-19 15:11
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-19 15:11 UTC
