### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2f900f88)

### ISSUE THREAD

**Issue by Entetry** [microsoft/azure-tools-for-java#8082] opened 2023-12-29 11:29 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Linux
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.83.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x983,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2f900f88)
	at com.microsoft.azure.toolkit.intellij.storage.code.spring.StoragePathPrefixCompletionProvider.addCompletions(StoragePathPrefixCompletionProvider.java:30)
```

**Comment by Flanker32** [comment] 2024-01-29 08:41
@Entetry Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8109. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 08:41
Duplicate of #8109

**Closed as completed by Flanker32** 2024-01-29 08:41 UTC
