### ISSUE TITLE
[IntelliJ] Uncaught Exception  java.lang.Throwable: com.microsoft.azure.toolkit.intellij.common.auth.IntelliJSecureStore$LazyHolder <clinit> requests com.intellij.ide.passwordSafe.PasswordSafe instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

### ISSUE THREAD

**Issue by tyger** [microsoft/azure-tools-for-java#8474] opened 2024-07-12 19:15 UTC
IntelliJ build version: 2024.2 Beta IU-242.20224.38
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.90.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: com.microsoft.azure.toolkit.intellij.common.auth.IntelliJSecureStore$LazyHolder <clinit> requests com.intellij.ide.passwordSafe.PasswordSafe instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.microsoft.azure.toolkit.intellij.common.auth.IntelliJSecureStore.<init>(IntelliJSecureStore.java:31)
	at com.microsoft.azure.toolkit.intellij.common.auth.IntelliJSecureStore$LazyHolder.<clinit>(IntelliJSecureStore.java:20)
	at com.microsoft.azure.toolkit.intellij.common.auth.IntelliJSecureStore.getInstance(IntelliJS

**Comment by wangmingliang-ms** [comment] 2024-07-18 07:35
Duplicate of #8473

**Closed as completed by wangmingliang-ms** 2024-07-18 07:35 UTC
