### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 960b4628-49b6-4bc0-bab3-716bd98aa3da] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed. java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by legalsight-admin** [microsoft/azure-tools-for-java#7673] opened 2023-07-07 18:35 UTC
IntelliJ build version: 2022.2.3 IU-222.4345.14
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.75.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 960b4628-49b6-4bc0-bab3-716bd98aa3da] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed., throwable=java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:62)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
```

**Comment by Flanker32** [comment] 2023-07-31 08:51
@legalsight-admin Thanks for your report and sorry for the late response. Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7682.

Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7682.

**Closed as completed** 2023-07-31 08:51 UTC
