### ISSUE TITLE
[IntelliJ] Uncaught Exception  java.lang.AssertionError: com.microsoft.azure.toolkit.lib.common.telemetry.AzureTelemeter <clinit> requests com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

### ISSUE THREAD

**Issue by erard22** [microsoft/azure-tools-for-java#8476] opened 2024-07-16 13:31 UTC
IntelliJ build version: 2024.2 Beta IU-242.20224.38
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.90.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,1535x1679,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: com.microsoft.azure.toolkit.lib.common.telemetry.AzureTelemeter <clinit> requests com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:82)
	at com.microsoft.azure.toolkit.intellij.common.settings.IntellijStore.getInstance(IntellijStore.java:36)
	at com.microsoft.azure.toolkit.intellij.common.telemetry.IntelliJAzureTelemetryCommonPropertiesProvider.getInstallationId(IntelliJAzureTelemetryCommonPropertiesProvider.java:42)
	at com.microsoft.azure.toolkit.intellij

**Comment by wangmingliang-ms** [comment] 2024-07-18 07:35
Duplicate of #8473

**Closed as completed by wangmingliang-ms** 2024-07-18 07:35 UTC
