### ISSUE TITLE
Unable to create a storage account and the error message is confusing (Message from Azure "null") 

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#55] opened 2017-02-17 18:09 UTC
![image](https://cloud.githubusercontent.com/assets/7052173/23077284/d1714754-f4f8-11e6-895f-d8cf90ceef3e.png)

Ideally I'd like to do all the necessary steps from the IntelliJ tool window and not be transferred to portal or elsewhere.

**Comment by hovsepm** [comment] 2017-02-17 18:10
This happened during VM creation wizard.

**Comment by hovsepm** [comment] 2017-02-17 18:21
Same error happen when I click Finish. But now it complains that 'Microsoft.Network' is not registered. But the ugly thing here is that my window where I was specifying resources is closed! I cannot retry - have to start it from scratch. Now I have partially created resources and storage account but no VM. How should I easily cleanup leftover resources?

**Comment by lenala** [comment] 2017-02-17 20:12
Similar error message for App Service creation, but at least the window does not close:
![image](https://cloud.githubusercontent.com/assets/6208231/23081542/2dfd1294-f50a-11e6-8379-f130d2a220d3.png)

**Comment by martinsawicki** [comment] 2017-03-02 00:42
looks like duplicate of https://github.com/Microsoft/azure-tools-for-java/issues/62

Probably needs to be resolved in the SDK, not plugin.,

**Comment by martinsawicki** [comment] 2017-04-18 21:52
should have been fixed by now

**Comment by bsaby** [comment] 2017-04-19 04:22
Can not repro the above issue.
Build used: artifacts/azure-toolkit-for-intellij.2017.333.04-18-2017.zip

**Closed** 2017-04-19 06:27 UTC
Labels: bug-bash, fixed, IntelliJ
