### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception : Conflicting component name 'RunManager'

### ISSUE THREAD

**Issue by pasimoes** [microsoft/azure-tools-for-java#5894] opened 2021-10-01 13:11 UTC
IntelliJ build version: 2021.2.1 IE-212.5284.54
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2046x1210,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@8283cca,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=microservices-demo, containerState=COMPONENT_CREATED, componentStore=/Users/pasimoes/Work/Workspaces/jetbrains/microservices-demo))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfiguration.java

**Comment by wangmingliang-ms** [comment] 2021-10-03 14:31
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-03 14:31 UTC
