### ISSUE TITLE
Minor UI issues on the Create Docker Host dialog

### ISSUE THREAD

**Issue by aovechki** [Microsoft/azure-tools-for-java#307] opened 2017-04-12 16:54 UTC
win10, x64, Eclipse.Mars

Region list should be sorted
The default name should use a prefix that is more specific, as opposed to a generic "remotesystemstem460904"

**Comment by martinsawicki** [comment] 2017-04-12 17:00
sounds like a dupe of another issue we discussed a few weeks ago - alphabetical would match the portal

**Comment by lenala** [comment] 2017-04-12 20:22
Done for sorted region list.

**Comment by davidliangze** [comment] 2017-04-14 02:33
Test passed.
Build used for IntelliJ: azure-toolkit-for-intellij.2017.282.04-13-2017
Build used for Eclipse Mars 2: WindowsAzurePlugin4EJ.286.04-13-2017

**Closed** 2017-04-14 02:54 UTC
Labels: bug-bash, Eclipse, fixed, IntelliJ, Mars
