### ISSUE TITLE
[IntelliJ][Linux\Mac] Can't sign to azure with develop 887

### ISSUE THREAD

**Issue by v-lanjli** [Microsoft/azure-tools-for-java#2460] opened 2018-12-07 07:31 UTC
Build: develop 887
intelliJ 2018.3.1
OS: Linux\Mac

Repro Steps:

1. Create a new project.
2. Open Azure Explorer.
3. Right click on Azure Explorer or click sign in icon.  
2. Sign to Azure with interactive in Azure Explorer. (If you have already signed to Azure, please sign out first.)

Result: Can't sign in
**The Log for Windows**
2018-12-11 14:42:18,294 [ 372237]   WARN - eSparkServerlessClusterManager - Checking Azure Data Lake Spark pool got error: com.microsoft.azuretools.adauth.AuthException: Can't get Azure Data Lake account since the user isn't signed in, please sign in by Azure Explorer. 
2018-12-11 14:42:23,200 [ 377143]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1 
**The Log for Linux:**
2018-12-11 13:48:20,098 [  91457]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 48030 ms
2018-12-11 13:48:23,907 [  95266]   WARN - eSparkServerlessClusterManager - Checking Azure Data Lake Spark pool got error: com.microsoft.azuretools.adauth.AuthException: Can't get Azure Data Lake account since the user isn't signed in, please sign in by Azure Explorer.
2018-12-11 13:48:54,153 [ 125512]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 51837ms; general responsiveness: 2/51 sluggish; EDT responsiveness: 4/52 sluggish, 15/52 very slow
2018-12-11 13:48:55,065 [ 126424]   INFO - j.ide.ui.OptionsTopHitProvider - 692 ms spent to cache options in project
2018-12-11 13:48:55,065 [ 126424]   INFO - tartup.impl.StartupManagerImpl - Some post-startup activities freeze UI for noticeable time. Please consider making them DumbAware to do them in background under modal progress, or just making them faster to speed up project opening.
2018-12-11 13:48:55,065 [ 126424]   INFO - tartup.impl.StartupManagerImpl - Activity run in 692ms on UI thread
2018-12-11 13:48:55,632 [ 126991]   INFO - tartup.impl.StartupManagerImpl - GradleJvmStartupActivity run in 424ms on UI thread
2018-12-11 13:48:57,553 [ 128912]   INFO - j.ide.ui.OptionsTopHitProvider - 1696 ms spent on EDT to cache options in project
2018-12-11 13:52:15,043 [ 326402]   WARN - eSparkServerlessClusterManager - Checking Azure Data Lake Spark pool got error: com.microsoft.azuretools.adauth.AuthException: Can't get Azure Data Lake account since the user isn't signed in, please sign in by Azure Explorer.
**The Log for MAC:**
2018-12-11 13:57:31,161 [  36819]   INFO - pl.projectlevelman.NewMappings - VCS Root: [] - [<Project>] 
2018-12-11 13:57:31,485 [  37143]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 2180 ms 
2018-12-11 13:57:31,487 [  37145]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 45ms; general responsiveness: ok; EDT responsiveness: ok 
2018-12-11 13:57:33,676 [  39334]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2187ms; general responsiveness: ok; EDT responsiveness: ok 
2018-12-11 13:57:33,676 [  39334]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 5 files to update 
2018-12-11 13:57:33,837 [  39495]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 161ms; general responsiveness: ok; EDT responsiveness: ok 
2018-12-11 13:57:33,913 [  39571]   INFO - j.ide.ui.OptionsTopHitProvider - 72 ms spent to cache options in project 
2018-12-11 13:57:33,990 [  39648]   INFO - CompilerWorkspaceConfiguration - Available processors: 4 
2018-12-11 13:57:34,069 [  39727]   INFO - j.ide.ui.OptionsTopHitProvider - 105 ms spent on EDT to cache options in project 
2018-12-11 13:57:34,225 [  39883]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2018-12-11 13:48) 
2018-12-11 13:57:37,998 [  43656]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-12-11 13:57:38,063 [  43721]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 2ms; general responsiveness: ok; EDT responsiveness: ok 
2018-12-11 13:57:39,315 [  44973]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1252ms; general responsiveness: ok; EDT responsiveness: ok 
2018-12-11 13:57:40,305 [  45963]   WARN - eSparkServerlessClusterManager - Checking Azure Data Lake Spark pool got error: com.microsoft.azuretools.adauth.AuthException: Can't get Azure Data Lake account since the user isn't signed in, please sign in by Azure Explorer. 
2018-12-11 14:02:52,669 [ 358327]   WARN - eSparkServerlessClusterManager - Checking Azure Data Lake Spark pool got error: com.microsoft.azuretools.adauth.AuthException: Can't get Azure Data Lake account since the user isn't signed in, please sign in by Azure Explorer. 
2018-12-11 14:03:09,289 [ 374947]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 0 to update, calculated in 20ms 
**Can sign in to azure on Windows, but you will get the error messages.** The error messages as below:
java.lang.NullPointerException at com.intellij.openapi.wm.impl.InternalDecorator.setTitleActions(InternalDecorator.java:316) at com.intellij.openapi.wm.impl.ToolWindowImpl.setTitleActions(ToolWindowImpl.java:309) at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$addToolbarItems$2(ServerExplorerToolWindowFactory.java:372) at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97) at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:133) at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:117) at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOutAction.java:46) at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72) at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60) at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$0(ServerExplorerToolWindowFactory.java:213) at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) at javax.swing.AbstractButton.doClick(AbstractButton.java:376) at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842) at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886) at java.awt.Component.processMouseEvent(Component.java:6548) at javax.swing.JComponent.processMouseEvent(JComponent.java:3325) at java.awt.Component.processEvent(Component.java:6313) at java.awt.Container.processEvent(Container.java:2237) at java.awt.Component.dispatchEventImpl(Component.java:4903) at java.awt.Container.dispatchEventImpl(Container.java:2295) at java.awt.Component.dispatchEvent(Component.java:4725) at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526) at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) at java.awt.Container.dispatchEventImpl(Container.java:2281) at java.awt.Window.dispatchEventImpl(Window.java:2746) at java.awt.Component.dispatchEvent(Component.java:4725) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764) at java.awt.EventQueue.access$500(EventQueue.java:98) at java.awt.EventQueue$3.run(EventQueue.java:715) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) at java.awt.EventQueue$4.run(EventQueue.java:737) at java.awt.EventQueue$4.run(EventQueue.java:735) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) at java.awt.EventQueue.dispatchEvent(EventQueue.java:734) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
![image](https://user-images.githubusercontent.com/40199316/49718325-b6fa0c80-fc94-11e8-82c3-c13163cfe938.png)

**Comment by v-lanjli** [comment] 2018-12-11 10:01
**Add screenshot for MAC:**
![image](https://user-images.githubusercontent.com/40199316/49792529-ee88b780-fd6d-11e8-986d-2b6c7464fb78.png)
**Add screenshot for Linux:**
![image](https://user-images.githubusercontent.com/40199316/49792845-b2098b80-fd6e-11e8-82a2-2d634a915fb3.png)

**Comment by Eskibear** [comment] 2018-12-11 10:53
Can it be the network issue? Using the same machine, are you able to sign-in Azure Portal via an external browser?

**Comment by Eskibear** [comment] 2018-12-12 02:35
@wezhang I just cannot reproduce it. And from the result, it's out of our control I think. 
I suggest:
1. Get rid of environmental factors like networking, etc. 
2. See if device login works as a mitigation.

**Comment by wezhang** [comment] 2018-12-12 03:10
@v-lanjli Could you help to try the device code login?

**Comment by v-lanjli** [comment] 2018-12-12 03:13
Tried, the device code login works fine.

**Comment by wezhang** [comment] 2018-12-12 03:20
@v-lanjli feel free to close the issue if it's fixed, please. Thanks!

**Closed** 2018-12-12 08:04 UTC
Labels: IntelliJ, bug, need more info, notreproduce
