### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by allonli** [microsoft/azure-tools-for-java#7800] opened 2023-08-26 10:04 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1120,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:465)
```

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:04
Duplicate of #7736

**Closed as completed by wangmingliang-ms** 2023-09-08 06:04 UTC
