### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by 1gordev** [microsoft/azure-tools-for-java#5449] opened 2021-06-29 13:14 UTC
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1811x1199,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=px-jwt, containerState=DISPOSE_COMPLETED, componentStore=K:\Work\proximity\px-auth) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=px-jwt, containerState=DISPOSE_COMPLETED, componentStore=K:\Work\proximity\px-auth) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.azure.toolkit.intellij.azuresdk.enforcer.AzureSdkEnforcer.enforce(A

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:14
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-01 03:14 UTC
