### ISSUE TITLE
Null issue for Docker Hosts

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1160] opened 2017-10-24 07:26 UTC
In most cases, both global and mooncake

1. Right click a project and click Publish as Docker Container
2. New a docker host ,e.g. gsspringboot52881 (you can use the default configuration)
3. After published, the new host will display in the Azure explorer, right click gsspringboot52881 and choose any option(e.g. refresh), error occurs unless you refresh **Docker Hosts** node.
![image](https://user-images.githubusercontent.com/22470312/31929688-864e3e62-b8cf-11e7-97bf-ca03aeb3fa9c.png)

**Error Log:**
```
null
java.lang.NullPointerException
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostNode.refreshItems(DockerHostNode.java:88)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:130)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by bsaby** [comment] 2017-10-24 09:04
I can't repro null issue in v3.0.10 global

**Comment by adashen** [comment] 2017-10-25 05:27
@bsaby this should not be a regression issue. Please try the following steps
1. Open intellIj and show azure explorer. make sure don't click the docker host node
2. from project publish to docker container
3. go to the explorer and right-click the new added node.

**Comment by adashen** [comment] 2017-10-25 05:29
The issue is caused by add the docker child node from dockermodule but the dockermanager is not initialized yet. dockermanager is only initialized in docker module in the refresh event

**Comment by bsaby** [comment] 2017-10-25 08:51
Not regression, also repro in v3.0.10 release version global.

**Comment by ZhengJun003** [comment] 2020-06-12 08:03
According to this issue: #4353, can't reproduce this issue

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738792

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: IntelliJ, Internal Test, P3, bug, docker-host, stacktrace, transfter
