### ISSUE TITLE
[IntelliJ][ReportedByUser] Unable to view log stream

### ISSUE THREAD

**Issue by cascer1** [microsoft/azure-tools-for-java#6098] opened 2021-11-18 08:59 UTC
#### Setup

IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2

####  Describe the bug

Trying to view the log stream for a function app never moves past `Connecting to log stream...`

It worked for me on my previous laptop, but not on the new one.

####  To Reproduce

1. Right-click a function app in the explorer 
2. Select `Start streaming logs`
3. Observe result

**Comment by Flanker32** [comment] 2021-11-19 02:59
@cascer1 Thanks for your report, for this issue, so for the same app, toolkit in your new PC could not view the log streaming but works fine with the old one? Could you please share the toolkit version in your old PC? By the way, could this issue be reproduced for other function app or only occurs for specific one?

**Comment by cascer1** [comment] 2021-11-22 07:43
Hi @Flanker32 Thanks for getting back to me. I'm afraid that I don't know the toolkit version on my previous laptop as I had to exchange it for this new one. I'm using toolkit version `3.58.0-2021.2`.

This happens to all function apps that I have access to.

**Comment by Flanker32** [comment] 2021-11-22 08:14
@cascer1 Thanks for your message. Could you please try log streaming in portal and see whether it could works? You may get the feature here
![image](https://user-images.githubusercontent.com/12445236/142825994-50f96a0b-b9ca-410c-b56a-3ccc7130274a.png)

**Comment by cascer1** [comment] 2021-11-22 08:22
Hi @Flanker32 

I am able to view the log stream in the Azure portal. That's why I believe it's an issue with the IntelliJ plugin and reported it here :)

**Comment by Flanker32** [comment] 2021-11-22 09:21
@cascer1 Got it, I tried to create a function app with http and timer trigger and the log streaming seems works well. Could you please help share the java version/os and pricing tier for your function app? And, it could be better if you could share me a demo project with the log streaming issue so that I may try to reproduce the issue and fix it.

**Comment by cascer1** [comment] 2021-11-22 10:12
@Flanker32 I'm afraid the project is under NDA so I can't reveal much, but I do think that the following information can be helpful:

* Java 11 (compiled with `openjdk 11.0.13 2021-10-19`)
* Pricing tier PremiumV2_P1v2
* Running in West Europe 
* Windows

My coworkers using the same version of IntelliJ and the same version of the plugin are able to stream logs without any issues.

**Comment by Flanker32** [comment] 2021-11-22 13:05
@cascer1 Thanks for your information! So this seems to be an issue of local configuration? Did you enable proxy and could you please try the feature without proxy? 
If not, could you please try backup and clean the Intellij configuration in `${user_home}\AppData\Roaming\JetBrains\`, reinstall the plugin and try again?

**Comment by cascer1** [comment] 2021-11-23 07:56
Hi again @Flanker32 

I have not enabled proxy, I changed it to inherit the system setting but that did not fix the issue (I don't think there's a proxy config on the system so that makes sense to me)

I've tried reinstalling the plugin after making a backup (make backup, remove plugin, restart, install plugin, restart) but this unfortunately also doesn't solve the issue.

**Comment by Flanker32** [comment] 2021-11-23 08:27
@cascer1 Thanks a lot for your information and help! Well I'm also puzzled for this issue... could you please help try the following items?
- Could you please try auth your account in your coworkers' IntelliJ and try the log streaming to see whether its an issue of account or the toolkit installation.
- Could you please try install the toolkit in a new intellij distribution(for instance, IC-2021.2) and see whether it could work? As intellij will not shared configuration within different version and we could see whether its an issue of intellij configuration.
- Could you please try backup and clean the azure identity cache in `${user_home}\AppData\Local\.IdentityService` to see whether this is an authentication issue? As log streaming will not share http client with toolkit and there might be some auth issue for log streaming.

Sorry for the trouble and really appreciate for your help!

**Comment by cascer1** [comment] 2021-11-25 08:02
@Flanker32 I've tried logging in on another laptop but the way our auth system is setup makes it practically impossible to do so. I've tried installing IntelliJ 2021.3 RC and then installing the plugin there but I'm running into the same issue. I even removed and re-installed IntelliJ and the azure cli without any success. 

Removing the `.IdentityService` directory with its contents doesn't solve the issue either I'm afraid.

**Comment by cascer1** [comment] 2021-11-25 08:15
I am able to stream logs by typing the relevant command in the terminal in IntelliJ: `az webapp log tail -resource-group foo --name bar`

**Comment by Flanker32** [comment] 2021-11-25 09:21
@cascer1 Thanks for your information and really appreciate your help! Glad to see you the issue could be resolved by  workaround, I'll try to resolve this issue in future development and will update in this issue once there are some updates.

**Comment by cascer1** [comment] 2022-01-03 09:08
Hi again,

I'm not sure what changed, but I am now able to view log streams again in IntelliJ.

Using toolkit version `3.60.0-2021.3` in IntelliJ `2021.3.1`

**Comment by Flanker32** [comment] 2022-01-03 12:15
@cascer1 Thanks for your message, glad to see the issue was resolved~

**Closed as completed** 2022-11-08 15:04 UTC
Labels: Type: Bug, Tool: IntelliJ, Reason: not reproduceable, workaround, Module: Azure Functions, P2, State: Resolved
