### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by SNY019** [microsoft/azure-tools-for-java#5440] opened 2021-06-28 13:58 UTC
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x512,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=import-rules-cassandra-function, containerState=DISPOSE_COMPLETED, componentStore=C:\Projects\CounterDo\21-06-2021\import-rules-cassandra-function) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=import-rules-cassandra-function, containerState=DISPOSE_COMPLETED, componentStore=C:\Projects\CounterDo\21-06-2021\import-rules-cassandra-function) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProj

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:16
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-01 03:16 UTC
