### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null

### ISSUE THREAD

**Issue by talios** [microsoft/azure-tools-for-java#7456] opened 2023-04-11 07:51 UTC
IntelliJ build version: 2023.1 IC-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x1000,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null
	at org.wso2.lsp4intellij.actions.LSPGotoDeclarationAction.actionPerformed(LSPGotoDeclarationAction.java:31)
```

**Comment by wangmingliang-ms** [comment] 2023-04-11 13:08
Duplicate of #7387

**Closed as completed by wangmingliang-ms** 2023-04-11 13:08 UTC
Labels: Type: Bug, Module: Bicep
