### ISSUE TITLE
[IntelliJ][Console] Cancel config should not create config anyway

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2950] opened 2019-03-28 03:40 UTC
Build: dev 1056

Repro Steps:
1. Create a new project, make sure there is no config file
2. Click Tools\Spark Console\Run Spark Local Console (Scala)
3. When pops the config dialog, click x to close the dialog

Result:
The config is created anyway

Expect:
When user want to cancel console, no need to create config anyway.

**Comment by t-rufang** [comment] 2020-06-28 05:03
This is by design and we won't fix this issue

**Closed by t-rufang** 2020-06-28 05:03 UTC
Labels: HDInsight, IntelliJ, Internal Test, invalid, wontfix
