### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by fhdupuydelome** [microsoft/azure-tools-for-java#7825] opened 2023-09-01 17:41 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:465)
```

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:03
Duplicate of #7736

**Closed as completed by wangmingliang-ms** 2023-09-08 06:03 UTC
