### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Cannot process toolwindow Resource Connections (Deprecated)

### ISSUE THREAD

**Issue by dthuering** [microsoft/azure-tools-for-java#8015] opened 2023-11-24 13:38 UTC
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1800x1125,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Cannot process toolwindow Resource Connections (Deprecated)
  com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.facet.ProjectFacetManager because container is already disposed (container=Project(name=sky-cordova-app, containerState=DISPOSE_COMPLETED, componentStore=<REDACTED: user-file-path>) (disposed))
at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindowFactory.shouldBeAvailable(ResourceConnectionExplorer.java:139)
```

**Comment by Flanker32** [comment] 2023-12-06 12:06
Duplicate of #7889

**Comment by Flanker32** [comment] 2023-12-06 12:06
@dthuering Thanks for your report and sorry for the trouble, please track the issue in #7889

**Closed as completed by Flanker32** 2023-12-06 12:06 UTC
