### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by mike-mwangi** [microsoft/azure-tools-for-java#4245] opened 2020-04-07 10:54 UTC
IntelliJ build version: 2019.3.4 IU-193.6911.18
OS: Linux
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.34.0-2019.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: ddd726c9-7acc-432a-8b04-49a7c4110d00\r\nCorrelation ID: 3509df36-6390-486d-a8a1-afd90d93a14a\r\nTimestamp: 2020-04-07 10:53:27Z","error_codes":[90002],"timestamp":"2020-04-07 10:53:27Z","trace_id":"ddd726c9-7acc-432a-8b04-49a7c4110d00","correlation_id":"3509df36-6390-486d-a8a1-afd90d93a14a","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)
	at com.microsoft.azure.management.resources.fluentcore.

**Comment by andxu** [comment] 2020-04-10 00:50
Will adjust Auth/Login in next few weeks, @mike-mwangi Can you help us to verify whether the issue is resolved if we can provide you a private bit?

**Comment by vscjavaci** [comment] 2020-06-02 09:02
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment] 2020-06-03 06:45
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.

**Closed by vscjavaci** 2020-06-03 06:45 UTC
Labels: auth, duplicate, stacktrace
