### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Cannot process toolwindow Resource Connections (Deprecated)

### ISSUE THREAD

**Issue by AlanChaney** [microsoft/azure-tools-for-java#8114] opened 2024-01-22 20:46 UTC
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.84.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2558x1363,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$1@fa2bedb,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Cannot process toolwindow Resource Connections (Deprecated)
  com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.facet.ProjectFacetManager because container is already disposed (container=Project(name=light-edit, containerState=DISPOSE_COMPLETED, componentStore=<REDACTED: user-file-path> <REDACTED: user-file-path>) (disposed))
at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindowFactory.shouldBeAvailable(ResourceConnectionExplorer.java:139)
```

**Comment by Flanker32** [comment] 2024-01-29 07:15
@AlanChaney Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8114. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:15
Duplicate of #8114

**Closed as completed by Flanker32** 2024-01-29 07:15 UTC
