### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.LeafPsiElement #Groovy  because: parent is null

### ISSUE THREAD

**Issue by jmestizo** [microsoft/azure-tools-for-java#6379] opened 2022-02-08 15:23 UTC
IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1696x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@a4076e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.LeafPsiElement #Groovy  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.LeafPsiElement:new line
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.ru

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:16
Duplicate of #5762

**Closed as completed by wangmingliang-ms** 2022-05-13 02:16 UTC
Labels: Module: HDInsight
