### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by phongcuncon** [microsoft/azure-tools-for-java#7960] opened 2023-10-25 23:06 UTC
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.80.2-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1080,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2023-11-19 12:23
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-11-19 12:23 UTC
