### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError

### ISSUE THREAD

**Issue by saipotta-eis** [microsoft/azure-tools-for-java#2733] opened 2019-01-28 20:04 UTC
IntelliJ build version: 2018.3.3 IU-183.5153.38
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1680x954,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError
	at com.microsoft.azure.hdinsight.spark.jobs.framework.JobRequestDetails.getJobRequestDetail(JobRequestDetails.java:75)
	at com.microsoft.azure.hdinsight.spark.jobs.YarnJobHttpHandler.handle(YarnJobHttpHandler.java:41)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)]
```

**Comment by t-rufang** [comment] 2020-06-28 03:19
Close this bug since we can't repro it

**Comment by t-rufang** [comment] 2020-06-28 03:22
Hi @saipotta-eis , we are clean up GitHub issues recently, and we close this bug since we can't repro it. Feel free to reopen the issue if the bug still reproduce for you. It would be better if you can let us know the repro steps.

**Closed by t-rufang** 2020-06-28 03:22 UTC
Labels: HDInsight, IntelliJ, System Telemetry, notreproduce, stacktrace
