### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: parent is null

### ISSUE THREAD

**Issue by sansmoraxz** [microsoft/azure-tools-for-java#6615] opened 2022-05-07 09:36 UTC
IntelliJ build version: 2022.1 IU-221.5080.210
OS: Windows 11
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl:WHITE_SPACE
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:12
Duplicate of #5762

**Closed as completed by wangmingliang-ms** 2022-05-13 02:12 UTC
Labels: Module: HDInsight
