### ISSUE TITLE
[Linux] Open in Browse: Unable to open external web browser

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#1174] opened 2017-10-26 03:10 UTC
Linux: Ubuntu 16.04.3 LTS
Linux ubuntu desktop: xfce
Default Browser : Firefox

**[Eclipse]**

1. Refresh a docker host in Azure Explorer 
2. Right click the container for this host  and choose browse

![image](https://user-images.githubusercontent.com/28860891/32032805-8e7b0f12-ba3b-11e7-93f9-39912469f4f5.png)

**[Intellij]**
Right click a Redis Cache/Web App/Container Registries/docker container for a docker host in Azure Explorer and choose open in browse
![image](https://user-images.githubusercontent.com/28860891/32032809-93602986-ba3b-11e7-9ef6-c0cf0128d577.png)
![image](https://user-images.githubusercontent.com/28860891/32033170-95775404-ba3d-11e7-9fd9-bf2e4915ec72.png)

**Comment by Eskibear** [comment] 2017-10-26 08:57
what's your eclipse version? @sallyur

**Comment by Eskibear** [comment] 2017-10-26 09:18
![image](https://user-images.githubusercontent.com/2351748/32044608-9fa3f602-ba70-11e7-8dd3-4bcbb276f37c.png)
```
Ubuntu: 16.04.1
Xfce: 4.12
Default browser: Firefox
Eclipse Neon.3 Release (4.6.3)
Plugin version: latest develop build #471
```


cannot reproduce.

**Comment by Eskibear** [comment] 2017-10-26 09:24
![image](https://user-images.githubusercontent.com/2351748/32045233-548e21fe-ba72-11e7-86f4-ad87c187bb32.png)

```
Ubuntu: 16.04.1
Xfce: 4.12
Default browser: Firefox
IntelliJ: Ultimate 2017.1.3
Plugin version: v3.0.10
```

Same in IntelliJ

**Comment by sallyur** [comment] 2017-10-26 09:34
My eclipse version is Neon.3 Release (4.6.3).
![image](https://user-images.githubusercontent.com/28860891/32045711-87e21d3e-ba73-11e7-97b6-1e9c07b2d028.png)

**Comment by Eskibear** [comment] 2017-11-01 09:05
I still cannot reproduce it. With a newly-installed Ubuntu, it also works well.
I suppose you might miss some packages or settings of your system.
You might refer to https://wiki.archlinux.org/index.php/default_applications for some information.

**Comment by bsaby** [comment] 2017-11-02 05:11
The root cause is environment-related and this issue can not be reproduced in the root user. So close it.

**Closed by bsaby** 2017-11-02 05:11 UTC
Labels: Eclipse, IntelliJ, notreproduce
