### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by kwerber** [microsoft/azure-tools-for-java#7393] opened 2023-03-15 15:42 UTC
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.74.1-2022.3
Additional Info: switching from one project to another
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x912,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:37
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-03-20 01:37 UTC
