### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure

### ISSUE THREAD

**Issue by spirosvar** [microsoft/azure-tools-for-java#8177] opened 2024-02-21 16:37 UTC
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.82.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:102)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:45)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
Caused by: reactor.core.Exceptions$ReactiveException: java.la

**Comment by wangmingliang-ms** [comment] 2024-03-01 06:31
Duplicate of #8108

**Closed as completed by wangmingliang-ms** 2024-03-01 06:31 UTC
