### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot create class com.microsoft.azure.toolkit.intellij.connector.code.spring.YamlCompletionContributor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\azure-toolkit-for-intellij, version=3.83.0-2021.3, package=null, isBundled=false), packagePrefix=null, instanceId=120, state=active))

### ISSUE THREAD

**Issue by afsiku01** [microsoft/azure-tools-for-java#8065] opened 2023-12-14 15:04 UTC
IntelliJ build version: 2021.3.2 IC-213.6777.52
OS: Windows 11
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.83.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1920x1009,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot create class com.microsoft.azure.toolkit.intellij.connector.code.spring.YamlCompletionContributor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, descriptorPath=plugin.xml, path=~<REDACTED: user-file-path>, version=3.83.0-2021.3, package

**Comment by Flanker32** [comment] 2024-01-29 08:49
@afsiku01 Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8079. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 08:49
Duplicate of #8079

**Closed as completed by Flanker32** 2024-01-29 08:49 UTC
