### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by Premchand-Mannam** [microsoft/azure-tools-for-java#8064] opened 2023-12-14 01:34 UTC
IntelliJ build version: 2023.3 IC-233.11799.241
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.net.SocketException: Connection reset
Caused by: java.net.SocketException: Connection reset
```

**Comment by Flanker32** [comment] 2024-01-29 08:39
@Premchand14 Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8086. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 08:39
Duplicate of #8086

**Closed as completed by Flanker32** 2024-01-29 08:39 UTC
