### ISSUE TITLE
[Intellij][Spark on ADL] The containers number does not update right now

### ISSUE THREAD

**Issue by liyanp1987** [microsoft/azure-tools-for-java#1738] opened 2018-06-25 03:13 UTC
**Repro bits**
https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/1678/Azure/ 

**Repro Steps**
1. Create a new Provision cluster with **2** containers
2. Right click it and choose Update item
3. Change the containers number to **4** and Click OK
4. Choose view cluster status on context menu

**Actual result**
The containers number does not update, until wait a moment, it can be changed

 **Screenshot**
![image](https://user-images.githubusercontent.com/37991481/41828577-9c6aebd8-7868-11e8-8eaa-695f5fd41ff8.png)

**Comment by t-rufang** [comment] 2020-06-19 09:57
It usually takes a while until the scale up operation succeeds. Close this issue since it's by design.

**Closed by t-rufang** 2020-06-19 09:57 UTC
Labels: HDInsight, IntelliJ, Internal Test, wontfix
