### ISSUE TITLE
Container Workflow - looks like success, but unexpected param values error

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#141] opened 2017-02-17 20:42 UTC
![image](https://cloud.githubusercontent.com/assets/3642444/23082424/1845d4aa-f50e-11e6-9696-aeb67d66415e.png)

**Comment by selvasingh** [comment] 2017-02-17 20:51
For this scenario, I completed the workflow. It successfully created everything

**Comment by milismsft** [comment] 2017-02-24 19:20
should be fixed in the latest version. The error was caused by failing to create the corresponding Key Vault.

**Comment by bsaby** [comment] 2017-02-27 09:30
Not repro in azure-toolkit-for-intellij.215.zip

**Closed by bsaby** 2017-02-27 09:30 UTC
Labels: bug-bash, IntelliJ
