### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    [Correlation ID: 73ccf34b-314c-4d36-84b7-bb933f46d83c] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.

### ISSUE THREAD

**Issue by alokkulkarni** [microsoft/azure-tools-for-java#7828] opened 2023-09-02 11:37 UTC
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1829x1285,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   [Correlation ID: 73ccf34b-314c-4d36-84b7-bb933f46d83c] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
   com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:39)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:111)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenReq

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:08
Duplicate of #7827

**Closed as completed by wangmingliang-ms** 2023-09-08 06:08 UTC
