### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by kingofsan** [microsoft/azure-tools-for-java#6156] opened 2021-12-01 10:46 UTC
IntelliJ build version: 2021.3 IC-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1278x1347,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.azure.toolkit.lib.common.utils.TailingDebouncer.debounce(TailingDebouncer.java:28)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:169)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.lambda$setItems$5(AzureComboBox.java:208)
	at com.microsoft.azure.toolkit.intellij.connector.ModuleConnectorAction.actionPerformed(ModuleConnectorAction.java:23)
```

**Comment by Flanker32** [comment] 2021-12-01 15:17
@kingofsan Thanks for your report, could you please help share the step to reproduce the issue? And could this issue be stable reproduced?

**Comment by Flanker32** [comment] 2021-12-21 13:55
@kingofsan Thanks for your report, the issue should be fixed in https://github.com/microsoft/azure-maven-plugins/pull/1858/files, we will release the fix in the next intellij toolkit release

**Comment by Flanker32** [comment] 2021-12-21 13:55
Tracking the issue in https://github.com/microsoft/azure-tools-for-java/issues/6195

**Closed as completed by Flanker32** 2021-12-21 13:55 UTC
Labels: Tool: IntelliJ, P2

**Comment by wangmingliang-ms** [comment] 2021-12-28 02:57
Duplicate of #6195
