### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.

### ISSUE THREAD

**Issue by felipeflorencio** [microsoft/azure-tools-for-java#8446] opened 2024-06-14 08:42 UTC
IntelliJ build version: 2023.1.6 IC-231.9414.13
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.82.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1981x1415,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
Caused by: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
```

**Comment by wangmingliang-ms** [comment] 2024-09-03 05:44
Duplicate of #8134

**Closed as completed by wangmingliang-ms** 2024-09-03 05:44 UTC
