### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by nextjedi** [microsoft/azure-tools-for-java#7811] opened 2023-08-30 05:23 UTC
IntelliJ build version: 2023.2.1 IC-232.9559.62
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Scheduler worker in group main failed with an uncaught exception
   reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$streamingLogs$0(StreamingLogSupport.java:58)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https:/<REDACTED: user-file-path>?follow=true&tailLines=300&tenantId=029494fa-4e02-4b01-b06f-65e9c72efbcd&tailLines=300&limitBytes=1048576&sinceSeconds=300&follow=true
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$streamingLogs

**Comment by wangmingliang-ms** [comment] 2023-09-19 02:28
Duplicate of #7742

**Closed as completed by wangmingliang-ms** 2023-09-19 02:28 UTC
