### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null

### ISSUE THREAD

**Issue by antonikozielewski-tomtom** [microsoft/azure-tools-for-java#7521] opened 2023-05-09 10:03 UTC
IntelliJ build version: 2022.2.4 IU-222.4459.24
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.75.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,2546x1402,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.editor.Editor.getDocument()" because "editor" is null
	at org.wso2.lsp4intellij.actions.LSPGotoDeclarationAction.actionPerformed(LSPGotoDeclarationAction.java:31)
```

**Comment by wangmingliang-ms** [comment] 2023-05-09 14:16
Duplicate of #7387

**Closed as completed by wangmingliang-ms** 2023-05-09 14:16 UTC
