### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by hildo** [microsoft/azure-tools-for-java#6844] opened 2022-08-11 21:03 UTC
IntelliJ build version: 2022.2 IU-222.3345.118
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1067x774,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2022-09-23 06:48
Hi, @hildo , thanks for reporting. can you tell us how to reproduce this error? This error has been reported several times, but we don't know how to reproduce it, making us unable to fix it immediately.

**Comment by hildo** [comment] 2022-09-24 02:25
I would have to recall.  If memory serves, all I was doing was starting IntelliJ.  But I don't know if I've seen this recently.  I'll check again during the week and see if I can provide more information.

**Comment by wangmingliang-ms** [comment] 2022-09-26 02:57
@hildo thank you so much.

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:59
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-03-20 01:59 UTC
Labels: Type: Bug, Reason: not reproduceable, need more info, State: Resolved
