### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: parent is null

### ISSUE THREAD

**Issue by TobiasAndersen98** [microsoft/azure-tools-for-java#6293] opened 2022-01-03 20:24 UTC
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.59.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,958x1039,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl:WHITE_SPACE
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConf

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:16
Duplicate of #5762

**Closed as completed by wangmingliang-ms** 2022-05-13 02:16 UTC
Labels: Module: HDInsight
