### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: containing file is null; hierarchy=class com.intellij.sql.psi.impl.SqlReferenceExpressionImpl, context=null, contextFile=null

### ISSUE THREAD

**Issue by tnais** [microsoft/azure-tools-for-java#6611] opened 2022-05-05 15:52 UTC
IntelliJ build version: 2021.3.2 IU-213.6777.52
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.62.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,25,1243x677,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl #  because: containing file is null; hierarchy=class com.intellij.sql.psi.impl.SqlReferenceExpressionImpl, context=null, contextFile=null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl:WHITE_SPACE / com.intellij.sql.psi.impl.SqlReferenceExpressionImpl:SQL_TAB

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:12
Duplicate of #5762

**Closed as completed by wangmingliang-ms** 2022-05-13 02:12 UTC
Labels: Module: HDInsight
