### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    [56839420, L:/192.168.3.96:49242 - R:nm4platform.blob.core.windows.net/20.150.37.228:443] Error was received while reading the incoming data. The connection will be closed.

### ISSUE THREAD

**Issue by maravelias** [microsoft/azure-tools-for-java#7897] opened 2023-09-29 10:18 UTC
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Linux
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1080,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   [56839420, L:/192.168.3.96:49242 - R:<REDACTED: user-file-path>:443] Error was received while reading the incoming data. The connection will be closed.
   java.lang.LinkageError: Package versions: jackson-core=2.13.4, jackson-databind=2.13.4-2, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.42.0, Troubleshooting version conflicts: https:/<REDACTED: user-file-path>
<REDACTED: Generic Secret>
```

**Comment by Flanker32** [comment] 2023-10-07 05:44
@maravelias Thank you for reporting this issue and sorry for the delay in getting back to you. Based on the error stack, it seems that the issue is related to a network connection problem. To help us investigate this further, could you please provide some additional information, such as the steps to reproduce this issue?

**Comment by AssasinCross** [comment] 2023-10-07 06:26
@Flanker32, I have the same issue with this during the deployment of Azure-Function.

```
Functions extension version isn't configured, setting up the default value.
Start updating Function App(azure-function)...
Function App(azure-function) is successfully updated
Starting deployment...
Trying to deploy artifact to azure-function...
```

Deploying the artifact into Azure Function will always result "Error was received while reading the incoming data. The connection will be closed."

**Comment by Flanker32** [comment] 2023-10-07 07:03
> @Flanker32, I have the same issue with this during the deployment of Azure-Function.
> 
> ```
> Functions extension version isn't configured, setting up the default value.
> Start updating Function App(azure-function)...
> Function App(azure-function) is successfully updated
> Starting deployment...
> Trying to deploy artifact to azure-function...
> ```
> 
> Deploying the artifact into Azure Function will always result "Error was received while reading the incoming data. The connection will be closed."

@AssasinCross Thanks for your report, could you please help share the toolkit version as well as the runtime info for the Function App? Besides, could you please try create a new function app and try whether this issue could be reproduced on a new function app?

**Comment by AssasinCross** [comment] 2023-10-07 07:16
> > @Flanker32, I have the same issue with this during the deployment of Azure-Function.
> > ```
> > Functions extension version isn't configured, setting up the default value.
> > Start updating Function App(azure-function)...
> > Function App(azure-function) is successfully updated
> > Starting deployment...
> > Trying to deploy artifact to azure-function...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Deploying the artifact into Azure Function will always result "Error was received while reading the incoming data. The connection will be closed."
> 
> @AssasinCross Thanks for your report, could you please help share the toolkit version as well as the runtime info for the Function App? Besides, could you please try create a new function app and try whether this issue could be reproduced on a new function app?

@Flanker32 The same issue still happening on the new function app.

Azure Toolkit Version: 3.81.0-2023.2

Azure Function Runtime:

- OS: Linux
- Java version: 8
- Extension Version: ~4

**Comment by Flanker32** [comment] 2023-10-07 07:42
> > > @Flanker32, I have the same issue with this during the deployment of Azure-Function.
> > > ```
> > > Functions extension version isn't configured, setting up the default value.
> > > Start updating Function App(azure-function)...
> > > Function App(azure-function) is successfully updated
> > > Starting deployment...
> > > Trying to deploy artifact to azure-function...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Deploying the artifact into Azure Function will always result "Error was received while reading the incoming data. The connection will be closed."
> > 
> > 
> > @AssasinCross Thanks for your report, could you please help share the toolkit version as well as the runtime info for the Function App? Besides, could you please try create a new function app and try whether this issue could be reproduced on a new function app?
> 
> @Flanker32 The same issue still happening on the new function app.
> 
> Azure Toolkit Version: 3.81.0-2023.2
> 
> Azure Function Runtime:
> 
> * OS: Linux
> * Java version: 8
> * Extension Version: ~4

Got it, thanks a lot for your report, we will fix this issue asap, will update here once we get any updates

**Comment by AssasinCross** [comment] 2023-10-07 07:52
> > > > @Flanker32, I have the same issue with this during the deployment of Azure-Function.
> > > > ```
> > > > Functions extension version isn't configured, setting up the default value.
> > > > Start updating Function App(azure-function)...
> > > > Function App(azure-function) is successfully updated
> > > > Starting deployment...
> > > > Trying to deploy artifact to azure-function...
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Deploying the artifact into Azure Function will always result "Error was received while reading the incoming data. The connection will be closed."
> > > 
> > > 
> > > @AssasinCross Thanks for your report, could you please help share the toolkit version as well as the runtime info for the Function App? Besides, could you please try create a new function app and try whether this issue could be reproduced on a new function app?
> > 
> > 
> > @Flanker32 The same issue still happening on the new function app.
> > Azure Toolkit Version: 3.81.0-2023.2
> > Azure Function Runtime:
> > 
> > * OS: Linux
> > * Java version: 8
> > * Extension Version: ~4
> 
> Got it, thanks a lot for your report, we will fix this issue asap, will update here once we get any updates

I can confirm this problem after double-checking with deployment via maven plugin.
Maven plugin one ends up success without any problem.

**Comment by Flanker32** [comment] 2023-10-08 05:49
@maravelias @AssasinCross Thank you for your valuable feedback that helped us identify and fix this issue. We have released the fix for this issue, and we would appreciate it if you could upgrade toolkit to v3.81.1 and try again.

**Comment by AssasinCross** [comment] 2023-10-08 05:55
> @maravelias @AssasinCross Thank you for your valuable feedback that helped us identify and fix this issue. We have released the fix for this issue, and we would appreciate it if you could upgrade toolkit to v3.81.1 and try again.

Updated and tested it on my machine.

Deployment to Azure Function using the plugin now works without Connection Closed issue

**Comment by Flanker32** [comment] 2023-10-08 05:59
@AssasinCross Got it, thank you very much for your assistance! I’ll close the issue for now, but please feel free to open it if you encounter this issue again. Thanks again for your support! Have a nice day!

**Comment by maravelias** [comment] 2023-10-09 10:16
@Flanker32  Thank you , i have update the plugin and now all works perfectly . I am able now to manage again the azure blob storages from IntelliJ

**Comment by Flanker32** [comment] 2023-10-10 02:39
@maravelias Glad to see the fix helps, and thanks again for your support!

**Closed as completed by Flanker32** 2023-10-10 02:39 UTC
Labels: Tool: IntelliJ, Reason: fixed
