### ISSUE TITLE
[IntelliJ] Uncaught Exception  java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder <clinit> requests com.microsoft.azure.toolkit.lib.common.messager.IAzureMessager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

### ISSUE THREAD

**Issue by bigdata4u** [microsoft/azure-tools-for-java#8475] opened 2024-07-13 08:53 UTC
IntelliJ build version: 2024.2 Beta IU-242.20224.38
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.90.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder <clinit> requests com.microsoft.azure.toolkit.lib.common.messager.IAzureMessager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager$Provider.getMessager(IntellijAzureMessager.java:172)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder.loadMessager(AzureMessager.java:30)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder.

**Comment by wangmingliang-ms** [comment] 2024-07-18 07:36
Duplicate of #8473

**Closed as completed by wangmingliang-ms** 2024-07-18 07:36 UTC
