### ISSUE TITLE
[IntelliJ]Chinese in the subscription name can not be displayed on Windows English system

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1225] opened 2017-11-06 02:09 UTC
Mooncake subscprition
Windows English system:
![image](https://user-images.githubusercontent.com/22470312/32422243-3cf3072e-c2da-11e7-9c0f-36762e8c7362.png)
Windows Chinese system:
![image](https://user-images.githubusercontent.com/22470312/32422245-3ec99a86-c2da-11e7-9e59-28834ff14c0a.png)

**Comment by jdneo** [comment] 2017-11-06 05:23
Coding Issue, seems duplicated with #394

**Comment by Eskibear** [comment] 2017-11-06 05:59
I suppose it's caused by missing Chinese fonts in the system. Please help to verify if it can show Chinese characters after installing Chinese language pack in the Windows system. If so, I don't think it should be our issue.

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738790

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: IntelliJ, Internal Test, P3, UI, bug, transfter
