### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by imranamans** [microsoft/azure-tools-for-java#7508] opened 2023-05-02 14:56 UTC
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationExceptionhttps://docs.github.com/en/early-access/issues/about-tasklists
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
```

**Comment by Flanker32** [comment] 2023-07-31 08:47
@imranamans Thanks for your report and sorry for the late response. Please track this issue in #7703

Duplicate of #7703

**Closed as completed by Flanker32** 2023-07-31 08:47 UTC
