### ISSUE TITLE
[IntelliJ] Docker host node can not be refreshed automatically after publish successfully.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#287] opened 2017-04-07 09:50 UTC
After publish successfully,  Docker host node doesn't refresh in Azure explorer.

**Comment by milismsft** [comment] 2017-04-07 17:08
This bug is a duplicate of #139. The Azure Explorer does not currently refresh the nodes to reflect new items created or removed via the publishing wizards.

**Closed by milismsft** 2017-04-07 17:08 UTC
