### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: User data is not supported; editorClass='com.microsoft.azure.toolkit.intellij.redis.explorer.RedisCacheExplorer'; key='editor.notification.provider' [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by kabirbansur** [microsoft/azure-tools-for-java#6554] opened 2022-04-16 08:29 UTC
IntelliJ build version: 2022.1 IU-221.5080.210
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1601x860,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: User data is not supported; editorClass='com.microsoft.azure.toolkit.intellij.redis.explorer.RedisCacheExplorer'; key='editor.notification.provider' [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
```

**Comment by wangmingliang-ms** [comment] 2022-04-19 04:30
Duplicate of #6550

**Closed as completed by wangmingliang-ms** 2022-04-19 04:30 UTC
