### ISSUE TITLE
The error message should be more specific

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1235] opened 2017-11-06 09:00 UTC
IntelliJ: Web app and Web app for containers
Eclipse: Web app for Containers

Create a resource group with an existing name when creating a new app service, error message shown as below:
![image](https://user-images.githubusercontent.com/22470312/32432810-dbb18a28-c313-11e7-84d3-139362293032.png)

![image](https://user-images.githubusercontent.com/22470312/32432801-d4e3050a-c313-11e7-9aa3-125d26c23fb2.png)

**Comment by ZhengJun003** [comment] 2020-06-15 02:24
Can reproduce this issue in azure toolkits for IntelliJ 3.37.0 and azure toolkits for Eclipse 3.23.0

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738803

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, IntelliJ, Internal Test, P3, app-service, bug, error-handling, transfter
