### ISSUE TITLE
[Enhancement]The deployed web app list should be sorted alphabetically

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2778] opened 2019-02-27 09:34 UTC
### Environment
1. OS: All
2. IDE: Eclipse IDE for Enterprise Java Developers 2018-12
3. JDK: 1.8.0_191
4. Build: 994

### Steps:
1. Make sure at least two subscriptions are selected
1. Right click project and select Azure -> publish as Azure web app

### Result:
This list sorts a bit confusing
![image](https://user-images.githubusercontent.com/28860891/53480320-eeb76a00-3ab5-11e9-8d64-f32884a40f7b.png)

**Comment by zmssp** [comment] 2019-03-06 01:34
Please verify, it should be fixed

**Comment by bsaby** [comment] 2019-03-06 11:28
The App service with uppercase letters are in front of apps with lowercase letters, expected?
![image](https://user-images.githubusercontent.com/22470312/53877648-b3ccad80-4044-11e9-816e-3abd4497b002.png)
The behavior is different from azure explorer, because I find that the order of web apps in azure explorer like below;
![image](https://user-images.githubusercontent.com/22470312/53877995-a82db680-4045-11e9-82de-10aa56dd0a77.png)

**Comment by ZhengJun003** [comment] 2020-06-16 07:54
Can reproduce this issue in azure toolkits for eclipse 3.23.0

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738756

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: Eclipse, Internal Test, P3, app-service, enhancement, transfter
