### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by allonli** [microsoft/azure-tools-for-java#7783] opened 2023-08-16 09:56 UTC
IntelliJ build version: 2023.2 IU-232.8660.185
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.79.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1120,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Scheduler worker in group main failed with an uncaught exception
  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:47)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:259)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.doGetById(AbstractAzService.java:110)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.getById(AbstractAzService.java:102)
at com.microsoft.azure.toolkit.intellij.springcloud.deplol

**Comment by wangmingliang-ms** [comment] 2024-09-03 05:42
Duplicate of #7742

**Closed as completed by wangmingliang-ms** 2024-09-03 05:42 UTC
