### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED

### ISSUE THREAD

**Issue by jpreber** [microsoft/azure-tools-for-java#7684] opened 2023-07-13 19:08 UTC
IntelliJ build version: 2023.2 Beta IU-232.8660.48
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x875,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1
	at com.microsoft.azure.toolkit.intellij.cosmos.dbtools.DbToolsWorkaround.loadCassandraDriver(DbToolsWorkaround.java:65)
	at com.microsoft.azure.toolkit.intellij.cosmos.dbtools.DbToolsWorkaround.lambda$preload$0(DbToolsWorkaround.java:43)
```

**Comment by Flanker32** [comment] 2023-07-31 05:05
Duplicate of #7733

**Closed as completed by Flanker32** 2023-07-31 05:05 UTC
