### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.arm.template.ResourceTemplateViewProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by allanlaal** [microsoft/azure-tools-for-java#8149] opened 2024-02-09 07:31 UTC
IntelliJ build version: 2023.3.3 IU-233.14015.106
OS: Linux
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.85.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,36,3805x1935,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.arm.template.ResourceTemplateViewProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:111)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

**Comment by wangmingliang-ms** [comment] 2024-02-18 02:19
Duplicate of #8143

**Closed as completed by wangmingliang-ms** 2024-02-18 02:19 UTC
