### ISSUE TITLE
Error occured while refreshing subscriptions

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#364] opened 2017-05-02 07:53 UTC
Version:
IntelliJ2017.1.2  and Eclipse.Neon.3
Builds used:
artifacts/azure-toolkit-for-intellij.2017.405.05-01-2017.zip.
artifacts/WindowsAzurePlugin4EJ.410.05-01-2017.zip.

Repro steps:
Open Eclipse/IntelliJ
Sign in Azure (Both Interactive and Automated can be reproduced)
Right click **Azure** and choose **Refresh**
After refresh, right click **Azure** and choose **Select Subscriptions**
Refresh subscriptions in the subscriptions dialog

Eclipse
![image](https://cloud.githubusercontent.com/assets/22470312/25608091/1f6496b8-2f4c-11e7-905a-b8685ed02895.png)
IntelliJ
![image](https://cloud.githubusercontent.com/assets/22470312/25608528/c8e7446e-2f4d-11e7-9c17-ffa2816159dc.png)

**Comment by milismsft** [comment] 2017-05-02 15:34
The issue is caused by the user changing the subscription while the Azure Explorer was still refreshing its nodes. There's little we can do about this at the moment since it requires some extensive changes to how we handle sign out/subscription change events down the stream.

**Comment by martinsawicki** [comment] 2017-05-02 19:36
yeah, i'm not sure this is worth doing anything about

**Comment by ZhengJun003** [comment] 2020-06-15 02:00
Can reproduce in azure toolkits for IntelliJ 3.37.0 and azure toolkits for eclipse 3.23.0

Eclipse:
![image](https://user-images.githubusercontent.com/41051257/84610955-f8552300-aeee-11ea-9011-2bfd56d33ff5.png)

IntelliJ:
![image](https://user-images.githubusercontent.com/41051257/84610066-f2aa0e00-aeeb-11ea-8bb6-e554136f3440.png)
![image](https://user-images.githubusercontent.com/41051257/84610761-59302b80-aeee-11ea-895f-239e5333d837.png)
![image](https://user-images.githubusercontent.com/41051257/84610771-5df4df80-aeee-11ea-809d-32651277ab3b.png)
![image](https://user-images.githubusercontent.com/41051257/84610789-736a0980-aeee-11ea-84d1-eec98aa6b8f5.png)

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738804

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, IntelliJ, Internal Test, auth, bug, transfter
