### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null

### ISSUE THREAD

**Issue by ultra101** [microsoft/azure-tools-for-java#7264] opened 2023-01-31 15:23 UTC
IntelliJ build version: 2022.3.1 IC-223.8214.52
OS: Linux
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.72.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,1,30,3440x1369,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
```

**Comment by wangmingliang-ms** [comment] 2023-02-01 01:14
Duplicate of #7248

**Closed as completed by wangmingliang-ms** 2023-02-01 01:14 UTC
