### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-superhero-sighting-full325089235)

### ISSUE THREAD

**Issue by StevenGinsberg** [microsoft/azure-tools-for-java#7093] opened 2022-11-13 05:32 UTC
IntelliJ build version: 2022.1.3 IU-221.5921.22
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.70.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x835,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@2ee2de8,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-superhero-sighting-full325089235)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:489)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:215)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getOrDraft(AbstractAzResourceModule.java:273)
	at com.microsoft.azure.toolkit.lib.appservice.config.AppServicePlanConfig.toResource(AppServicePl

**Comment by wangmingliang-ms** [comment] 2022-11-15 05:40
Duplicate of #7028

**Closed as completed by wangmingliang-ms** 2022-11-15 05:40 UTC
