### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)

### ISSUE THREAD

**Issue by mary-alexander** [microsoft/azure-tools-for-java#8058] opened 2023-12-08 16:02 UTC
IntelliJ build version: 2023.3 RC IU-233.11799.196
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1244x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler$1.processWillTerminate(RunProcessHandler.java:88)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.onFail(AzureRunProfileState.java:109)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.onFail(FunctionRunState.java:451)
	at com.microsoft.a

**Comment by Flanker32** [comment] 2024-01-29 07:56
@mary-alexander Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8100. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:56
Duplicate of #8100

**Closed as completed by Flanker32** 2024-01-29 07:56 UTC
