### ISSUE TITLE
Click a multiple times to create the same network name

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#3893] opened 2020-01-02 10:11 UTC
#### Environment:

- OS: Windows10
- Plugin version
  - Azure java toolkit for IntelliJ: 3.31.0
  - Azure java toolkit for Eclipse: 3.21.0
- IDE version
  - IntelliJ: IU19.2.4-jre11
  - Eclipse: 2019-12

#### Repro steps:
1. Right click Virtual Machines to create a new VM
2. When you click <<Create new>>, it will create a new network
3. Click <<Create new>> again, It will create a network with the same name.
#### Result:
![image](https://user-images.githubusercontent.com/44559777/71661897-9ebacb00-2d8a-11ea-96d4-5d41b9a0caf8.png)

**Comment by Flanker32** [comment] 2020-01-20 06:36
Caused by the new virtual network dialog add new virtual network item to checkbox directly without validation, will fix this issue in next release

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738760

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: Eclipse, IntelliJ, Internal Test, P3, VM, known-issue, transfter
