### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by GHzOliveira** [microsoft/azure-tools-for-java#6942] opened 2022-09-19 15:32 UTC
IntelliJ build version: 2022.2.2 IU-222.4167.29
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.4
Plugin version: 3.68.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x681,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2022-09-23 08:27
duplicate of #6844

**Comment by wangmingliang-ms** [comment] 2022-09-23 08:27
Hi, @GHzOliveira , thanks for reporting. can you tell us how to reproduce this error? This error has been reported several times, but we don't know how to reproduce it, making us unable to fix it immediately.

**Closed as completed by wangmingliang-ms** 2022-09-23 08:27 UTC
