### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=backend, containerState=COMPONENT_CREATED, componentStore=C:\Users\romul\IdeaProjects\backend))

### ISSUE THREAD

**Issue by Romulo-S** [microsoft/azure-tools-for-java#5899] opened 2021-10-02 00:19 UTC
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.57.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2049x824,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=backend, containerState=COMPONENT_CREATED, componentStore=C:\Users\romul\IdeaProjects\CNJ\backend))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfiguration.java:103)
```

**Comment by wangmingliang-ms** [comment] 2021-10-03 14:29
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-03 14:29 UTC
