### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by Abbcinto** [microsoft/azure-tools-for-java#5638] opened 2021-08-02 17:44 UTC
IntelliJ build version: 2021.1.3 IC-211.7628.21
OS: Windows 7
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,8,30,1366x690,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=AplicativoWeb, containerState=DISPOSE_COMPLETED, componentStore=C:\ProjetoJava\AplicativoWeb) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=AplicativoWeb, containerState=DISPOSE_COMPLETED, componentStore=C:\ProjetoJava\AplicativoWeb) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.azure.toolkit.intellij.azuresdk.enforcer.AzureSdkEnforcer.enforce(AzureSdkEnforcer.java:39)

**Comment by shenqianjin** [comment] 2021-08-05 08:30
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/5444

**Closed by shenqianjin** 2021-08-05 08:30 UTC
Labels: duplicate
