### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.common.feedback.MonkeySurveyEditorProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by amel967** [microsoft/azure-tools-for-java#8387] opened 2024-04-23 10:55 UTC
IntelliJ build version: 2023.3.4 IC-233.14475.28
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.common.feedback.MonkeySurveyEditorProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:111)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

**Comment by amel967** [comment] 2024-04-23 10:56
comment éviter cette erreur ?

**Comment by wangmingliang-ms** [comment] 2024-05-17 01:47
seems this kind of error is becoming common in new versions of IntelliJ IDEA, we'll investigate what's changed. Thanks for reporting this to us.
does this error block any operation? (this helps prioritizing)

**Comment by wangmingliang-ms** [comment] 2024-11-06 03:01
Duplicate of #8143

**Closed as completed by wangmingliang-ms** 2024-11-06 03:01 UTC
