### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback - blank Azure login page

### ISSUE THREAD

**Issue by ravikoppar** [Microsoft/azure-tools-for-java#1839] opened 2018-07-27 04:58 UTC
IntelliJ build version: 2018.2 IC-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).

# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
After installing Azure Toolkit Plugin, When I click on interactive login, I am getting blank popup screen, hence I am not able to login.

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?

**Comment by ravikoppar** [comment] 2018-07-27 05:00
![azuretoolkitissue](https://user-images.githubusercontent.com/41771168/43302419-0e7e7aae-9188-11e8-895b-42d55b36cf99.jpg)

**Comment by wezhang** [comment] 2018-08-07 06:40
@Eskibear , have you hit this issue?

**Comment by Eskibear** [comment] 2018-08-07 07:04
@wezhang No I cannot reproduce. Since it's only a dialog opening the login url, can it be network issue? 
@ravikoppar Are you able to open Microsoft login page in your browser? e.g. This one https://login.microsoftonline.com/login.srf

**Comment by wezhang** [comment] 2018-09-10 05:45
Can be fixed with #1877

**Closed by wezhang** 2018-09-10 05:45 UTC
Labels: Feedback, IntelliJ, bug, need more info
