### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Must be precomputed

### ISSUE THREAD

**Issue by jorge-barroso** [microsoft/azure-tools-for-java#7686] opened 2023-07-14 11:04 UTC
IntelliJ build version: 2023.2 Beta IU-232.8660.48
OS: Linux
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1713x1396,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Must be precomputed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.microsoft.azure.toolkit.intellij.database.dbtools.DatabaseDbToolsWorkaround.loadMySqlAzureTemplates(DatabaseDbToolsWorkaround.java:30)
	at com.microsoft.azure.toolkit.intellij.database.dbtools.DatabaseDbToolsWorkaround.lambda$preload$0(DatabaseDbToolsWorkaround.java:22)
```

**Comment by Flanker32** [comment] 2023-07-31 05:11
@jorge-barroso  Thanks for your report and sorry for the trouble, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7732

Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7732

**Closed as completed by Flanker32** 2023-07-31 05:11 UTC
