### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by HenrikWL** [microsoft/azure-tools-for-java#6877] opened 2022-08-24 11:20 UTC
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1537x825,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2022-09-01 01:29
Duplicate of #6844

**Closed as completed by wangmingliang-ms** 2022-09-01 01:29 UTC

**Comment by wangmingliang-ms** [comment] 2022-09-23 06:47
Hi, @HenrikWL , thanks for reporting. can you tell us how to reproduce this error? This error has been reported several times, but we don't know how to reproduce it, making us unable to fix it immediately.

**Comment by HenrikWL** [comment] 2022-09-23 15:43
I don’t know how to reproduce it accurately, but when it happened I was using remote development, with the server running in WSL2 and the client running on Windows 10. My guess is that the error is somehow related to the separation of client GUI and server.
