### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@200698e4 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@54bd3715

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#7955] opened 2023-10-25 06:49 UTC
IntelliJ build version: 2023.2.3 IU-232.10072.27
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.81.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2497x1415,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@200698e4 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@54bd3715
<REDACTED: Generic Secret>
at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<R

**Comment by Flanker32** [comment] 2023-12-06 12:38
@prshnt Thanks for your report and sorry for the late response, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/8009

**Comment by Flanker32** [comment] 2023-12-06 12:38
Duplicate of #8009

**Closed as completed by Flanker32** 2023-12-06 12:38 UTC
