### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: 0 : child= 'FilePartNode: 'DDl'; children: 0; fs=LocalFileSystem; myFileOrUrl=file:///Users/huangzihao/IdeaProjects/ForDogProject/ForDog/fordog/SQL/DDl; class java.lang.String'; child.nameEqualTo(nameId)=false; child.getClass()=class com.intellij.openapi.vfs.impl.FilePartNode; child.nameId=12083989; child.getName()='DDl'; nameId=12083997; name='DDL'; compare(child) = 0; UrlPart.nameEquals: true; name.equals(child.getName())=false; file=file:///Users/huangzihao/IdeaProjects/ForDogProject/ForDog/fordog/SQL/DDL; this.isCaseSensitive()=false

### ISSUE THREAD

**Issue by jounace** [microsoft/azure-tools-for-java#8198] opened 2024-02-29 03:17 UTC
IntelliJ build version: 2023.3.4 IU-233.14475.28
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.85.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: 0 : child= 'FilePartNode: 'DDl'; children: 0; fs=LocalFileSystem; myFileOrUrl=<REDACTED: user-file-path>; class java.l

**Comment by wangmingliang-ms** [comment] 2024-03-01 06:29
Duplicate of #7463

**Closed as completed by wangmingliang-ms** 2024-03-01 06:29 UTC
