### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException

### ISSUE THREAD

**Issue by quanKM** [microsoft/azure-tools-for-java#6191] opened 2021-12-10 03:36 UTC
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.59.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException
	at com.intellij.packaging.elements.PackagingElement.update(PackagingElement.java:136)
	at com.microsoft.azure.hdinsight.projects.HDInsightModuleBuilder.lambda$moduleCreated$0(HDInsightModuleBuilder.java:136)
```

**Comment by fengshuaihu** [comment] 2022-12-29 05:44
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6478

**Closed as completed by fengshuaihu** 2022-12-29 05:44 UTC
Labels: Module: HDInsight
