### ISSUE TITLE
Open two identical web pages at the same time for docker conatiner

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2790] opened 2019-02-28 04:57 UTC
Can't stable repro.

### Environment:
* OS: Windows/Mac/Linux
* Eclipse: 2018-12 (4.10.0)
* Bits: dev995

### Steps:
1. Publish a war/jar package as a docker container
2. Click the published link after deployment

![image](https://user-images.githubusercontent.com/22470312/53542151-19f29580-3b58-11e9-880a-278d1128340b.png)

### Result:
Open two same web pages iat the same time.
![image](https://user-images.githubusercontent.com/22470312/53542155-1bbc5900-3b58-11e9-8deb-0cdd8cf2dc2c.png)

**Comment by ZhengJun003** [comment] 2020-06-15 09:33
According to this issue: #4353, can't reproduce this issue

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738775

**Comment by vscjavaci** [comment] 2020-06-23 12:27
Track internal issue by AB#1738816

**Comment by vscjavaci** [comment] 2020-07-02 01:10
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:10 UTC
Labels: Eclipse, Internal Test, P3, bug, docker-host, transfter
