### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null

### ISSUE THREAD

**Issue by bastiaan-los** [microsoft/azure-tools-for-java#6547] opened 2022-04-12 13:49 UTC
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@7b9ec81d,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl #JAVA  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiJavaTokenImpl:STRING_LITERAL
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdins

**Comment by wangmingliang-ms** [comment] 2022-05-13 02:06
Duplicate of #6338

**Closed as completed by wangmingliang-ms** 2022-05-13 02:06 UTC
Labels: Module: HDInsight
