### ISSUE TITLE
Storage account->An error occurred while loading suscriptions

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1169] opened 2017-10-25 05:41 UTC
Stable repro in automated browse login in method via .json or .azureauth file in Eclipse
Not Stable repro in interactive login method.

Right Click Storage Account node and choose create a storage account
![image](https://user-images.githubusercontent.com/22470312/31981518-6ed8edb0-b986-11e7-9aa8-360c35205876.png)

**Comment by adashen** [comment] 2017-10-25 06:26
@bsaby it should be a mooncake specific issue.
To reproduce
1. Login automatically with one auth file
2. create storage account action, no error
3. log out and login with another auth file
4. create storage account action, error shows up.

This should also be reproducable in old versions. Please verify it on old versions with global/mooncake account

**Comment by bsaby** [comment] 2017-10-25 06:47
Try the repro steps and find this issue also repro in v3.0.10 release version for both Global and Mooncake
And this issue repro in both Eclipse and IntelliJ.

**Global**: login with Interactive method and create a storage account and sign out , then sign in with sp file, create storage account, error occurred:

**Error log in IntelliJ**
null
java.lang.NullPointerException
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.loadGroups(CreateArmStorageAccountForm.java:463)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.fillRegions(CreateArmStorageAccountForm.java:458)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.loadRegions(CreateArmStorageAccountForm.java:450)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.fillFields(CreateArmStorageAccountForm.java:343)
	at com.microsoft.intellij.serviceexplorer.azure.storagearm.CreateStorageAccountAction.actionPerformed(CreateStorageAccountAction.java:50)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$0(ServerExplorerToolWindowFactory.java:163)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ZhengJun003** [comment] 2020-06-15 02:15
Can reproduce this issue in azure toolkits for IntelliJ 3.37.0 and azure toolkits for Eclipse 3.23.0

Eclipse:
![image](https://user-images.githubusercontent.com/41051257/84611464-87166f80-aef0-11ea-8ab2-2da52d345175.png)

IntelliJ:
![image](https://user-images.githubusercontent.com/41051257/84611655-0f951000-aef1-11ea-926b-d01ce2f8acc8.png)

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738791

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, IntelliJ, Internal Test, P2, StorageExplorer, auth, bug, transfter
