### ISSUE TITLE
[Enhancement]The web app properties list should be sorted alphabetically

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2781] opened 2019-02-27 10:05 UTC
### Environment
1. OS: All
2. IDE: Eclipse IDE for Enterprise Java Developers 2018-12
3. JDK: 1.8.0_191
4. Build: 994

### Actual Result:
Now the web app properties list displayed as below:
![image](https://user-images.githubusercontent.com/28860891/53482258-c7fb3280-3ab9-11e9-96fb-78321d3b0ab2.png)
### Expect result:
The web app properties list be sorted alphabetically like portal:
![image](https://user-images.githubusercontent.com/28860891/53482363-01cc3900-3aba-11e9-9c72-11e246be2801.png)

**Comment by ZhengJun003** [comment] 2020-06-16 07:54
Can reproduce this issue in azure toolkits for eclipse 3.23.0

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738771

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: Eclipse, Internal Test, P3, app-service, enhancement, transfter
