### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by MaxImusMDA** [microsoft/azure-tools-for-java#6929] opened 2022-09-12 12:47 UTC
IntelliJ build version: 2022.2.1 IC-222.3739.54
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.68.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2022-09-23 08:28
Hi, @MaxImusMDA , thanks for reporting. can you tell us how to reproduce this error? This error has been reported several times, but we don't know how to reproduce it, making us unable to fix it immediately.

**Comment by wangmingliang-ms** [comment] 2022-09-23 08:28
duplicate of #6844

**Closed as completed by wangmingliang-ms** 2022-09-23 08:28 UTC

**Comment by MaxImusMDA** [comment] 2022-09-23 13:18
Hello Miller,

Unfortunately i can not help you a lot, it happened when i was travelling
and switching wifi networks , so this might be the cause.
If i would find a precise way to reproduce i would gladly write back .

Regards

**Comment by wangmingliang-ms** [comment] 2022-09-26 01:52
@MaxImusMDA that should not be related to this error. thanks anyway for reporting this bug to us and adding these details. I would really appreciate it If you can add more details here if you find out how to reproduce later
