### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@7deb7ed5] - other than com.intellij.util.proxy.CommonProxy.ourInstance.

### ISSUE THREAD

**Issue by JurgitaZvinklieneMSM** [microsoft/azure-tools-for-java#4362] opened 2020-05-04 12:42 UTC
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.1-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@7deb7ed5] - other than com.intellij.util.proxy.CommonProxy.ourInstance.
This will make some IDEA network calls fail.
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:94)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:78)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at com.mi

**Comment by andxu** [comment] 2020-06-02 07:14
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  https://api.github.com/repos/microsoft/azure-tools-for-java/issues/2665

**Comment by andxu** [comment] 2020-06-02 07:15
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  https://github.com/microsoft/azure-tools-for-java/issues/2665

**Comment by andxu** [comment] 2020-06-02 07:15
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  https://github.com/microsoft/azure-tools-for-java/issues/2665

**Comment by andxu** [comment] 2020-06-02 07:23
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Excep... (#2665)

**Comment by andxu** [comment] 2020-06-02 07:23
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.Throwable: Pro... (#2665)

**Comment by andxu** [comment] 2020-06-02 07:55
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was ch... (#2665)

**Comment by vscjavaci** [comment] 2020-06-03 06:45
Close this issue due to duplicate error: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector

**Closed by vscjavaci** 2020-06-03 06:45 UTC
Labels: ReportedByUser, duplicate, stacktrace

**Comment by Flanker32** [comment] 2020-06-10 02:12
@ShingmoYeung Thanks a lot for your report and sorry for the late reply, could you please share a bit more infos like how this issue occurs and is there any way to reproduce it?
