### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by vkoryakin** [microsoft/azure-tools-for-java#7641] opened 2023-06-22 17:15 UTC
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x999,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2023-06-28 02:36
@vkoryakin Thanks a lot for your report, could you please some more info like is there any steps to reproduce this issue?

**Comment by wangmingliang-ms** [comment] 2023-08-08 00:07
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-08-08 00:07 UTC
Labels: Tool: IntelliJ, need more info
