### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.microsoft.azure.toolkit.lib.common.utils.InstallationIdUtils.getHashMac()" is null

### ISSUE THREAD

**Issue by junkert** [microsoft/azure-tools-for-java#7166] opened 2022-12-13 17:23 UTC
IntelliJ build version: 2022.2.3 IU-222.4345.14
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.71.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x1415,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@50739423,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.microsoft.azure.toolkit.lib.common.utils.InstallationIdUtils.getHashMac()" is null
	at com.microsoft.azure.toolkit.intellij.common.feedback.RateManager$WhenToPopup.runActivity(RateManager.java:114)
```

**Comment by wangmingliang-ms** [comment] 2022-12-16 14:41
Duplicate of #7155

**Closed as completed by wangmingliang-ms** 2022-12-16 14:41 UTC
