### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by rvervaek** [microsoft/azure-tools-for-java#5453] opened 2021-06-30 06:52 UTC
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.54.0-2021.1
Additional Info: 1. Open new project from version control and save in C:\Users\ruben.vervaeke\IdeaProjects\liantis3
2. Close IDEA
3. Move project files into new directory -> C:\Users\ruben.vervaeke\IdeaProjects\liantis3\my-calendar-service
4. Open IDEA and open new project directory
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=liantis3, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\ruben.vervaeke\IdeaProjects\liantis3) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=liantis3, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\ruben.vervaeke\IdeaProjects\liantis3) (disposed)
	at com.micro

**Comment by wangmingliang-ms** [comment] 2021-07-01 03:13
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-01 03:13 UTC
