### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=dct.CARTAPORTE.API, containerState=COMPONENT_CREATED, componentStore=C:\Users\EON-35\Documents\Danone\Backend\dct.CARTAPORTE.API))

### ISSUE THREAD

**Issue by egarciaeon** [microsoft/azure-tools-for-java#5895] opened 2021-10-01 13:50 UTC
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.57.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=dct.CARTAPORTE.API, containerState=COMPONENT_CREATED, componentStore=C:\Users\EON-35\Documents\Danone\Backend\dct.CARTAPORTE.API))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfiguration.java:103)

**Comment by wangmingliang-ms** [comment] 2021-10-03 14:30
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-03 14:30 UTC
