### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@1e06434a when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@326ddd3d com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.usgovcloudapi.net/  -t 030e81e9-0529-4468-a323-b30d5496e634 --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by pcsmiana** [microsoft/azure-tools-for-java#8092] opened 2024-01-08 17:58 UTC
IntelliJ build version: 2023.3.1 IU-233.11799.300
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.Cognitive

**Comment by Flanker32** [comment] 2024-01-29 07:47
@pcsmiana Thank you for reporting this issue and we apologize for the delay in responding to you. Please track the issue in #8101. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:47
Duplicate of #8101

**Closed as completed by Flanker32** 2024-01-29 07:47 UTC
