### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@3279f531 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@7f9c85c0 com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.windows.net/  -t 56564e0f-83d3-4b52-92e8-a6bb9ea36564 --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#7668] opened 2023-07-05 12:13 UTC
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1380x875,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.monitor.LogAnalyticsWork

**Comment by Flanker32** [comment] 2024-01-29 07:49
@prshnt Thank you for reporting this issue and we apologize for the delay in responding to you. Please track the issue in #8101. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:49
Duplicate of #8101

**Closed as completed by Flanker32** 2024-01-29 07:49 UTC
