### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.redis.property.RedisCachePropertiesEditorProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by Maniatty** [microsoft/azure-tools-for-java#8087] opened 2024-01-05 01:25 UTC
IntelliJ build version: 2023.3.1 IU-233.11799.300
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,3535x2046,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$setTransparentTitleBar$customBorder$1@e5bc444,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.redis.property.RedisCachePropertiesEditorProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:111)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

**Comment by Flanker32** [comment] 2024-01-29 08:40
@Maniatty Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?

**Comment by wangmingliang-ms** [comment] 2024-11-06 03:01
Duplicate of #8143

**Closed as completed by wangmingliang-ms** 2024-11-06 03:01 UTC
Labels: Type: Bug, Tool: IntelliJ, need more info
