### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=pdicloud-infra, containerState=COMPONENT_CREATED, componentStore=/Users/dicken.george/bitrepo/pdicloud-infra))

### ISSUE THREAD

**Issue by DG007** [microsoft/azure-tools-for-java#5890] opened 2021-09-30 19:54 UTC
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1415,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@991c9af,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'RunManager': class com.intellij.execution.impl.RunManagerImpl and class com.intellij.execution.impl.RunManagerImpl (componentManager=Project(name=pdicloud-infra, containerState=COMPONENT_CREATED, componentStore=/Users/dicken.george/bitrepo/pdicloud-infra))
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyRunConfigurationExtension.isApplicableFor(ConnectionRunnerForRunConfiguration.java:103)
```

**Comment by wangmingliang-ms** [comment] 2021-10-03 14:31
Duplicate of #5888

**Closed as completed by wangmingliang-ms** 2021-10-03 14:31 UTC
