### ISSUE TITLE
[Azure Toolkit for IntelliJ] Multi-Factor Authentication does not work

### ISSUE THREAD

**Issue by mirodd** [microsoft/azure-tools-for-java#1332] opened 2018-01-09 15:06 UTC
Along with my colleagues, we are having troubles when signing in from IntelliJ using Azure Explorer (part of Azure Toolkit for IntelliJ) to Azure.
We are using the latest version of the toolkit (3.1.0 – 2017.3) but we are getting a Multi-Factor Authentication error similar to this:

AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxx'.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2018-01-08 12:24:51Z","error_codes":[50076],"timestamp":"2018-01-08 12:24:51Z","trace_id":"xxx","correlation_id":"xxx"}

We have checked the issue tracker here GitHub but were not able to find anything related with that problem.
So I am opening a new issue and hope this to be solved as soon as possible.

Thanks.

**Comment by Eskibear** [comment] 2018-01-11 02:33
Current knowledge:

* The user can successfully sign-in with AAD (MFA passed)  in browser.

**Comment by mirodd** [comment] 2018-01-11 08:17
Hello,
We were having separate discussion on email but we are moving now here.
So, I've tried as suggested to log in using IE InPrivate tab or Chrome Incognito window via this link: https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client-request-id=083f2439-b24a-4123-95da-af6b5f08c960&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&prompt=login&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c

I am getting redirected properly to my company login page and when I put my credentials and then enter the code I get at my device, I am receiving an error I have previously sent (in the attached file)
![error_toolkit](https://user-images.githubusercontent.com/35266014/34814940-2d0b8d7e-f6b8-11e7-914d-6bb848bc645d.png)

On the other hand, I also contacted our IT administrators and no changes have been made to my account. In order to give you the full picture, I have managed to log on with the same account using an older version of the toolkit but do not remember the exact version. However, I need the new one as the previous was not working with HDInsight clusters when the default storage is Data Lake Store Account.

Note that the MFA works like charm with the same account when accessing Azure SQL Databases for example.

Let me know if you need more details from my side and how we can take this further.
Thanks.

**Comment by Eskibear** [comment] 2018-01-16 06:51
@mirodd 
In the IDE plugin, authentication workflow is as following:
1. Generate a request, open in integrated browser, let you sign in and verify MFA.
1. Once MFA is successfully verified, `authorization_code` is appended after `https://msopentech.com/?code=` as the redirected url.     (this page is not valid, it's only used to receive `authorization_code`)
![image](https://user-images.githubusercontent.com/2351748/34974915-520a2584-faca-11e7-839f-f0789b9d6c91.png)
1. with the `authorization_code`, we try fetching tokens for different resources.

I your case, `authorization_code` has been got. We suppose something is wrong with the `fetchToken` task.
Since we don't have any account to re-produce it, we are not able to locate where the problem is. (e.g. which resource or any server-side change)

### Things we want to know about the 400 error.
* The whole story is `popup a dialog`, `type in credentials`, `verify MFA`, `select subscriptions`, `done with sign-in`. In which step did you get the error? Or you just successfully signed in, but got error when accessing some resources?

### Suggestions
* If you can provide an account for us to diagnose, send to me and @jdneo via email please.
* We didn't change the authentication workflow in this IDE plugin for months, and it is almost the same with that in Azure CLI. You might also have a try on [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/overview?view=azure-cli-latest), and see whether there's bug in the workflow.

**Comment by mirodd** [comment] 2018-01-24 11:50
@Eskibear 
Unfortunately, as it is a company-owned account, I do not think it is a good idea to provide you with that.
However, I have tested your second suggestion and tried with Azure CLI. The result is similar to the one we are getting with the Toolkit and the error is pretty much the same:

To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code xxx to authenticate.
Failed to authenticate '{'id': '/tenants/xxx', 'tenant_id': 'xxx'}' due to error 'Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxx'.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2018-01-24 11:43:21Z","error_codes":[50076],"timestamp":"2018-01-24 11:43:21Z","trace_id":"xxx","correlation_id":"xxx"}'
No subscriptions were found for 'None'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses

What can we do now then? Is this helping you to conclude where the problem might be?

Thanks!

**Comment by Eskibear** [comment] 2018-01-25 04:00
@mirodd 
From the behavior, I suppose the problem is most likely located in:
* Azure AD service
* Configuation or policy change of your organization

> We didn't change the authentication workflow in this IDE plugin for months, and it is almost the same with that in Azure CLI. 

As I mentioned, both AzureCLI and this IDE plugin follow the same auth workflow according to AzureAD documentation.

> On the other hand, I also contacted our IT administrators and no changes have been made to my account. 

I remember your colleagues also have the same issue, so is it possible that your IT admins change some organization policy or something else?

### Followups
@Matthew-Dong will help to loop Azure AD service team in the former mail threads.

Meanwhile you might also share the details with your IT administrators, and let them create a support ticket for Azure AD support if necessary.

**Comment by Eskibear** [comment] 2018-02-22 03:18
## Possible workaround 
Manually generate an authfile:

1. Follow https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal to create an AAD application.
2. Create a plain text file e.g. `example.azureauth`
```
subscription=########-####-####-####-############
client=########-####-####-####-############
tenant=########-####-####-####-############
key=XXXXXXXXXXXXXXXX
managementURI=https\://management.core.windows.net/
baseURL=https\://management.azure.com/
authURL=https\://login.windows.net/
graphURL=https\://graph.windows.net/
```
`subscription`: Subscription Id
`client`: AAD application Id
`tenant`: Tenant Id 
`key`: AAD application key

3. Use **Automated** method when sign-in in the toolkit.

**Comment by Eskibear** [comment] 2019-06-13 06:28
AFAIK, now it adopts the device-code flow to auth. Leveraging external browser, it is supposed not to have the MFA issue. I'm closing it.

**Closed by Eskibear** 2019-06-13 06:28 UTC
