### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "org.jetbrains.idea.maven.project.MavenProject.getParentId()" because "result" is null

### ISSUE THREAD

**Issue by survivant** [microsoft/azure-tools-for-java#6909] opened 2022-08-31 17:58 UTC
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1401,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "org.jetbrains.idea.maven.project.MavenProject.getParentId()" because "result" is null
	at com.microsoft.intellij.util.MavenUtils.getRootMavenProject(MavenUtils.java:111)
	at com.microsoft.azure.toolkit.intellij.legacy.function.wizard.module.helper.MavenFunctionsModuleBuilderHelper.lambda$setupMavenModule$1(MavenFunctionsModuleBuilderHelper.java:47)
```

**Comment by Flanker32** [comment] 2022-09-04 14:50
@survivant Thanks for your report and sorry for the trouble, we will investigate this issue soon and update here once we have any updates.

**Comment by wangmingliang-ms** [comment] 2022-09-21 08:27
Duplicate of #6605

**Closed as completed by wangmingliang-ms** 2022-09-21 08:27 UTC
Labels: Type: Bug, Module: Azure Functions, Reason: fixed, State: Resolved
