### ISSUE TITLE
"RefreshWorkspace" progress running constantly

### ISSUE THREAD

**Issue by mkurz** [Microsoft/azure-tools-for-java#15] opened 2016-06-20 09:50 UTC
Azure Toolkit for Eclipse

When having projects in Eclipse which are not Dynamic Web applications but just normal projects my eclipse is getting crazy. There are `RefreshWorkspace` tasks running all the time and which occupies a  processor all the time.
When I remove the non dynamic web application projects everyhing is normal again.
I had to remove the Azure Toolkit for Eclipse everything is back to normal again.

**Comment by mkurz** [comment] 2016-06-20 09:51
I tried in latest Eclipse in Ubuntu, as well in Windows 7 (both with completly fresh Eclipse installations)

**Comment by duanewaninger** [comment] 2016-07-12 18:59
I am experiencing the same issue.  Eclipse is rendered completely useless in a matter of 15 seconds by the Refresh threads.  I've attached a time lapse of thread dumps and it appears the plugin is spinning multiple concurrent refresh threads that are in contention.  It also looks like threads are never actually terminated and just go into a wait state resulting in an ever increasing number of threads.  I've see it get up to over 300.  Eclipse becomes so useless waiting for the threads to complete that after 2.5 hours, I finally killed the Eclipse Windows process rather than waiting for these threads to stop.

[ThreadDump1-10_30_44_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360068/ThreadDump1-10_30_44_AM.txt)
[ThreadDump2-10_32_41_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360071/ThreadDump2-10_32_41_AM.txt)
[ThreadDump3-10_33_35_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360069/ThreadDump3-10_33_35_AM.txt)
[ThreadDump4-10_36_37_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360070/ThreadDump4-10_36_37_AM.txt)
[ThreadDump5-10_47_18_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360072/ThreadDump5-10_47_18_AM.txt)
[ThreadDump6-11_07_36_AM.txt](https://github.com/Microsoft/azure-tools-for-java/files/360073/ThreadDump6-11_07_36_AM.txt)

**Comment by mkurz** [comment] 2016-07-12 19:41
Thanks for providing the thread dumps @duanewaninger 
Hopefully someone from Microsoft will have a look....

**Comment by pednekarprajakta** [comment] 2016-07-12 21:16
@mkurz and @duanewaninger, Thanks for reporting the issue. What exact steps did you perform using Azure Toolkit for Eclipse which caused “RefreshWorkspace” issue ?

@mkurz, Could you also provide thread dumps ? It will help us to debug the issue.

**Comment by mkurz** [comment] 2016-07-12 21:54
@pednekarprajakta Thanks for the response.
I don't have azure tools installed anymore. As far as I remember the problem was that if you have project in eclipse that is **not** a dynamic web application then this issue appeared.

You could try to reproduce like this:
1) Open eclipse and create a new dynamic web project
2) Now import [this dummy project](https://github.com/mkurz/make-azure-tools-for-java-fail) into eclipse:
  * Goto "File" -> "Import..."
  * Choose "Existing Projects into Workspace"
  * Select the above project (just clone or download it)

After you imported the project the bug should appear.

Let me know if you can reproduce the problem.

**Comment by mkurz** [comment] 2016-07-13 10:31
@pednekarprajakta Can you reproduce the problem?

**Comment by duanewaninger** [comment] 2016-07-13 13:28
The issue starts the moment you install the plugin.  I happen to be working with Dynamic Web Project, Maven Projects and Spring Maven Project, but it really doesn't seem to make a difference.  The number of threads spun off by the plugin begins increasing as you move around Eclipse perform common tasks like compiling code, changing project properties, etc; basically anything that would cause Eclipse to trigger a Workspace Refresh.

I too had to uninstall the Plugin in order to move on with work.  But the problem is easily reproducible.

**Comment by duanewaninger** [comment] 2016-07-13 13:41
I should add that I'm currently using the following Eclipse version on Windows:

Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

But, I've also tried Eclipse Kepler and Luna versions and Rational Application Developer 9.1 with the same result.

**Comment by mkurz** [comment] 2016-07-13 13:43
I tested on Windows 7 and Ubuntu 12.04 with Eclipse Mars. Also on both systems the problem occured immediately. Hard to believe someone is actually using this plugin...

**Comment by pednekarprajakta** [comment] 2016-07-13 23:26
@mkurz I am not able to reproduce the issue using the provided sample dummy project. I did exactly same steps which you mentioned. I tested on Windows 8.

**Comment by priand** [comment] 2016-07-19 20:45
@pednekarprajakta FYI, I'm getting the same issue that makes Eclipse just unusable. My workspace contains a lot of projects: Java, J2EE, Android, RoboVM... all maven enabled The initialization never ends as it constantly refreshes the workspace. This happens right after installing 2.9.0 on Mars 4.5.2, Windows 64 bits. I already tried it twice with the same outcome.
I'll be happy to send you all the log files you need or even run a screen sharing session with you if it helps.

**Comment by duanewaninger** [comment] 2016-07-26 20:19
Any updates from the Microsoft team on resolving this issue?

**Comment by martinsawicki** [comment] 2016-08-02 12:32
we're still looking for a way to reproduce this issue as none of us are able to see this problem (Linux, Mac, Windows). I'm using Mars 4.5.2 with the Toolkit installed and a number of Maven projects, on Win 10 - no issues...  So the main challenge right now is to figure out what is different about your environments.

**Comment by priand** [comment] 2016-08-31 14:46
@martinsawicki if you still cannot reproduce it, I can share my screen with you or give you access to the machine

**Comment by martinsawicki** [comment] 2016-09-08 23:25
we provided at attempt to fix this issue (though not being able to repro) -- fix shipped in the latest toolkit updates -- see if it helps.

**Comment by priand** [comment] 2016-09-19 00:40
@martinsawicki thanks a lot for fix, it seems that the issue disappeared with 2.9.5. I'll watch it in the next few weeks to validate this conclusion.
BTW, it now generates many errors in the error logs, while it seems to be some debug information (<project>isOpenTrue, <project>isNaturefalse, ...). All these entries are coming from WAEclipsePlugin

**Comment by martinsawicki** [comment] 2016-10-27 21:34
thank you, if there is a specific new issue to file, please log as a new issue with repro steps. thanks for the feedback!

**Closed by martinsawicki** 2016-10-27 21:34 UTC
