### ISSUE TITLE
Can't auto refresh web app 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2775] opened 2019-02-27 09:22 UTC
### Environment:
1. Eclispe: 2018-12 (4.10.0)
2. JDK: 1.8
3. Bits: dev944

### Behavior:
First, make sure you have at least two Web Apps
1. Delete one app service (e.g monawarwin33) in Deploy to Web App dialog, after deleting, the web app list in Azure Explorer will not auto-refresh.
2. Delete another web app (e.g. monajarwin111) in Azure Explorer, open deploy to Web App dialog, you will find the deleted web app still exist.

![image](https://user-images.githubusercontent.com/22470312/53479288-aa2acf00-3ab3-11e9-97cf-a58f04c43b96.png)

**Comment by ZhengJun003** [comment] 2020-06-15 09:29
Can reproduce this issue in azure toolkits for eclipse 3.23.0

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738757

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: Eclipse, Internal Test, P3, app-service, bug, transfter
