### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by deadman76926** [microsoft/azure-tools-for-java#7657] opened 2023-06-30 01:56 UTC
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1079,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:258)
```

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:04
Duplicate of #7736

**Closed as completed by wangmingliang-ms** 2023-09-08 06:04 UTC
