### ISSUE TITLE
The region list should be sorted for easy navigation

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#324] opened 2017-04-12 18:24 UTC
Issue:
The region list is not sorted, especially that "West US" and "West US 2" are faraway from each.

Expected:
Region list is sorted for fast navigation.

Repro:
1. Create a Dynamic Web Project Eclipse Neon.
2. Click the dropdown list on toolbar for Azure, then choose "Publish as Docker Container."
3. Click Add to create a new Docker host.
4. Click on the Region list, then you will see:
<img width="526" alt="screen shot 2017-04-12 at 11 17 40 am" src="https://cloud.githubusercontent.com/assets/6917718/24972915/de55f944-1f71-11e7-8c16-907b054e8fe5.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: Eclipse Neon.3

Plugin: WindowsAzurePlugin4EJ.273.04-12-2017.zip

Feature: Publish as "Docker Container".

**Comment by martinsawicki** [comment] 2017-04-12 18:30
dupe of the alphabetical ordering issue

**Comment by lenala** [comment] 2017-04-12 20:53
This is fixed, please verify.

**Comment by bsaby** [comment] 2017-04-13 02:35
Test passed, using WindowsAzurePlugin4EJ.278.04-12-2017.zip.

**Closed by bsaby** 2017-04-13 02:35 UTC
Labels: bug-bash, Eclipse, fixed
