### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.intellij.ide.ui.UITheme$1@327120c8 cannot patch icon path java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by redrebelsheep** [microsoft/azure-tools-for-java#6685] opened 2022-06-07 06:40 UTC
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.65.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1870x1200,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@57101048,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.intellij.ide.ui.UITheme$1@327120c8 cannot patch icon path, throwable=java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.loadIcon(IntelliJAzureIcons.java:109)
	at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.lambda$doGetIcon$2(IntelliJAzureIcons.java:91)
	at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.doGetIcon(IntelliJAzureIcons.java:91)
	at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.getIcon(IntelliJAzureIcons.java:82)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper.applyView(IntellijAzureActionManager.java:139)
	at com.micr

**Comment by wangmingliang-ms** [comment] 2022-06-07 07:06
Duplicate of #6674

**Closed as completed by wangmingliang-ms** 2022-06-07 07:06 UTC
