### ISSUE TITLE
Sign in-> In the Subscriptions window, click Cancel still successfully signed in 

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1101] opened 2017-10-10 07:31 UTC
Repro steps:

1. Open Azure Sign in window and choose any of the ways to sign in
2.  Through some validation until pop up the below subscriptions window
3.  Click Cancel

**Result:**
Still sign in
**Expect:** 
Can't Sign in
![image](https://user-images.githubusercontent.com/22470312/31374246-be1970ec-adcf-11e7-8918-ee5256d4f25e.png)

Not a regression issue,

**Comment by Eskibear** [comment] 2017-10-10 15:02
by `not regression`, do you mean it's existing all the time?

**Comment by bsaby** [comment] 2017-10-11 01:15
Yes

**Comment by adashen** [comment] 2017-10-11 01:17
This is a design issue. When subscription selection dialog shows up, user has already login in. The dialog just ask the user to filter some subscriptions. So one proposal is to remove the cancel button.

**Comment by andxu** [comment] 2020-06-16 05:27
@adashen , this issue has very low impact on user experience.

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738795

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, IntelliJ, Internal Test, P3, auth, cancel-job, enhancement, transfter
