### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot process toolwindow Resource Connections com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.microsoft.azure.toolkit.intellij.connector.ConnectionManager because container is already disposed (container=Project(name=intelligent-kakamora, containerState=DISPOSE_COMPLETED, componentStore=/home/clopez/Projects/Java/intelligent-kakamora) (disposed))

### ISSUE THREAD

**Issue by cailtin** [microsoft/azure-tools-for-java#7325] opened 2023-02-22 15:31 UTC
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Linux
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.73.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,29,1910x1000,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot process toolwindow Resource Connections, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.microsoft.azure.toolkit.intellij.connector.ConnectionManager because container is already disposed (container=Project(name=intelligent-kakamora, containerState=DISPOSE_COMPLETED, componentStore=/home/clopez/Projects/Java/intelligent-kakamora) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindo

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:48
Duplicate of #7198

**Closed as completed by wangmingliang-ms** 2023-03-20 01:48 UTC
