### ISSUE TITLE
[IntelliJ][ReportedByUser] Failed to load Azure SDK meta data from github

### ISSUE THREAD

**Issue by freastro** [microsoft/azure-tools-for-java#5464] opened 2021-07-01 17:22 UTC
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1

Additional Info:
Based on the below error message, I'm guessing that the Azure SDK is not able to validate the SSL certificate for GitHub? I'm using a proxy to access the Internet and that may be causing the error. I added the proxy's SSL certificate to IntelliJ: https://www.jetbrains.com/help/idea/settings-tools-server-certificates.html. And IntelliJ is now able to download plugins and updates, but I'm still seeing the same error message with the Azure SDK. Could the Azure SDK use the same server certificates that IntelliJ does?

Parent component:
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,3200x1747,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```

Error message: 
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: rx.exceptions.OnErrorNotImplementedException: load Azure SDK meta data from github
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:79)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onNext(OperatorSubscribeOn.java:74)
	at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: load Azure SDK meta data from github
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getAzureSDKEntities_aroundBody2(AzureSdkLibraryService.java:158)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService$AjcClosure3.run(AzureSdkLibraryService.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.lambda$readCache$0(CacheManager.java:121)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4864)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.readCache(CacheManager.java:118)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.ajc$inlineAccessMethod$com_microsoft_azure_toolkit_lib_common_cache_CacheManager$com_microsoft_azure_toolkit_lib_common_cache_CacheManager$readCache(CacheManager.java:1)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.aroundCacheable(CacheManager.java:69)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getAzureSDKEntities(AzureSdkLibraryService.java:150)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getDeprecatedAzureSDKEntities_aroundBody4(AzureSdkLibraryService.java:168)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService$AjcClosure5.run(AzureSdkLibraryService.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.lambda$readCache$0(CacheManager.java:121)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4864)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4859)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.readCache(CacheManager.java:118)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.ajc$inlineAccessMethod$com_microsoft_azure_toolkit_lib_common_cache_CacheManager$com_microsoft_azure_toolkit_lib_common_cache_CacheManager$readCache(CacheManager.java:1)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.aroundCacheable(CacheManager.java:69)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getDeprecatedAzureSDKEntities(AzureSdkLibraryService.java:168)
	at com.microsoft.azure.toolkit.intellij.azuresdk.enforcer.AzureSdkEnforcer.enforce(AzureSdkEnforcer.java:36)
	at com.microsoft.intellij.AzurePlugin.lambda$afterInitialization$2(AzurePlugin.java:152)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	... 11 more
Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException: failed to load Azure SDK list from "https://raw.githubusercontent.com/Azure/azure-sdk/master/_data/releases/latest/java-packages.csv"
	... 45 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at com.fasterxml.jackson.core.TokenStreamFactory._optimizedStreamFromURL(TokenStreamFactory.java:211)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:306)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createParser(CsvFactory.java:15)
	at com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1035)
	at com.fasterxml.jackson.databind.ObjectReader.readValues(ObjectReader.java:1944)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getAzureSDKEntities_aroundBody2(AzureSdkLibraryService.java:152)
	... 44 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 67 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 73 more

**Comment by wangmingliang-ms** [comment] 2021-07-06 05:28
Duplicate of #5444 , backup with local metadata file when failed to load from github at runtime.

**Closed by wangmingliang-ms** 2021-07-06 05:28 UTC
