### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @fff2294)

### ISSUE THREAD

**Issue by ponsianodeloor** [microsoft/azure-tools-for-java#8123] opened 2024-01-29 21:02 UTC
IntelliJ build version: 2023.3.3 IU-233.14015.106
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl cannot be cast to class com.intellij.psi.PsiLiteralExpression (com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl and com.intellij.psi.PsiLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @fff2294)
	at com.microsoft.azure.toolkit.intellij.storage.code.spring.StoragePathPrefixCompletionProvider.addCompletions(StoragePathPrefixCompletionProvider.java:30)
```

**Comment by Flanker32** [comment] 2024-01-30 01:34
@ponsianodeloor Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/8109. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-30 01:34
Duplicate of #8109

**Closed as completed by Flanker32** 2024-01-30 01:34 UTC
