### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by andriesfc** [microsoft/azure-tools-for-java#5470] opened 2021-07-04 15:21 UTC
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@7e505c52,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=playgroundk, containerState=DISPOSE_COMPLETED, componentStore=/Users/aspies/Projects/playgroundk) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=playgroundk, containerState=DISPOSE_COMPLETED, componentStore=/Users/aspies/Projects/playgroundk) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.azure.toolkit.intellij.azuresdk.enf

**Comment by wangmingliang-ms** [comment] 2021-07-06 05:25
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-06 05:25 UTC
