### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'subscribeOnCalla

### ISSUE THREAD

**Issue by mckreddy** [microsoft/azure-tools-for-java#9537] opened 2024-10-27 22:13 UTC
IntelliJ build version: 2024.1.6 IC-241.19072.14
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.11
Plugin version: 3.92.0-2024.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1601x1019,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'subscribeOnCallable' (and no fallback has been configured)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'subscribeOnCallable' (and no fallback has been configured)
```

**Comment by wangmingliang-ms** [comment] 2024-11-06 01:31
Duplicate of #8997

**Closed as completed by wangmingliang-ms** 2024-11-06 01:31 UTC
