### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by LESUTOH** [microsoft/azure-tools-for-java#7806] opened 2023-08-29 05:57 UTC
IntelliJ build version: 2023.1.4 IU-231.9225.16
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.79.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1392,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2023-09-08 06:01
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-09-08 06:01 UTC
