### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)

### ISSUE THREAD

**Issue by Raikenken** [microsoft/azure-tools-for-java#8084] opened 2024-01-02 18:07 UTC
IntelliJ build version: 2023.3.2 IU-233.13135.103
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x900,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler$1.processWillTerminate(RunProcessHandler.java:88)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyComplete(RunProcessHandler.java:110)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$1(SpringCloudDeploymentConfigurationState.java

**Comment by Flanker32** [comment] 2024-01-29 07:55
@Raikenken Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8100. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment] 2024-01-29 07:55
Duplicate of #8100

**Closed as completed by Flanker32** 2024-01-29 07:55 UTC
