### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception DeployFunctionAppAction#update@MainMenu (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(asciidoc-kata) is a valid function project

### ISSUE THREAD

**Issue by mr83** [microsoft/azure-tools-for-java#7637] opened 2023-06-22 06:45 UTC
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2022.3
Additional Info: I was not using or intending to use Azure Toolkit, when the problem occured
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2762x1718,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@c34eb61,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=DeployFunctionAppAction#update@MainMenu (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(asciidoc-kata) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function

**Comment by Flanker32** [comment] 2023-06-28 02:47
Duplicate of #7624

**Closed as completed by Flanker32** 2023-06-28 02:47 UTC
