### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by vijtheveg** [microsoft/azure-tools-for-java#6892] opened 2022-08-29 07:08 UTC
IntelliJ build version: 2022.2.1 IC-222.3739.54
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.67.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1393,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by wangmingliang-ms** [comment] 2022-09-01 01:29
Duplicate of #6844

**Closed as completed by wangmingliang-ms** 2022-09-01 01:29 UTC

**Comment by wangmingliang-ms** [comment] 2022-09-23 06:46
Hi, @vijtheveg, thanks for reporting. can you tell us how to reproduce this error? This error has been reported several times, but we don't know how to reproduce it, making us unable to fix it immediately.

**Comment by vijtheveg** [comment] 2022-09-24 02:06
Unfortunately, I am not sure how I encountered this bug either, and therefore don't now how to reproduce it.

**Comment by wangmingliang-ms** [comment] 2022-09-26 01:48
@vijtheveg Thanks anyway for reporting this bug to us. If you find out how to reproduce later, I hope you can add details here.
