### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'

### ISSUE THREAD

**Issue by rjackson88** [microsoft/azure-tools-for-java#3019] opened 2019-04-13 21:38 UTC
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,929x494,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:153)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:14)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:93)
	at

**Comment by wezhang** [comment] 2019-04-15 01:19
Thanks @rjackson88 ! Could you help provide steps to reproduce?

**Comment by wezhang** [comment] 2019-04-15 01:20
Dup #2983

**Comment by andxu** [comment] 2020-06-02 07:58
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  User feedback (#1831)

**Comment by vscjavaci** [comment] 2020-06-03 08:22
Close this issue due to duplicate error: throwable=com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'

**Closed by vscjavaci** 2020-06-03 08:23 UTC
Labels: Feedback, HDInsight, IntelliJ, System Telemetry, duplicate
