### ISSUE TITLE
[IntelliJ2017]Can't open in browser in after deploying as Azure Web App[Linux]

### ISSUE THREAD

**Issue by davidliangze** [Microsoft/azure-tools-for-java#511] opened 2017-05-22 05:02 UTC
Repro Step:
Choose Deploy as Azure Web App through toolbar or right clicking the project.
Click "+"to create new app service. 
Keep the setting as default and Create.
Deploy to the new created App Service.
After the web app published, right click this web app service in Azure Explorer and Open in Browser.

**Expected:**
If you deploy to root, it will show the content of the webpage.
If you don't deploy to root, it will show a message saying that deploying is successful.

**Actual:**
It shows nothing in the explorer or it throws back a error.
![capture1](https://cloud.githubusercontent.com/assets/26756696/26293385/e09a9c04-3eee-11e7-8d16-2fe4a207c9eb.JPG)
![capture2](https://cloud.githubusercontent.com/assets/26756696/26293903/a20cd444-3ef2-11e7-9186-af685707a37c.JPG)

**Comment by adashen** [comment] 2017-05-22 05:14
Is it duplicate with https://github.com/Microsoft/azure-tools-for-java/issues/342 ?
if So please close it as duplicate

**Comment by davidliangze** [comment] 2017-05-22 05:26
No it's not the same with #342.

In this issue, the explorer should have shown the proper content, weather you deploy to root or not.
For the scenario deploying to root, the expected result is the browser will navigate to the root URL and show the content.
For the scenario not deploying to root, the expected result is the browser will still navigate to the root URL and show a default page saying the deployment is successful.

But the actual performance is either it shows nothing, or it throw back a error 404/ error 503 etc.

**Comment by adashen** [comment] 2017-05-22 05:31
The reason is the service is not started up. Can you check the service status in portal? Whether it is deployed successfully or not? Besides, is this regression issue?

**Comment by davidliangze** [comment] 2017-05-22 05:39
Yes, the services are deployed successfully and is running. ![capture3](https://cloud.githubusercontent.com/assets/26756696/26294053/a37568ea-3ef3-11e7-95c7-2bade5fa6e09.JPG)

And yes it is a regression issue.

**Comment by Eskibear** [comment] 2017-05-23 03:22
cannot repro. 
OS: Ubuntu 16.04 LTS
Build: azure-toolkit-for-intellij.2017.develop.daily.10.05-22-2017.zip

PS:
FYI, about `If you don't deploy to root, it will show a message saying that deploying is successful.`, I think just after creating the app service, the default page exists, saying  successfully **created** instead of **deployed**. 

Anyway I cannot repro it, if you can still repro this issue, plz provide more details and reopen it. @davidliangze

**Closed by Eskibear** 2017-05-23 03:22 UTC
Labels: bug-bash, IntelliJ
