### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun java.lang.IllegalStateException: Index is not created for `Stubs`

### ISSUE THREAD

**Issue by SP-2827** [microsoft/azure-tools-for-java#6159] opened 2021-12-02 09:55 UTC
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,26,1366x715,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=961,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=java.lang.IllegalStateException: Index is not created for `Stubs`
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndex(FileBasedIndexImpl.java:1249)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findMainMethod(SparkContextUtils.kt:89)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.update(SparkRunConfigurationAction.kt:70)

**Comment by fengshuaihu** [comment] 2022-12-29 05:24
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7158

**Closed as completed by fengshuaihu** 2022-12-29 05:24 UTC
Labels: Module: HDInsight
