### ISSUE TITLE
[MAC]Device login, an extra sign in progress window appeared

### ISSUE THREAD

**Issue by sallyur** [microsoft/azure-tools-for-java#2802] opened 2019-03-01 08:13 UTC
Sometimes, this issue can stable repro, sometimes not.

### Environment:
1. OS: Mac
2. IDE version:
```
 IntelliJ IDEA 2019.1 EAP (Ultimate Edition) Build #IU-191.5849.21, built on February 27, 2019
 IntelliJ IDEA 2019.1 EAP (Community Edition) Build #IC-191.5849.21, built on February 27, 2019

```
3. Bits: 3012

### Steps:
1. Right-click `Azure `in Azure explorer and choose `Sign In`
2. Select Interactive method. then cancel
3. Click try device log flow

### Result:
An extra sign in progress window appeared
![image](https://user-images.githubusercontent.com/28860891/53624942-b8582700-3c3c-11e9-9d17-381f60a9d0d7.png)

If I click the sign in progress window, it will hide behind other windows

**Comment by ZhengJun003** [comment] 2020-06-16 08:03
Can reproduce this issue in azure toolkits for IntelliJ 3.37.0, IntelliJ version is IU19.3-jre8
This issue does not reproduce in IntelliJ 2020.1

![image](https://user-images.githubusercontent.com/41051257/84748036-ad203a80-afea-11ea-8485-0bb28500762a.png)

**Comment by andxu** [comment] 2020-06-17 05:57
Very trivial issue.

**Comment by vscjavaci** [comment] 2020-06-23 12:25
Track internal issue by AB#1738762

**Comment by vscjavaci** [comment] 2020-07-02 01:12
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:12 UTC
Labels: IntelliJ, Internal Test, P3, auth, bug, transfter
