### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Cannot process toolwindow Resource Connections (Deprecated)

### ISSUE THREAD

**Issue by ymartmengual** [microsoft/azure-tools-for-java#8022] opened 2023-11-27 19:51 UTC
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,8,0,784x642,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Cannot process toolwindow Resource Connections (Deprecated)
  com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.facet.ProjectFacetManager because container is already disposed (container=Project(name=administracion, containerState=DISPOSE_COMPLETED, componentStore=<REDACTED: user-file-path>) (disposed))
at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindowFactory.shouldBeAvailable(ResourceConnectionExplorer.java:139)
```

**Comment by Flanker32** [comment] 2023-12-06 12:07
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7889

**Comment by Flanker32** [comment] 2023-12-06 12:07
@ymartmengual Thanks for your report and sorry for the trouble, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/7889

**Closed as completed by Flanker32** 2023-12-06 12:07 UTC
