### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: !connector|connection.prepare_before_run!

### ISSUE THREAD

**Issue by ghost** [microsoft/azure-tools-for-java#6192] opened 2021-12-10 05:13 UTC
IntelliJ build version: 2021.3 IC-213.5744.223
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1848x1016,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: !connector|connection.prepare_before_run!
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.connector.Connection.prepareBeforeRun(Connection.java:96)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.lambda$executeTask$0(ConnectionRunnerForRunConfiguration.java:87)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.executeTask(ConnectionRunnerForRunConfiguration.java:87)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.executeTask(ConnectionRunnerForRunConfiguration.java:43)
Caused by: com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not

**Comment by wangmingliang-ms** [comment] 2022-02-18 06:45
Duplicate of #6382

**Closed as completed by wangmingliang-ms** 2022-02-18 06:45 UTC
