### ISSUE TITLE
App insights list can't be refreshed automatically when change selected subscription

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#1585] opened 2018-04-09 07:16 UTC
Not a regression issue.
Also repro in AI 1.0.10 
![image](https://user-images.githubusercontent.com/22470312/38483729-8dd2046a-3c06-11e8-90d8-fc8ebf5b667c.png)

**Comment by ZhengJun003** [comment] 2020-06-15 02:43
Can reproduce this issue in azure toolkits for Eclipse 3.23.0

**Comment by vscjavaci** [comment] 2020-06-23 12:26
Track internal issue by AB#1738787

**Comment by vscjavaci** [comment] 2020-07-02 01:11
Close this issue since it is tracked in Azure Boards.

**Closed by vscjavaci** 2020-07-02 01:11 UTC
Labels: Eclipse, Internal Test, P3, app-insights, bug, transfter
