### ISSUE TITLE
error (Message from Azure: 'Index: 0' Size: 0' ) while login using Eclipse Azure Toolkit

### ISSUE THREAD

**Issue by martinsawicki** [Microsoft/azure-tools-for-java#30] opened 2016-11-03 19:18 UTC
[PROBLEM DESCRIPTION]
Customer is getting this error (Message from Azure: 'Index: 0' Size: 0' ) while login using Eclipse Azure Toolkit

-Customer using updated version of Azure toolkit plugin and tried to login Azure account we use to get Message from Azure: 'Index: 0' Size: 0'.
- When we try again in second attempt we are able to login and deploy successfully and as we discussed this issue happening because of drop in network authentication and it is working in second attempt.

**Comment by martinsawicki** [comment] 2016-11-29 20:15
planned to investigate for the 2.9.6 release (January)

**Comment by gosig** [comment] 2016-12-16 06:06
finally I found the man who was same case as me.
Is there any way possible..?
what means 2.9.6 release..? is it version of Eclipse Azure ToolKit? 
As I see, the recently version is 2.9.0 and 2.9.7 mixed..

please, let me know how to do..

**Comment by iljoong** [comment] 2016-12-26 04:54
It looks like this error is poping up when user logs in via Microsoft account (e.g., outlook.com).

**Comment by martinsawicki** [comment] 2016-12-26 16:23
we have not been able to reproduce this issue yet, so thank you for the additional clues.

**Comment by dpeddi** [comment] 2016-12-31 07:02
same issue here with @msn.com account 

Azure login dialog url:
https://login.microsoftonline.com/common/oauth2/authorize?return-client-request-id=true&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client-request-id=758a5a0b-ad02-4b1e-844f-b1db408146e5&response_type=code&redirect_uri=https%3A%2F%2Fmsopentech.com%2F&prompt=login&client_id=61d65f5a-6e3b-468b-af73-a033f5098c5c

After entered the username, I get redirected to:
https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxM0wxM00zTdQ1SzVO0jUxs0jSTUwzN9ZNNDA2TjM1sLRINk0uEuISSJ6yQLxubqjfpEZp77uaMzasYhTPKCkpKLbS188tzi9IzStJTc7QS87P1d_ByHiBkfEFI2MDE-MtJn5_x9KSDCMQkV-UWZX6CEPkFRNrTn56Zt4qZhW4iYl5iempuUBDgSYWpeqVZ-al5JcX6-WlluhvYmYD2pKbn7eLWcU8Jc3QJNkwUTfV1DQV6HhTS91EQ3NL3SSzVNPUNAPjNBNzyxvMjBdYGH-wMC5iBXpjitztiw2rbZ3myc6IUC9VMz7Fql_gZ2RRGBjiG5BTmhZQEGbmV1qcW-LqWpqZ71ZllOEcmKgdkpqbGWCY6lFsa2ZlOIGNcRcnLr8DAA2&wfresh=0&id=&uaid=17a094639d7e4e5592811b4bdd2998b0&pcexp=false&username=myownmyusername%40msn.com&popupui=1

After inserting the correct password  and submitting the popup is automatically closed with:
Message from Azure: 'Index: 0' Size: 0' 

Following is the response header by trying to authenticate with IE and monitoring the communications with developer tools
Key	Value
Response	HTTP/1.1 302 Found
Cache-Control	no-cache, no-store
Pragma	no-cache
Content-Type	text/html; charset=utf-8
Expires	-1
Location	https://msopentech.com/?code=AQABAAAAAADRNYRQ3dhRSrm-4K-adpCJ5KtUluQm42L4MuTpy1IqgQiTuJjGpn44Y08AyoPqyH0-GVLQDWz-4HHwgP5DBWRcqkXRunZiSqrIqv6QYAExK_Pl_34Vjlmi0aOW9Pnk_0wb7K0MlZEmC08ICAm2j4DolYuBSQcrfXl00R5dyfLVy4b5D_1BD5Iz6aYY94p2fkpXjxoRqLh3esfSi1ettthEsJaC_KwA7K1ovjvAfiguJ7-SsU3oLM8Ki7K0HBSimB15wzibnVcs8KijR3dgG9qzzwXs-cVWgUL2W_qx6o3-8N-MG7_c_tOy9fGqukBMSDwCYvB0-W1yXhWMQFNTEUokBEpeN_kLmvPnE7y9SNWq50SHRKcn9aRK8NOS0u7v9MVCU6gm3fwKQ_rVhHPvFNKBPVUL253BAlaHgDx-0dKXB61UUfopWQ30t1RWvgAvmYTKW1fZ1bnY1_JdWINKJNipPrKgHMZVQstFovyrAIVGLgMCRzJveD28BKyTBfs3red_06y5_wCMe6MSSMzX6zgGUyG1hqWTwq8u85pBoGBYGbvGqa6nKpMIX6xa_4TcyIPvPiQO5MZHEdWfpyNbHkZFYqvAhwLziN6JcYC-gvfPF4LBgPk2usY7FpfIbo_QV6d26lTlRpRFkO7QpqTn0YLQGpQOTVMHqWaE4U-8LhbS4lvQe9x_1b3fdKrinbKtFRcgAA&session_state=8785df8c-48da-44c1-9f93-e8bc33eb21ac
Server	Microsoft-IIS/8.5
Strict-Transport-Security	max-age=31536000; includeSubDomains
X-Content-Type-Options	nosniff
x-ms-request-id	b177280b-916e-4ba2-aae4-2cdd865a0340
P3P	CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie	ESTSAUTHPERSISTENT=AQABAAEAAADRNYRQ3dhRSrm-4K-adpCJb2XGnSvJTnyWwGHNavmyaNCBD4bL8N4QAiLTmpL_vfkGlm09XlU_OpKtRwnEUmxoqdrjumlcCpfnA_avqtQnocY0wWZfpHK4PUgXh9KSaeBZs9YtxRrr9C5n7z9J6-QAMrneBWCSO3zpOo6SBakWtePsZDib9aa6bS5jQYw6K-Uo7tXicSGl_GAFm06wnaok74eiNMRJoSIkKj6JFHCBJoo76jAwR2L02JHE51eY37xYKm1tNMVYxP2r6DP3oQ-1nNbuV9V0lgqbLjVtT3HFI6MZmY8P6RTJ3Q3FxVGJidIgAA; domain=.login.microsoftonline.com; expires=Thu, 29-Jun-2017 06:57:02 GMT; path=/; secure; HttpOnly
Set-Cookie	ESTSAUTH=QVFBQkFBRUFBQURSTllSUTNkaFJTcm0tNEstYWRwQ0o1ZXVsWEp1QzVYd2R6cDFlQlhNWHIzWnlQNXBmQV8yU2o2dGJvdGlPV0dYRFEtemZSYUpnMUdmV0R2c21ab1RXSVpFUkJiN3VwV0ltOGFpenZPZDhodmJvSmp4Z0NYbjF0TmpMaF8xeEtXSWREUXkxM3podEZoWXgwT1dQTGg1cFFqa0dydnZLTERtakFGVGJzM2syWmY5WlQ5OUYxYmZleDBxTnRmWHJrWTE2R1VrLVNtZm1uZjRGb1NKTGUwWVd3WHI3VUFuOGR0c2g5ci04ZGFKSlJZdkQ5bnRPaEc1RWFzWWlrcVlZbkowejFlVnRDdTNCQTl6WVI2Y3dZVlJZREtMc1ZIUV9EeS1ybWZtX0hfbnFBR0F6MFlMYkpYcjhVTzFlNmNFanV4SHY0NFB2ZkJOUUNjTGxJblRSTXVOWW41eTRCU3ZvZGNMc1hXRmcxR2NIdDhJdlFuS1lqbDBmUy1wcmI2V0NZYVE3ekhjeHU2WHZJT0g5bjFpLUczUDNtNzJ0b3h3cGtBV19zOFdDVzhHTlJFbUktN2l5WmFnOEVfTFhRNDlfMzU4QllLQUk5YVdSakhOOWp2LWhiRnNUS1lvR2l3UUVfa2o5dnRHRDN0SHRjQjl1VS1RdDFlOGdZZVhXZFdkanNCX0NkNnlpWGZlcHl2ZjBuaWdxWWtLS0lBQQ==; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie	ESTSAUTHLIGHT=+8785df8c-48da-44c1-9f93-e8bc33eb21ac; path=/; secure
Set-Cookie	ESTSSC=00; path=/; secure; HttpOnly
Set-Cookie	buid=AQABAAEAAADRNYRQ3dhRSrm-4K-adpCJ-_32We8IuPe5koBYAv7xVW2dd_Tal0cix7_WVg-fwj7oK5bnVZQvyHkhzW50MZkP_GvkPsa3dGdoHsiMErilhukUUSq8UNKW6S1-8hiYaWggAA; expires=Thu, 29-Jun-2017 06:57:02 GMT; path=/; secure; HttpOnly
Set-Cookie	SignInStateCookie=QVFBQkFBQUFBQURSTllSUTNkaFJTcm0tNEstYWRwQ0pGRWM3T2hUWlVYdmJBUnFrOWNCZHdTT2VXVDRzYllBR1U3VmdreWdIYUhXTFRwZUNrUU9JX0s5RmFvZkEwVGhiN3dBMnI4MEZKb2lvNWN1LV9RMEtzZi1PWFFuMTN1YXlDaUNLQXhXNm1raEJQTllDQ0wxY3F4SHFBSFFVQVQxWGo3bHlRSzFvcnhic1MzRUVYZEJ1Rk1wOU9BZlhHUUY3QlpQVzlkTFItUG5lVjB3RXI1dDNKMmRJelB2RnFPUk8yOURGRVpZZFZGQm9GaXdMN0Rza1d2LWdvYV9kN211R3JxTjVhMHV5WEl6a1pLcjNnV3dRMDlfOWs3ZDhhQzFsMHhwNzRuT0Ftem1VVDRpc0lFaERJTjBBMWNHeXhPRVZKcnJQaUFHYmhrMmhLam5ZVFhTVllXNTY2MDlPdVBVcmlLYmpNSVNHUGpqaHVFeTFxb2lMeHgwWDA1QWxsVFdNZ3ZOb3BmTkNSUEoxcVh3Q1ZXYncxTTRlNl9jUjFQWEh0U215S1RFWk1yeFUzdVhuby1qSGpDQUE=; path=/; secure; HttpOnly
Set-Cookie	esctx=AQABAAAAAADRNYRQ3dhRSrm-4K-adpCJuDniCrXlt8sOagakDQ7mbtFjJwaAL6Xtv6goQMRF_K0HdW5wkbISfb_bJq_JCgkki2l5aweZoWDm2Afq1ULWRdsdCFJlVLDeihk0qvUkc3cM2FIy6uAwxwfFvTv60WK-wC1Gmzqt4TztU8Qy2qWtREsLZhO8dvcM-3PmCHBlzU8gAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie	x-ms-gateway-slice=007; path=/; secure; HttpOnly
Set-Cookie	stsservicecookie=ests; path=/; secure; HttpOnly
X-Powered-By	ASP.NET
Date	Sat, 31 Dec 2016 06:57:02 GMT
Content-Length	752

**Comment by viswax2000** [comment] 2017-01-04 09:52
This error is terribly blocking my work. I tried with different outlook subscriptions, and with different eclipse versions but something seriously wrong at the Azure side. The pop-up opens and able to enter the username, and followed by password, and it returns back the to the eclipse where it pop-up this error. 
![azureeclipseloginerror](https://cloud.githubusercontent.com/assets/24229885/21638489/992b286c-d291-11e6-94bb-08e5cb223cb3.png) Please kindly help as last 2 days its seriously affecting my work.

**Comment by martinsawicki** [comment] 2017-01-04 09:59
Sorry to hear this. We have been investigating this and have not been able to reproduce this issue yet on the tooling side. For some reason we do not yet understand, there seems to be something about your and some other users' logins that triggers this behavior, but we do not yet know what it is, as we have not yet figure out how to get it to happen on our side. Stay tuned.

**Comment by viswax2000** [comment] 2017-01-04 10:05
Hi Martin, Thanks for acknowledging my issue. I have been trying few dozen times this issue, and still on top of me. I am struck in the mid of my development. I dont know how to proceed ahead without resolving this. I can share my screen through TeamSite and show the steps that am following. Am using the login user name of nookalav@oulook.com, please let me know if this helps. Thanks.

**Comment by viswax2000** [comment] 2017-01-04 15:21
the following are the eclipse logs that might help you.

!ENTRY com.microsoft.auth.TokenFileStorage 1 0 2017-01-04 19:54:24.631
!MESSAGE filePath = 'C:\installs\eclipseneon\eclipse\..\..\..\Users\nookala\.p2\pool\plugins\com.microsoftopentechnologies.wacommon\.msauth4j\msauth4j.cache'

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 19:54:24.639
!MESSAGE Deserializing...

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 19:54:24.669
!MESSAGE Putting key into the dictionary [hash: 'fbefa3d3']

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 19:54:24.678
!MESSAGE Putting key into the dictionary [hash: '50f5b3d9']

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 19:54:24.679
!MESSAGE Deserialized 2 items to token cache.

!ENTRY com.microsoft.azureexplorer 4 0 2017-01-04 19:54:24.766
!MESSAGE An error occurred when trying to load Storage Accounts

An error occurred when trying to load Storage Accounts for the subscriptions:

Pay-As-You-Go: No User Information for the specified Subscription Id


!ENTRY WACommon 4 0 2017-01-04 19:54:24.900
!MESSAGE An error occurred while attempting to load Virtual Machines.
!STACK 0
com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: No User Information for the specified Subscription Id
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerBaseImpl.getUserInfo(AzureManagerBaseImpl.java:171)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.getUserInfo(AzureArmManagerImpl.java:53)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.requestAzureSDK(AzureArmManagerImpl.java:141)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.getVirtualMachines(AzureArmManagerImpl.java:195)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.vmarm.VMArmServiceModule.refresh(VMArmServiceModule.java:57)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.microsoft.azureexplorer.helpers.IDEHelperImpl$2.run(IDEHelperImpl.java:88)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY WACommon 4 0 2017-01-04 19:54:26.571
!MESSAGE An error occurred while attempting to load Web Apps.
!STACK 0
com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: null
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1420)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestResourceManagementSDK(AzureManagerImpl.java:1336)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getResourceGroupNames(AzureManagerImpl.java:693)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(WebappsModule.java:68)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.microsoft.azureexplorer.helpers.IDEHelperImpl$2.run(IDEHelperImpl.java:88)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.windowsazure.exception.ServiceException: null
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:295)
	at com.microsoft.azure.management.resources.ResourceGroupOperationsImpl.list(ResourceGroupOperationsImpl.java:971)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:887)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:883)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1409)
	... 7 more

!ENTRY WACommon 4 0 2017-01-04 19:54:39.256
!MESSAGE An error occurred while attempting to load Web Apps.
!STACK 0
com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: null
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1420)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestResourceManagementSDK(AzureManagerImpl.java:1336)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getResourceGroupNames(AzureManagerImpl.java:693)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(WebappsModule.java:68)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.microsoft.azureexplorer.helpers.IDEHelperImpl$2.run(IDEHelperImpl.java:88)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.windowsazure.exception.ServiceException: null
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:295)
	at com.microsoft.azure.management.resources.ResourceGroupOperationsImpl.list(ResourceGroupOperationsImpl.java:971)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:887)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:883)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1409)
	... 7 more

**Comment by viswax2000** [comment] 2017-01-04 15:46
Hello Martin, I see its the problem with the subscription. I tried with a corporate level subscription and it gets the data, however i do not understand whats the problem with my subscription as it failed to authenticate. Can you let me know if the below eclipse logs will be of help to check against my subscription

!ENTRY com.microsoft.auth.AcquireTokenInteractiveHandler 1 0 2017-01-04 20:57:59.762
!MESSAGE 
=== AcquireTokenInteractiveHandler params:
	promptBehavior: Auto
	webUi: com.microsoftopentechnologies.wacommon.adauth.SwtBrowserWIndow
	uniqueId: null
	displayableId: null

!ENTRY com.microsoft.auth.AcquireTokenHandlerBase 1 0 2017-01-04 20:57:59.763
!MESSAGE 
=== Token Acquisition started:
	Authority: https://login.windows.net/2d1a296d-5d40-49b3-9e5e-1ded3a44949e/
	Resource: https://management.core.windows.net/
	ClientId: 61d65f5a-6e3b-468b-af73-a033f5098c5c
	CacheType: com.microsoft.auth.TokenCache (2 items)
	Authentication Target: User
	thread name: main
	

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 20:57:59.764
!MESSAGE Looking up cache for a token...

!ENTRY com.microsoft.auth.TokenCache 1 0 2017-01-04 20:57:59.765
!MESSAGE No matching token was found in the cache

!ENTRY com.microsoft.auth.AcquireTokenInteractiveHandler 1 0 2017-01-04 20:57:59.766
!MESSAGE acquireAuthorization...

!ENTRY com.microsoft.auth.AcquireTokenInteractiveHandler 1 0 2017-01-04 20:57:59.767
!MESSAGE using existing authorization code

!ENTRY com.microsoft.auth.HttpHelper 1 0 2017-01-04 20:57:59.768
!MESSAGE sendPostRequestAndDeserializeJsonResponseAsync...

!ENTRY com.microsoft.auth.HttpHelper 4 0 2017-01-04 20:58:00.033
!MESSAGE AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70000: The provided access grant is invalid or malformed.\r\nTrace ID: 480a5d60-15c6-4205-bb4e-51154d08b347\r\nCorrelation ID: 3f90260c-d9d0-4ff5-aba7-dc240710de10\r\nTimestamp: 2017-01-04 15:28:05Z","error_codes":[70002,70000],"timestamp":"2017-01-04 15:28:05Z","trace_id":"480a5d60-15c6-4205-bb4e-51154d08b347","correlation_id":"3f90260c-d9d0-4ff5-aba7-dc240710de10"}

!ENTRY com.microsoft.tooling.msservices.helpers.auth.AADManagerImpl 2 0 2017-01-04 20:58:00.036
!MESSAGE com.microsoft.auth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70000: The provided access grant is invalid or malformed.\r\nTrace ID: 480a5d60-15c6-4205-bb4e-51154d08b347\r\nCorrelation ID: 3f90260c-d9d0-4ff5-aba7-dc240710de10\r\nTimestamp: 2017-01-04 15:28:05Z","error_codes":[70002,70000],"timestamp":"2017-01-04 15:28:05Z","trace_id":"480a5d60-15c6-4205-bb4e-51154d08b347","correlation_id":"3f90260c-d9d0-4ff5-aba7-dc240710de10"}

!ENTRY com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl 2 0 2017-01-04 20:58:00.039
!MESSAGE TenantId 'com.microsoft.auth.tenants.Tenant@3ea102' auth error: com.microsoft.auth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70000: The provided access grant is invalid or malformed.\r\nTrace ID: 480a5d60-15c6-4205-bb4e-51154d08b347\r\nCorrelation ID: 3f90260c-d9d0-4ff5-aba7-dc240710de10\r\nTimestamp: 2017-01-04 15:28:05Z","error_codes":[70002,70000],"timestamp":"2017-01-04 15:28:05Z","trace_id":"480a5d60-15c6-4205-bb4e-51154d08b347","correlation_id":"3f90260c-d9d0-4ff5-aba7-dc240710de10"}

!ENTRY WACommon 4 0 2017-01-04 20:58:00.040
!MESSAGE An error occurred while attempting to sign in to your account.
!STACK 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)

**Comment by hangryfabian** [comment] 2017-01-05 16:18
I am having the same problem. All of a sudden just wont let me sign in. Keep getting Azure Index 0 size 0

**Comment by vladimir-shcherbakov** [comment] 2017-01-05 17:52
The root cause of the issue is that Active Directory endpoint changed protocol and the plugin is unable to get subscription list. Eclipse error message is misleading.

**Comment by viswax2000** [comment] 2017-01-05 18:35
Hi vladimir, thanks for identifying the issue, so any idea how do i go about that ? Will i be able to use my subscription or anything wrong with my subscription settings etc.? Please let me know what i need to do to overcome this. Thanks in advance.

**Comment by martinsawicki** [comment] 2017-01-05 18:39
based on Vlad's findings, it looks like we're able to reproduce this issue now with MSDN subcriptions specficially. Interestingly, we had tested MSDN subscriptions before with no issues, so the AD auth behavior change may have been more recent.
We believe we have found a way to fix this issue on the plugin side. We're looking into releasing an update to the existing plugin over the next few days.

**Comment by viswax2000** [comment] 2017-01-07 17:31
Hi Martin, thanks for identifying the issue successfully, would be really helpful and appreciate if the fix is provided at the earliest. Thanks.

**Comment by viswax2000** [comment] 2017-01-09 09:14
Is there any workaround as a fallback option for now, ie if it is not a problem with previous version of the plugin ? Please let me know

**Comment by timarcher** [comment] 2017-01-09 14:53
I'm having the same issue. I have an MSDN subscription as well. An update for when a release can be provided would be much appreciated if you have any ballpark estimates.

**Comment by martinsawicki** [comment] 2017-01-09 15:50
We're expecting to release an update this week, as soon as we verify all the tests are passing.

**Comment by viswax2000** [comment] 2017-01-10 06:54
Hi Martin, facing another issue since yesterday while trying to upload the webapp to the Azure AppService (with a corporate subscription) as below, it says  "java.net.UnknownHostException: waws-prod-am2-107.ftp.azurewebsites.windows.net", please kindly check on this as well.

!ENTRY com.microsoft.webapp 4 0 2017-01-10 12:21:22.196
!MESSAGE Unable to connect to the FTP server
!STACK 0
com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: Unable to connect to the FTP server
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.publishWebArchiveArtifact(AzureManagerImpl.java:906)
	at com.microsoft.webapp.config.WebAppDeployDialog$WebAppDeployJob$2.run(WebAppDeployDialog.java:955)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.net.UnknownHostException: waws-prod-am2-107.ftp.azurewebsites.windows.net
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getByName(Unknown Source)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:296)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.publishWebArchiveArtifact(AzureManagerImpl.java:872)
	... 28 more

**Comment by martinsawicki** [comment] 2017-01-11 17:32
We have now published an update to the Eclipse plugin which should resolve the MSDN login issue based on our tests. If you still have challenges with MSDN accounts after updating the plugin, pls let us know in this GitHub issue.

(@viswax2000 - can you pls log your latest WebApp issue separately?  This is not related to the MSDN authentication problem. thanks)

**Closed** 2017-01-11 17:32 UTC

**Comment by viswax2000** [comment] 2017-01-12 06:52
Hi Martin, this issue "Message from Azure: Index: 0, Size: 0" looks resolved after updating the Azure Plugin. Also the above issue "Unable to connect to the FTP Server" is resolved after mailing apimgmt@microsoft.com and they seems to have made up the FTP Server. Thanks for following up and arranging a fix for this issue.
