### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    [3711ada0, L:/192.168.1.125:64761 - R:testccconegroupae13.blob.core.windows.net/20.150.90.36:443] Error was received while reading the incoming data. The connection will be closed.

### ISSUE THREAD

**Issue by neo-mamoon** [microsoft/azure-tools-for-java#7910] opened 2023-10-04 17:30 UTC
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x963,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   [3711ada0, L:/192.168.1.125:64761 - R:<REDACTED: user-file-path>:443] Error was received while reading the incoming data. The connection will be closed.
   java.lang.LinkageError: Package versions: jackson-core=2.13.4, jackson-databind=2.13.4-2, jackson-dataformat-xml=2.13.4, jackson-datatype-jsr310=2.13.4, azure-core=1.42.0, Troubleshooting version conflicts: https:/<REDACTED: user-file-path>
<REDACTED: Generic Secret>
```

**Comment by Flanker32** [comment] 2023-10-07 05:45
Duplicate of #7897

**Comment by Flanker32** [comment] 2023-10-07 05:45
@neo-mamoon Thanks for your report and sorry for the trouble, please track the issue in #7897

**Closed as completed by Flanker32** 2023-10-07 05:45 UTC
Labels: Tool: IntelliJ, need more info
