### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@4bfa5857] - other than com.intellij.util.proxy.CommonProxy.ourInstance.

### ISSUE THREAD

**Issue by psoares** [microsoft/azure-tools-for-java#3658] opened 2019-10-11 21:04 UTC
IntelliJ build version: 2019.2.3 IU-192.6817.14
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1440x855,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@4bfa5857] - other than com.intellij.util.proxy.CommonProxy.ourInstance.
This will make some IDEA network calls fail.
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:94)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:78)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at com.mi

**Comment by wezhang** [comment] 2019-10-30 09:01
Thanks @psoares ! @Flanker32 , looks like an application insights issue.

**Comment by Flanker32** [comment] 2019-10-30 09:21
@psoares Thanks for your feedback, could you please share when did this issue occurs and whethere there are any method to reproduce it?

**Comment by andxu** [comment] 2020-06-02 07:55
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was ch... (#2665)

**Comment by vscjavaci** [comment] 2020-06-03 06:46
Close this issue due to duplicate error: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector

**Closed by vscjavaci** 2020-06-03 06:46 UTC
Labels: Feedback, IntelliJ, bug, duplicate
