### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@61df022d when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@27c96585 java.lang.ArrayIndexOutOfBoundsException: 0 >= 0

### ISSUE THREAD

**Issue by alexkit** [microsoft/azure-tools-for-java#7838] opened 2023-09-08 22:47 UTC
IntelliJ build version: 2023.1.5 IU-231.9392.1
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.80.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,2036x1190,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@61df022d when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@27c96585, throwable=java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at <REDACTED: user-file-path>(Vector.java:466)
	at com.microsoft.azure.toolkit.intellij.common.component.TreeUtils.findResourceTreeNode(TreeUtils.java:341)
	at com.microsoft.azure.toolkit.intellij.common.component.TreeUtils.getExistingResourceParentNode

**Comment by Flanker32** [comment] 2023-10-07 06:23
@alexkit Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?

**Comment by alexkit** [comment] 2023-10-07 07:03
@Flanker32 I have just installed Azure toolkit and started to use it. I just noticed the errors in the IDE. I am not sure I know to reproduce it.

**Comment by Flanker32** [comment] 2023-10-08 06:13
@alexkit Got it, thank you for contacting us about this issue. We will continue to investigate this issue and we will update you as soon as we have any updates.

**Comment by wangmingliang-ms** [comment] 2024-02-02 08:01
Duplicate of #8063

**Closed as completed by wangmingliang-ms** 2024-02-02 08:01 UTC
Labels: Tool: IntelliJ, Module: Framework
