### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.

### ISSUE THREAD

**Issue by martin67** [microsoft/azure-tools-for-java#8252] opened 2024-03-14 22:18 UTC
IntelliJ build version: 2023.3.5 IU-233.14808.21
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.85.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1079,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
Caused by: java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.
```

**Comment by wangmingliang-ms** [comment] 2024-09-03 05:45
Duplicate of #8134

**Closed as completed by wangmingliang-ms** 2024-09-03 05:45 UTC
