### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by dejstheman** [microsoft/azure-tools-for-java#5468] opened 2021-07-02 22:25 UTC
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=streaming-api, containerState=DISPOSE_COMPLETED, componentStore=/Users/deji/Documents/dev.nosync/projects/personal/clandestine-old/streaming-api) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=streaming-api, containerState=DISPOSE_COMPLETED, componentStore=/Users/deji/Documents/dev.nosync/projects/personal/clandestine-old/streaming-api) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryServic

**Comment by wangmingliang-ms** [comment] 2021-07-06 05:25
Duplicate of #5439

**Closed by wangmingliang-ms** 2021-07-06 05:25 UTC
