### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files

### ISSUE THREAD

**Issue by thxmasj** [microsoft/azure-tools-for-java#7298] opened 2023-02-08 10:12 UTC
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.73.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1728x1079,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@5d5d2349,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:42)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:35)
```

**Comment by wangmingliang-ms** [comment] 2023-02-24 02:01
Duplicate of #7247

**Closed as completed by wangmingliang-ms** 2023-02-24 02:01 UTC
