### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppPropertyViewProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by romualdbassinot** [microsoft/azure-tools-for-java#8347] opened 2024-04-04 22:10 UTC
IntelliJ build version: 2024.1 RC IU-241.14494.158
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2024.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot check provider com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppPropertyViewProvider [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$getProvidersAsync$sharedProviders$1$1$1.invokeSuspend(FileEditorProviderManagerImpl.kt:108)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
```

**Comment by wangmingliang-ms** [comment] 2024-11-06 03:02
Duplicate of #8143

**Closed as completed by wangmingliang-ms** 2024-11-06 03:02 UTC
