### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot create class com.microsoft.azure.toolkit.intellij.connector.code.spring.YamlCompletionContributor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/azure-toolkit-for-intellij, version=3.83.0-2021.3, package=null, isBundled=false), packagePrefix=null, instanceId=344, state=active))

### ISSUE THREAD

**Issue by kmarx** [microsoft/azure-tools-for-java#8068] opened 2023-12-17 18:15 UTC
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.83.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1010,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@3072e0fc,flags=961,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot create class com.microsoft.azure.toolkit.intellij.connector.code.spring.YamlCompletionContributor (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, descriptorPath=plugin.xml, path=~<REDACTED: user-file-path> <

**Comment by Flanker32** [comment] 2024-01-29 08:49
@kmarx Thanks for your feedback on this issue and apologize for any trouble it has caused. Please track the issue in #8079

**Comment by Flanker32** [comment] 2024-01-29 08:49
Duplicate of #8079

**Closed as completed by Flanker32** 2024-01-29 08:49 UTC
