### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(scope) is a valid function project

### ISSUE THREAD

**Issue by artLeschenko** [microsoft/azure-tools-for-java#7660] opened 2023-07-03 06:56 UTC
IntelliJ build version: 2023.1.3 IC-231.9161.38
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1575,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(scope) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.core.FunctionUtils.isFunctionProject(FunctionUtils.java:189)

**Comment by Flanker32** [comment] 2023-07-03 07:15
Duplicate of #7651

**Closed as completed by Flanker32** 2023-07-03 07:15 UTC
