### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by megatony** [microsoft/azure-tools-for-java#7695] opened 2023-07-18 07:16 UTC
IntelliJ build version: 2023.1.4 IU-231.9225.16
OS: Linux
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1920x964,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: null [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
```

**Comment by Flanker32** [comment] 2023-07-31 08:38
@megatony Thanks a lot for your report and sorry for the late response. Could you please help a bit more info for this issue? Could this issue be stable reproduced? If so, could you please provide the steps to reproduce this issue?

**Comment by wangmingliang-ms** [comment] 2023-08-08 00:07
Duplicate of #4631

**Closed as completed by wangmingliang-ms** 2023-08-08 00:07 UTC
Labels: Tool: IntelliJ, need more info
