### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by inhyeokjo** [microsoft/azure-tools-for-java#6755] opened 2022-07-02 15:25 UTC
IntelliJ build version: 2022.1.3 IU-221.5921.22
OS: Windows 11
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.66.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1537x913,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.registerAction(IntellijAzureActionManager.java:64)
	at com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor.registerActions(ResourceCommonActionsContributor.java:71)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$0(IntellijAzureActionManager.java:57)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.register(IntellijAzureActionManager.java:57)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:132)
```

**Comment by wangmingliang-ms** [comment] 2022-07-20 01:50
Duplicate of #6671

**Closed as completed by wangmingliang-ms** 2022-07-20 01:50 UTC
