### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by ghost** [microsoft/azure-tools-for-java#6655] opened 2022-05-30 08:11 UTC
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.registerAction(IntellijAzureActionManager.java:64)
	at com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor.registerActions(ResourceCommonActionsContributor.java:68)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$0(IntellijAzureActionManager.java:57)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.register(IntellijAzureActionManager.java:57)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:129)
```

**Comment by wangmingliang-ms** [comment] 2022-06-29 05:03
Duplicate of #6671

**Closed as completed by wangmingliang-ms** 2022-06-29 05:03 UTC
Labels: Type: Bug
