### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by NapierPort** [microsoft/azure-tools-for-java#7603] opened 2023-06-05 21:40 UTC
IntelliJ build version: 2023.1.2 IU-231.9011.34
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
```

**Comment by Flanker32** [comment] 2023-07-31 08:47
@NapierPort Thanks for your report and sorry for the late response. Please track this issue in #7703

Duplicate of #7703

**Closed as completed by Flanker32** 2023-07-31 08:47 UTC
