### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.

### ISSUE THREAD

**Issue by mgonblan** [microsoft/azure-tools-for-java#5716] opened 2021-08-18 09:16 UTC
IntelliJ build version: 2021.1.2 IC-211.7442.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.55.1-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x513,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog2,346,153,857x565,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Edit configuration,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,843x558,invalid,layout=javax.

**Comment by Flanker32** [comment] 2021-12-01 07:12
@t-rufang Could you please help looking into this issue

**Comment by t-rufang** [comment] 2021-12-03 02:33
@v-lanjli , could you help repro this bug in the same environment as the customer's environment?

Based on the stack trace that customer provided and the stack trace we found in telemetry,  this bug should happen when we click the "browse" button to select a "Main class name" or when we click the "browse" button to select an "Artifact from local disk".

![image](https://user-images.githubusercontent.com/32627233/144534824-48e96d84-342a-4a37-900d-f7479eb58feb.png)

**Comment by v-lanjli** [comment] 2021-12-08 06:22
@t-rufang This issue cannot repro from my side, and the following is the version of intellij I used:

![image](https://user-images.githubusercontent.com/40199316/145356306-f8df930f-24e7-42b7-96a1-d5616b96b783.png)
![image](https://user-images.githubusercontent.com/40199316/145356381-094c395f-8c66-4003-99e9-67e1606894a4.png)

**Comment by t-rufang** [comment] 2021-12-10 13:33
@mgonblan
 We will close the issue because it cannot be reproduced from our side. Please feel free to reactivate the issue if you could help provide the stable reproduce step,

**Closed as completed by t-rufang** 2021-12-10 13:33 UTC
Labels: Module: HDInsight
