### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Cannot init component state (componentName=connections, componentClass=Impl) [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by saurabhssahu** [microsoft/azure-tools-for-java#7200] opened 2022-12-28 07:57 UTC
IntelliJ build version: 2022.1.4 IC-221.6008.13
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.67.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1287x632,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Cannot init component state (componentName=connections, componentClass=Impl) [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:148)
	at com.microsoft.azure.toolkit.intellij.connector.ResourceConnectionExplorer$ToolWindowFactory.shouldBeAvailable(ResourceConnectionExplorer.java:116)
Caused by: java.lang.IllegalStateException: C:\Users\POT30616\AppData\Roaming\JetBrains\IdeaIC2022.1\plugins\Kotlin\kotlinc doesn't exist
```

**Comment by wangmingliang-ms** [comment] 2023-03-20 02:02
Duplicate of #7154

**Closed as completed by wangmingliang-ms** 2023-03-20 02:02 UTC
