### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.microsoft.azure.toolkit.lib.common.utils.InstallationIdUtils.getHashMac()" is null

### ISSUE THREAD

**Issue by githubmallesh2** [microsoft/azure-tools-for-java#7209] opened 2023-01-02 10:37 UTC
IntelliJ build version: 2022.2.3 IU-222.4345.14
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.70.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x816,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@415b441d,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.microsoft.azure.toolkit.lib.common.utils.InstallationIdUtils.getHashMac()" is null
	at com.microsoft.azure.toolkit.intellij.common.feedback.RateManager$WhenToPopup.runActivity(RateManager.java:110)
```

**Comment by wangmingliang-ms** [comment] 2023-03-20 01:55
Duplicate of #7155

**Closed as completed by wangmingliang-ms** 2023-03-20 01:55 UTC
